## Analysis process - Dianela

In [1]:
from pathlib import Path
import statsmodels.formula.api as smf

import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
raw_data   = Path("G:/Mi unidad/Master_LSE/Git-hub/Economic_Observatory/Data/raw_data")
clean_data = Path("G:/Mi unidad/Master_LSE/Git-hub/Economic_Observatory/Data/cleaning_data")

In [33]:
analysis_data = pd.read_csv(clean_data / "local_indicators_with_LAD_all_sample_sector.csv")
analysis_data.head(50)

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,OBS_Value_Business,OBS_Value_Employment,growth_firms,growth_emp,Area Code,County_or_Unitary_Authority,...,Data accuracy [Happiness],Local Authority District [Anxiety],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety],Observation Status [Anxiety],Data accuracy [Anxiety],Local Authority District [Net additions],"Net additions per 1,000 stock [Net additions]",Homicide Offences (per million population) [Homicide],% living in an area that has a devolution deal with a directly elected mayor [Devolution],_merge
0,2022,E06000001,Hartlepool,Advanced manufacturing,20.0,1485.0,-0.213574,0.295338,E06000001,Hartlepool,...,coefficient of variation is less than or equal...,NaN,3.48,NaN,coefficient of variation is greater than 5% bu...,NaN,11.0,NaN,NaN,both
1,2022,E06000001,Hartlepool,Creative Industries,100.0,785.0,-0.094410,0.032323,E06000001,Hartlepool,...,coefficient of variation is less than or equal...,NaN,3.48,NaN,coefficient of variation is greater than 5% bu...,NaN,11.0,NaN,NaN,both
2,2022,E06000001,Hartlepool,Defence sector,0.0,0.0,0.000000,0.000000,E06000001,Hartlepool,...,coefficient of variation is less than or equal...,NaN,3.48,NaN,coefficient of variation is greater than 5% bu...,NaN,11.0,NaN,NaN,both
3,2022,E06000001,Hartlepool,Digital and Technology,285.0,1395.0,-0.146126,-0.055725,E06000001,Hartlepool,...,coefficient of variation is less than or equal...,NaN,3.48,NaN,coefficient of variation is greater than 5% bu...,NaN,11.0,NaN,NaN,both
4,2022,E06000001,Hartlepool,Financial Services,55.0,265.0,0.000000,0.255620,E06000001,Hartlepool,...,coefficient of variation is less than or equal...,NaN,3.48,NaN,coefficient of variation is greater than 5% bu...,NaN,11.0,NaN,NaN,both
5,2022,E06000001,Hartlepool,Life Sciences,0.0,40.0,0.000000,0.000000,E06000001,Hartlepool,...,coefficient of variation is less than or equal...,NaN,3.48,NaN,coefficient of variation is greater than 5% bu...,NaN,11.0,NaN,NaN,both
6,2022,E06000001,Hartlepool,Professional and Business Services,640.0,2580.0,-0.103643,-0.264062,E06000001,Hartlepool,...,coefficient of variation is less than or equal...,NaN,3.48,NaN,coefficient of variation is greater than 5% bu...,NaN,11.0,NaN,NaN,both
7,2022,E06000002,Middlesbrough,Advanced manufacturing,35.0,715.0,0.325423,0.555087,E06000002,Middlesbrough,...,coefficient of variation is less than or equal...,NaN,3.07,NaN,coefficient of variation is greater than 5% bu...,NaN,9.0,NaN,NaN,both
8,2022,E06000002,Middlesbrough,Creative Industries,190.0,1890.0,-0.051031,0.160251,E06000002,Middlesbrough,...,coefficient of variation is less than or equal...,NaN,3.07,NaN,coefficient of variation is greater than 5% bu...,NaN,9.0,NaN,NaN,both
9,2022,E06000002,Middlesbrough,Defence sector,0.0,0.0,0.000000,0.000000,E06000002,Middlesbrough,...,coefficient of variation is less than or equal...,NaN,3.07,NaN,coefficient of variation is greater than 5% bu...,NaN,9.0,NaN,NaN,both
10,2022,E06000002,Middlesbrough,Digital and Technology,425.0,2505.0,-0.131769,-0.027550,E06000002,Middlesbrough,...,coefficient of variation is less than or equal...,NaN,3.07,NaN,coefficient of variation is greater than 5% bu...,NaN,9.0,NaN,NaN,both
11,2022,E06000002,Middlesbrough,Financial Services,105.0,1300.0,0.000000,-0.210614,E06000002,Middlesbrough,...,coefficient of variation is less than or equal...,NaN,3.07,NaN,coefficient of variation is greater than 5% bu...,NaN,9.0,NaN,NaN,both
12,2022,E06000002,Middlesbrough,Life Sciences,0.0,10.0,0.000000,0.000000,E06000002,Middlesbrough,...,coefficient of variation is less than or equal...,NaN,3.07,NaN,coefficient of variation is greater than 5% bu...,NaN,9.0,NaN,NaN,both
13,2022,E06000002,Middlesbrough,Professional and Business Services,1160.0,7810.0,-0.070657,-0.045670,E06000002,Middlesbrough,...,coefficient of variation is less than or equal...,NaN,3.07,NaN,coefficient of variation is greater than 5% bu...,NaN,9.0,NaN,NaN,both
14,2022,E06000003,Redcar and Cleveland,Advanced manufacturing,35.0,1000.0,-0.130053,-0.135278,E06000003,Redcar and Cleveland,...,coefficient of variation is less than or equal...,NaN,3.25,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
15,2022,E06000003,Redcar and Cleveland,Creative Industries,145.0,380.0,0.187816,0.096361,E06000003,Redcar and Cleveland,...,coefficient of variation is less than or equal...,NaN,3.25,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
16,2022,E06000003,Redcar and Cleveland,Defence sector,0.0,0.0,0.000000,0.000000,E06000003,Redcar and Cleveland,...,coefficient of variation is less than or equal...,NaN,3.25,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
17,2022,E06000003,Redcar and Cleveland,Digital and Technology,360.0,1290.0,-0.053922,-0.252003,E06000003,Redcar and Cleveland,...,coefficient of variation is less than or equal...,NaN,3.25,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
18,2022,E06000003,Redcar and Cleveland,Financial Services,65.0,285.0,0.000000,0.150661,E06000003,Redcar and Cleveland,...,coefficient of variation is less than or equal...,NaN,3.25,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
19,2022,E06000003,Redcar and Cleveland,Life Sciences,0.0,120.0,0.000000,0.000000,E06000003,Redcar and Cleveland,...,coefficient of variation is less than or equal...,NaN,3.25,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
20,2022,E06000003,Redcar and Cleveland,Professional and Business Services,875.0,4485.0,-0.060893,-0.347651,E06000003,Redcar and Cleveland,...,coefficient of variation is less than or equal...,NaN,3.25,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
21,2022,E06000004,Stockton-on-Tees,Advanced manufacturing,85.0,4630.0,0.123614,-0.110293,E06000004,Stockton-on-Tees,...,coefficient of variation is less than or equal...,NaN,3.23,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
22,2022,E06000004,Stockton-on-Tees,Creative Industries,340.0,1590.0,-0.043048,-0.156751,E06000004,Stockton-on-Tees,...,coefficient of variation is less than or equal...,NaN,3.23,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
23,2022,E06000004,Stockton-on-Tees,Defence sector,0.0,0.0,0.000000,0.000000,E06000004,Stockton-on-Tees,...,coefficient of variation is less than or equal...,NaN,3.23,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
24,2022,E06000004,Stockton-on-Tees,Digital and Technology,825.0,6025.0,-0.092444,-0.252383,E06000004,Stockton-on-Tees,...,coefficient of variation is less than or equal...,NaN,3.23,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
25,2022,E06000004,Stockton-on-Tees,Financial Services,210.0,2235.0,0.000000,-0.640111,E06000004,Stockton-on-Tees,...,coefficient of variation is less than or equal...,NaN,3.23,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
26,2022,E06000004,Stockton-on-Tees,Life Sciences,5.0,175.0,0.000000,-0.055263,E06000004,Stockton-on-Tees,...,coefficient of variation is less than or equal...,NaN,3.23,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
27,2022,E06000004,Stockton-on-Tees,Professional and Business Services,1990.0,12950.0,-0.049006,-0.261752,E06000004,Stockton-on-Tees,...,coefficient of variation is less than or equal...,NaN,3.23,NaN,coefficient of variation is greater than 5% bu...,NaN,7.0,NaN,NaN,both
28,2022,E06000005,Darlington,Advanced manufacturing,30.0,1575.0,0.000000,1.296537,E06000005,Darlington,...,coefficient of variation is less than or equal...,NaN,3.38,NaN,coefficient of variation is greater than 5% bu...,NaN,10.0,NaN,NaN,both
29,2022,E06000005,Darlington,Creative Industries,210.0,1045.0,-0.090559,-0.586830,E06000005,Darlington,...,coefficient of variation is less than or equal...,NaN,3.38,NaN,coefficient of variation is greater than 5% bu...,NaN,10.0,NaN,NaN,both
30,2022,E06000005,Darlington,Defence sector,0.0,0.0,0.000000,0.000000,E06000005,Darlington,...,coefficient of variation is less than or equal...,NaN,3.38,NaN,coefficient of variation is greater than 5% bu...,NaN,10.0,NaN,NaN,both
31,2022,E06000005,Darlington,Digital and Technology,310.0,3685.0,-0.120994,-0.216283,E06000005,Darlington,...,coefficient of variation is less than or equal...,NaN,3.38,NaN,coefficient of variation is greater than 5% bu...,NaN,10.0,NaN,NaN,both
32,2022,E06000005,Darlington,Financial Services,135.0,1875.0,-0.036105,0.206492,E06000005,Darlington,...,coefficient of variation is less than or equal...,NaN,3.38,NaN,coefficient of variation is greater than 5% bu...,NaN,10.0,NaN,NaN,both
33,2022,E06000005,Darlington,Life Sciences,0.0,0.0,0.000000,0.000000,E06000005,Darlington,...,coefficient of variation is less than or equal...,NaN,3.38,NaN,coefficient of variation is greater than 5% bu...,NaN,10.0,NaN,NaN,both
34,2022,E06000005,Darlington,Professional and Business Services,1005.0,8025.0,0.050979,-0.006210,E06000005,Darlington,...,coefficient of variation is less than or equal...,NaN,3.38,NaN,coefficient of variation is greater than 5% bu...,NaN,10.0,NaN,NaN,both
35,2022,E06000006,Halton,Advanced manufacturing,85.0,3100.0,0.000000,-0.143917,E06000006,Halton,...,coefficient of variation is less than or equal...,NaN,3.35,NaN,coefficient of variation is greater than 5% bu...,NaN,6.0,NaN,NaN,both
36,2022,E06000006,Halton,Creative Industries,185.0,1790.0,-0.149532,0.118412,E06000006,Halton,...,coefficient of variation is less than or equal...,NaN,3.35,NaN,coefficient of variation is greater than 5% bu...,NaN,6.0,NaN,NaN,both
37,2022,E06000006,Halton,Defence sector,0.0,0.0,0.000000,0.000000,E06000006,Halton,...,coefficient of variation is less than or equal...,NaN,3.35,NaN,coefficient of variation is greater than 5% bu...,NaN,6.0,NaN,NaN,both
38,2022,E06000006,Halton,Digital and Technology,420.0,4650.0,-0.023475,0.030563,E06000006,Halton,...,coefficient of variation is less than or equal...,NaN,3.35,NaN,coefficient of variation is greater than 5% bu...,NaN,6.0,NaN,NaN,both
39,2022,E06000006,Halton,Financial Services,110.0,1675.0,-0.086260,-0.029397,E06000006,Halton,...,coefficient of variation is less than or equal...,NaN,3.35,NaN,coefficient of variation is greater than 5% bu...,NaN,6.0,NaN,NaN,both
40,2022,E06000006,Halton,Life Sciences,15.0,1275.0,0.000000,0.039973,E06000006,Halton,...,coefficient of variation is less than or equal...,NaN,3.35,NaN,coefficient of variation is greater than 5% bu...,NaN,6.0,NaN,NaN,both
41,2022,E06000006,Halton,Professional and Business Services,1030.0,11635.0,-0.083692,-0.234152,E06000006,Halton,...,coefficient of variation is less than or equal...,NaN,3.35,NaN,coefficient of variation is greater than 5% bu...,NaN,6.0,NaN,NaN,both
42,2022,E06000007,Warrington,Advanced manufacturing,90.0,2280.0,-0.152580,0.153713,E06000007,Warrington,...,coefficient of variation is less than or equal...,NaN,3.18,NaN,coefficient of variation is greater than 5% bu...,NaN,16.0,NaN,NaN,both
43,2022,E06000007,Warrington,Creative Industries,740.0,4175.0,-0.090267,0.082320,E06000007,Warrington,...,coefficient of variation is less than or equal...,NaN,3.18,NaN,coefficient of variation is greater than 5% bu...,NaN,16.0,NaN,NaN,both
44,2022,E06000007,Warrington,Defence sector,0.0,0.0,0.000000,0.000000,E06000007,Warrington,...,coefficient of variation is less than or equal...,NaN,3.18,NaN,coefficient of variation is greater than 5% bu...,NaN,16.0,NaN,NaN,both
45,2022,E06000007,Warrington,Digital and Technology,1510.0,14885.0,-0.197537,0.090645,E06000007,Warrington,...,coefficient of variation is less than or equal...,NaN,3.18,NaN,coefficient of variation is greater than 5% bu...,NaN,16.0,NaN,NaN,both
46,2022,E06000007,Warrington,Financial Services,275.0,2095.0,-0.052922,-0.538400,E06000007,Warrington,...,coefficient of variation is less than or equal...,NaN,3.18,NaN,coefficient of variation is greater than 5% bu...,NaN,16.0,NaN,NaN,both
47,2022,E06000007,Warrington,Life Sciences,5.0,450.0,0.000000,0.045359,E06000007,Warrington,...,coefficient of variation is less than or equal...,NaN,3.18,NaN,coefficient of variation is greater than 5% bu...,NaN,16.0,NaN,NaN,both
48,2022,E06000007,Warrington,Professional and Business Services,3895.0,43975.0,-0.103537,-0.158927,E06000007,Warrington,...,coefficient of variation is less than or equal...,NaN,3.18,NaN,coefficient of variation is greater than 5% bu...,NaN,16.0,NaN,NaN,both
49,2022,E06000008,Blackburn with Darwen,Advanced manufacturing,90.0,1880.0,0.180126,0.035167,E06000008,Blackburn with Darwen,...,coefficient of variation is less than or equal...,NaN,3.07,NaN,coefficient of variation is greater than 5% bu...,NaN,9.0,NaN,NaN,both

In [34]:
cols_to_drop = [col for col in analysis_data.columns if 
                col.startswith('Local Authority District') or
                col.startswith('Notes') or
                col.startswith('Data accuracy') or
                col.startswith('Observation Status') or
                col.startswith('Country') or
                col.startswith('Nation') or
                col.startswith('Total value of UK') or               
                col.startswith('Total UK') or 
                col.startswith('% living in') or 
                col.startswith('Homicide Offences')]
# Drop merged variable and pattern-matched columns
analysis_data = analysis_data.drop(columns=['_merge', 'Area Code'] + cols_to_drop)

print(f"Columns dropped: {len(cols_to_drop) + 2}")
print(f"Remaining columns: {analysis_data.shape[1]}")

Columns dropped: 60
Remaining columns: 50

In [35]:
# Columns to exclude from indicators
cols_to_exclude = ['YEAR', 'GEOGRAPHY_CODE', 'GEOGRAPHY_NAME', 
                   'IS8_SECTOR','OBS_Value_Business', 'OBS_Value_Employment',
                   'growth_firms', 'growth_emp']

x = analysis_data.drop(columns=cols_to_exclude)
y = analysis_data[cols_to_exclude]

In [42]:
x

,County_or_Unitary_Authority,Gross Value Added (GVA) per hour worked (£) [GVA per hour],Gross median weekly pay (£) [Weekly pay],"Employment rate, aged 16 to 64 years (%) [Employment rate]","Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]","Gross disposable household income, per head (£) [GDHI per head]",Count of births of new enterprises (control rounded to base 5) [New enterprises],Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises],Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],...,Proportion of children living with obesity at reception age (%) [Reception obesity],Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity],"Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]",Proportion of cancers diagnosed at stages 1 and 2 (%) [Cancer diagnosis],"Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]",Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction],Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile],Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety],"Net additions per 1,000 stock [Net additions]"
0,Hartlepool,29.84,521.2,69.7,4.6,16934.0,280.0,315.0,2430.0,10.0,...,12.68293,27.46781,35.35587,49.21053,37.85297,7.29,7.75,7.57,3.48,11.0
1,Hartlepool,29.84,521.2,69.7,4.6,16934.0,280.0,315.0,2430.0,10.0,...,12.68293,27.46781,35.35587,49.21053,37.85297,7.29,7.75,7.57,3.48,11.0
2,Hartlepool,29.84,521.2,69.7,4.6,16934.0,280.0,315.0,2430.0,10.0,...,12.68293,27.46781,35.35587,49.21053,37.85297,7.29,7.75,7.57,3.48,11.0
3,Hartlepool,29.84,521.2,69.7,4.6,16934.0,280.0,315.0,2430.0,10.0,...,12.68293,27.46781,35.35587,49.21053,37.85297,7.29,7.75,7.57,3.48,11.0
4,Hartlepool,29.84,521.2,69.7,4.6,16934.0,280.0,315.0,2430.0,10.0,...,12.68293,27.46781,35.35587,49.21053,37.85297,7.29,7.75,7.57,3.48,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2480,NaN,NaN,540,74.1,3.8,18038.0,12090.0,11660.0,104520.0,400.0,...,NaN,NaN,NaN,NaN,NaN,7.4,7.69,7.35,3.3,NaN
2481,NaN,NaN,540,74.1,3.8,18038.0,12090.0,11660.0,104520.0,400.0,...,NaN,NaN,NaN,NaN,NaN,7.4,7.69,7.35,3.3,NaN
2482,NaN,NaN,540,74.1,3.8,18038.0,12090.0,11660.0,104520.0,400.0,...,NaN,NaN,NaN,NaN,NaN,7.4,7.69,7.35,3.3,NaN
2483,NaN,NaN,540,74.1,3.8,18038.0,12090.0,11660.0,104520.0,400.0,...,NaN,NaN,NaN,NaN,NaN,7.4,7.69,7.35,3.3,NaN
2484,NaN,NaN,540,74.1,3.8,18038.0,12090.0,11660.0,104520.0,400.0,...,NaN,NaN,NaN,NaN,NaN,7.4,7.69,7.35,3.3,NaN

In [44]:
#With the previous code, I realised that some of the indicators were not numeric, so I will convert them to numeric:
cols_to_convert = [
    'Gross median weekly pay (£) [Weekly pay]',
    'Employment rate, aged 16 to 64 years (%) [Employment rate]',
    'Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]',
    'Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]',
    'Percentage of adults that currently smoke cigarettes (%) [Smokers]',
    'Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]',
    'Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]',
    'Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]',
    'Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]'
]
for col in cols_to_convert:
    x[col] = pd.to_numeric(x[col], errors='coerce')

print(x.dtypes)

County_or_Unitary_Authority                                                                                                                                                       object
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                                                                                       float64
Gross median weekly pay (£) [Weekly pay]                                                                                                                                         float64
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                                                                                       float64
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                                                                                                       float64
Gross disposable household income, per head (£) [GDHI per head]                                                                                                                  float64
Count of births of new enterprises (control rounded to base 5) [New enterprises]                                                                                                 float64
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                                                                                               float64
Count of active enterprises (control rounded to base 5) [Active enterprises]                                                                                                     float64
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                                                                                           float64
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes) [Public transport to employer]    float64
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes) [Drive to employer]                                       float64
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes) [Cycle to employer]                                     float64
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                                                                                               float64
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                                                                                         float64
Percentage of pupils in state-funded schools meeting the expected standard in reading, writing and maths at the end of key stage 2 (%) [KS2 attainment]                          float64
Percentage of young people achieving GCSEs (and equivalent qualifications) in English and maths by age 19 (%) [GCSE by age 19]                                                    object
Percentage of schools rated good or outstanding by Ofsted (%) [Ofsted]                                                                                                            object
Percentage of persistent absences (10% or more missed) for all pupils (%) [Persistent absences]                                                                                  float64
Percentage of persistent absences (10% or more missed) eligible for free school meals in the past 6 years (%) [Persistent absences FSM]                                          float64
Percentage of persistent absences (10% or more missed) for pupils who are looked after continuously for at least 12 months by local authorities (%) [Persistent absences CLA]     object
Percentage of 5-year olds at 'expected level' in communication and language early learning goals (%) [Early years comms]                                                         float64
Percentage of 5-year olds at 'expected level' in literacy early learning goals (%) [Early years literacy]                                                                        float64
Percentage of 5-year olds at 'expected level' in maths early learning goals (%) [Early years maths]                                                                              float64
Count of 19+ Further Education and Skills Learner Achievements (qualifications) [FE and skills achievements]                                                                     float64
Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]                                                                float64
Apprenticeships achieved by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship achievements]                                                          object
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]                                                                                float64
19+ further education and skills participation (per 100,000 population) [FE and skills participation]                                                                            float64
Female Healthy Life Expectancy (years) [Female HLE]                                                                                                                               object
Male Healthy Life Expectancy (years) [Male HLE]                                                                                                                                   object
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                                                                                               float64
Proportion of children living with obesity at reception age (%) [Reception obesity]                                                                                              float64
Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity]                                                                                                    float64
Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]                                                                                             float64
Proportion of cancers diagnosed at stages 1 and 2 (%) [Cancer diagnosis]                                                                                                          object
Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]                                                                       float64
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]                                                                            float64
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]                                                                             float64
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                                                                                                     float64
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                                                                                         float64
Net additions per 1,000 stock [Net additions]                                                                                                                                    float64
dtype: object

In [ ]:
x
x_controls = x.groupby("County_or_Unitary_Authority").mean(numeric_only=True).reset_index()

In [45]:
x_controls.head()

,County_or_Unitary_Authority,Gross Value Added (GVA) per hour worked (£) [GVA per hour],"Gross disposable household income, per head (£) [GDHI per head]",Count of births of new enterprises (control rounded to base 5) [New enterprises],Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises],Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],"Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes) [Public transport to employer]","Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes) [Drive to employer]","Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes) [Cycle to employer]",...,Percentage of 5-year olds at 'expected level' in literacy early learning goals (%) [Early years literacy],Percentage of 5-year olds at 'expected level' in maths early learning goals (%) [Early years maths],Count of 19+ Further Education and Skills Learner Achievements (qualifications) [FE and skills achievements],"Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]","19+ further education and skills participation (per 100,000 population) [FE and skills participation]",Proportion of children living with obesity at reception age (%) [Reception obesity],Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity],"Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]","Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]","Net additions per 1,000 stock [Net additions]"
0,Bath and North East Somerset,28.45,23101.0,835.0,945.0,8980.0,50.0,12.495296,7.943799,10.514685,...,74.3,81.5,1730.0,766.0,3013.0,7.44048,17.30205,21.68340,20.12109,6.0
1,Bedford,32.74,21328.0,965.0,1025.0,8075.0,30.0,11.587914,7.952530,10.505185,...,69.4,76.5,3000.0,876.0,4930.0,8.33333,21.47806,24.02529,29.30756,18.0
2,Blackburn with Darwen,28.48,15025.0,815.0,855.0,6270.0,35.0,9.404357,7.019322,8.619506,...,65.9,72.2,3550.0,1067.0,8923.0,10.35354,24.72406,22.97324,48.34618,9.0
3,Blackpool,28.32,16717.0,795.0,565.0,4670.0,20.0,8.375514,6.636762,7.819612,...,66.2,72.5,3240.0,1222.0,7782.0,11.98630,26.92308,35.62741,52.62189,3.0
4,"Bournemouth, Christchurch and Poole",34.79,21751.0,1935.0,1935.0,17220.0,75.0,NaN,NaN,NaN,...,71.8,79.9,5970.0,929.0,4906.0,6.90162,18.96104,27.92590,27.00597,4.0

In [24]:
threshold = 0.1  # drop columns with more than 10% missing
missing_pct = analysis_data.isnull().mean()  # gives proportion (0 to 1)
cols_to_keep = missing_pct[missing_pct < threshold].index.tolist()
cols_to_drop = missing_pct[missing_pct >= threshold].index.tolist()

print(f"Columns kept:    {len(cols_to_keep)}")
print(f"Columns dropped: {len(cols_to_drop)}")
print(f"\nDropped columns:\n{cols_to_drop}")

# Apply
X_clean = analysis_data[cols_to_keep]

X_clean.head()

Columns kept:    32
Columns dropped: 79

Dropped columns:
['County_or_Unitary_Authority', 'Local Authority District [GVA per hour]', 'Country', 'Nation', 'Local Authority District [Weekly pay]', 'Local Authority District [Employment rate]', 'Local Authority District [Unemployment rate]', 'Local Authority District [GDHI per head]', 'Local Authority District [New enterprises]', 'Local Authority District [Deaths of enterprises]', 'Local Authority District [Active enterprises]', 'Local Authority District [High growth enterprises]', 'Total value of UK exports (£ million) [UK exports]', 'Total UK public-funded gross regional capital and non-capital expenditure on research and development (£ million) [Goverment R&D]', 'Local Authority District [Public transport to employer]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes) [Public transport to employer]', 'Local Authority District [Drive to employer]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes) [Drive to employer]', 'Local Authority District [Cycle to employer]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes) [Cycle to employer]', 'Local Authority District [Broadband availability]', 'Local Authority District [4G area coverage]', 'Local Authority District [KS2 attainment]', 'Percentage of pupils in state-funded schools meeting the expected standard in reading, writing and maths at the end of key stage 2 (%) [KS2 attainment]', 'Local Authority District [GCSE by age 19]', 'Percentage of young people achieving GCSEs (and equivalent qualifications) in English and maths by age 19 (%) [GCSE by age 19]', 'Local Authority District [Ofsted]', 'Percentage of schools rated good or outstanding by Ofsted (%) [Ofsted]', 'Local Authority District [Persistent absences]', 'Percentage of persistent absences (10% or more missed) for all pupils (%) [Persistent absences]', 'Local Authority District [Persistent absences FSM]', 'Percentage of persistent absences (10% or more missed) eligible for free school meals in the past 6 years (%) [Persistent absences FSM]', 'Local Authority District [Persistent absences CLA]', 'Percentage of persistent absences (10% or more missed) for pupils who are looked after continuously for at least 12 months by local authorities (%) [Persistent absences CLA]', 'Local Authority District [Early years comms]', "Percentage of 5-year olds at 'expected level' in communication and language early learning goals (%) [Early years comms]", 'Local Authority District [Early years literacy]', "Percentage of 5-year olds at 'expected level' in literacy early learning goals (%) [Early years literacy]", 'Local Authority District [Early years maths]', "Percentage of 5-year olds at 'expected level' in maths early learning goals (%) [Early years maths]", 'Local Authority District [FE and skills achievements]', 'Count of 19+ Further Education and Skills Learner Achievements (qualifications) [FE and skills achievements]', 'Local Authority District [Apprenticeship starts]', 'Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]', 'Observation Status [Apprenticeship starts]', 'Local Authority District [Apprenticeship achievements]', 'Apprenticeships achieved by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship achievements]', 'Observation Status [Apprenticeship achievements]', 'Local Authority District [Level 3+ qualifications]', 'Local Authority District [FE and skills participation]', '19+ further education and skills participation (per 100,000 population) [FE and skills participation]', 'Local Authority District [Female HLE]', 'Female Healthy Life Expectancy (years) [Female HLE]', 'Local Authority District [Male HLE]', 'Male Healthy Life Expectancy (years) [Male HLE]', 'Local Authority District [Smokers]', 'Local Authority District [Reception obesity]', 'Proportion of children living with obesity at reception age (%) [Reception obesity]', 'Local Authority District [Year 6 obesity]', 'Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity]', 'Local Authority District [Adult obesity]', 'Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]', 'Local Authority District [Cancer diagnosis]', 'Proportion of cancers diagnosed at stages 1 and 2 (%) [Cancer diagnosis]', 'Observation Status [Cancer diagnosis]', 'Local Authority District [Under 75 mortality rate]', 'Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]', 'Local Authority District [Life satisfaction]', 'Observation Status [Life satisfaction]', 'Local Authority District [Worthwhile]', 'Observation Status [Worthwhile]', 'Local Authority District [Happiness]', 'Observation Status [Happiness]', 'Local Authority District [Anxiety]', 'Observation Status [Anxiety]', 'Local Authority District [Net additions]', 'Net additions per 1,000 stock [Net additions]', 'Homicide Offences (per million population) [Homicide]', '% living in an area that has a devolution deal with a directly elected mayor  [Devolution]']

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment,growth_firms,growth_emp,Area Code,...,Percentage of adults that currently smoke cigarettes (%) [Smokers],Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction],Data accuracy [Life satisfaction],Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile],Data accuracy [Worthwhile],Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness],Data accuracy [Happiness],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety],Data accuracy [Anxiety],_merge
0,2022,E06000001,Hartlepool,Professional and Business Services,"Accounting, audit and tax consultancy",25.0,175.0,0.000000,0.839751,E06000001,...,14.3,7.29,coefficient of variation is less than or equal...,7.75,coefficient of variation is less than or equal...,7.57,coefficient of variation is less than or equal...,3.48,coefficient of variation is greater than 5% bu...,both
1,2022,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,15.0,0.000000,-1.558145,E06000001,...,14.3,7.29,coefficient of variation is less than or equal...,7.75,coefficient of variation is less than or equal...,7.57,coefficient of variation is less than or equal...,3.48,coefficient of variation is greater than 5% bu...,both
2,2022,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0,0.000000,0.000000,E06000001,...,14.3,7.29,coefficient of variation is less than or equal...,7.75,coefficient of variation is less than or equal...,7.57,coefficient of variation is less than or equal...,3.48,coefficient of variation is greater than 5% bu...,both
3,2022,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0,0.000000,0.000000,E06000001,...,14.3,7.29,coefficient of variation is less than or equal...,7.75,coefficient of variation is less than or equal...,7.57,coefficient of variation is less than or equal...,3.48,coefficient of variation is greater than 5% bu...,both
4,2022,E06000001,Hartlepool,Financial Services,Asset management and wholesale services,10.0,45.0,-0.374693,0.245122,E06000001,...,14.3,7.29,coefficient of variation is less than or equal...,7.75,coefficient of variation is less than or equal...,7.57,coefficient of variation is less than or equal...,3.48,coefficient of variation is greater than 5% bu...,both

In [26]:
#Variables with growth rates:
X_clean= X_clean.rename(columns={
    'growth_firms': 'Business_growth_rate',
    'growth_emp': 'Employment_growth_rate'
})

In [27]:
X_clean.head()

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment,Business_growth_rate,Employment_growth_rate,Gross Value Added (GVA) per hour worked (£) [GVA per hour],...,Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],Percentage of premises with gigabit-capable broadband (%) [Broadband availability],Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage],Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications],Percentage of adults that currently smoke cigarettes (%) [Smokers],Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction],Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile],Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]
0,2022,E06000001,Hartlepool,Professional and Business Services,"Accounting, audit and tax consultancy",25.0,175.0,0.000000,0.839751,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
1,2022,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,15.0,0.000000,-1.558145,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
2,2022,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
3,2022,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
4,2022,E06000001,Hartlepool,Financial Services,Asset management and wholesale services,10.0,45.0,-0.374693,0.245122,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48

In [28]:
#With the previous code, I realised that some of the indicators were not numeric, so I will convert them to numeric:
cols_to_convert = [
    'Gross median weekly pay (£) [Weekly pay]',
    'Employment rate, aged 16 to 64 years (%) [Employment rate]',
    'Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]',
    'Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]',
    'Percentage of adults that currently smoke cigarettes (%) [Smokers]',
    'Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]',
    'Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]',
    'Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]',
    'Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]'
]
for col in cols_to_convert:
    X_clean[col] = pd.to_numeric(X_clean[col], errors='coerce')

print(X_clean.dtypes)

YEAR                                                                                                       int64
GEOGRAPHY_CODE                                                                                            object
GEOGRAPHY_NAME                                                                                            object
IS8_SECTOR                                                                                                object
FRONTIER_SECTOR                                                                                           object
OBS_Value_Business                                                                                       float64
OBS_Value_Employment                                                                                     float64
Business_growth_rate                                                                                     float64
Employment_growth_rate                                                                                   float64
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               float64
Gross median weekly pay (£) [Weekly pay]                                                                 float64
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               float64
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               float64
Gross disposable household income, per head (£) [GDHI per head]                                          float64
Count of births of new enterprises (control rounded to base 5) [New enterprises]                         float64
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                       float64
Count of active enterprises (control rounded to base 5) [Active enterprises]                             float64
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                   float64
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       float64
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                 float64
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        float64
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       float64
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    float64
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     float64
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                             float64
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                 float64
dtype: object

In [29]:
##Number of missing values after conversion
print(X_clean.isnull().sum())

YEAR                                                                                                       0
GEOGRAPHY_CODE                                                                                             0
GEOGRAPHY_NAME                                                                                             0
IS8_SECTOR                                                                                                 0
FRONTIER_SECTOR                                                                                            0
OBS_Value_Business                                                                                         0
OBS_Value_Employment                                                                                       0
Business_growth_rate                                                                                       0
Employment_growth_rate                                                                                     0
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               198
Gross median weekly pay (£) [Weekly pay]                                                                  44
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               132
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               462
Gross disposable household income, per head (£) [GDHI per head]                                           88
Count of births of new enterprises (control rounded to base 5) [New enterprises]                          88
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        88
Count of active enterprises (control rounded to base 5) [Active enterprises]                              88
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                    88
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       198
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                 198
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        132
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       154
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    352
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     352
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                             352
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                 352
dtype: int64

In [30]:
total = len(X_clean)
missing_pct = (X_clean.isnull().sum() / total * 100).round(1)
print(missing_pct[missing_pct > 0])

Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               2.5
Gross median weekly pay (£) [Weekly pay]                                                                 0.6
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               1.7
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               5.9
Gross disposable household income, per head (£) [GDHI per head]                                          1.1
Count of births of new enterprises (control rounded to base 5) [New enterprises]                         1.1
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                       1.1
Count of active enterprises (control rounded to base 5) [Active enterprises]                             1.1
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                   1.1
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       2.5
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                 2.5
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        1.7
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       2.0
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    4.5
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     4.5
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                             4.5
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                 4.5
dtype: float64

In [31]:
# How many LADs needed the national median fallback?
lads_with_all_missing = X_clean.groupby('GEOGRAPHY_CODE')[col].apply(
    lambda x: x.isnull().all()
).sum()

print(f"LADs with no data at all for {col}: {lads_with_all_missing}")

LADs with no data at all for Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]: 16

One important thing — the wellbeing variables (Life satisfaction, Happiness, Worthwhile, Anxiety) and Unemployment rate tend to be missing in the same 16-21 LADs. This is likely because smaller or more rural LADs don't report these statistics.

For approximately 16-21 LADs (~5%) where no local data was available, missing values were imputed using the national median. These LADs are predominantly smaller or rural authorities with limited data reporting.

In [32]:
# Columns to exclude from indicators
cols_to_exclude = ['YEAR', 'GEOGRAPHY_CODE', 'GEOGRAPHY_NAME', 
                   'IS8_SECTOR', 'FRONTIER_SECTOR', 
                   'OBS_Value_Business', 'OBS_Value_Employment',
                   'Business_growth_rate', 'Employment_growth_rate']

# X — only local indicators
indicators = X_clean.drop(columns=cols_to_exclude)

In [33]:
##Imputations
fallback_summary = {}
for col in indicators.columns:
    lads_all_missing = X_clean.groupby('GEOGRAPHY_CODE')[col].apply(
        lambda x: x.isnull().all()
    ).sum()
    fallback_summary[col] = lads_all_missing
    
fallback_df = pd.DataFrame.from_dict(
    fallback_summary, orient='index', columns=['LADs using national median']
)

fallback_df = fallback_df[fallback_df['LADs using national median'] > 0].sort_values(
    'LADs using national median', ascending=False
)
print(fallback_df)
print(f"Total LADs in dataset: {X_clean['GEOGRAPHY_CODE'].nunique()}")

                                                    LADs using national median
Modelled unemployment rate, aged 16 years and o...                          21
Mean satisfaction with your life nowadays score...                          16
Mean feeling things done in life are worthwhile...                          16
Mean happiness yesterday scored 0 (not at all) ...                          16
Mean anxiety yesterday scored 0 (not at all) - ...                          16
Gross Value Added (GVA) per hour worked (£) [GV...                           9
Percentage of 4G coverage by at least one mobil...                           9
Percentage of premises with gigabit-capable bro...                           9
Percentage of adults that currently smoke cigar...                           7
Employment rate, aged 16 to 64 years (%) [Emplo...                           6
Proportion of the population aged 16 to 64 with...                           6
Count of births of new enterprises (control rou...                           4
Count of high growth enterprises (control round...                           4
Count of deaths of enterprises (control rounded...                           4
Gross disposable household income, per head (£)...                           4
Count of active enterprises (control rounded to...                           4
Gross median weekly pay (£) [Weekly pay]                                     2
Total LADs in dataset: 355

In [ ]:
## I will drop of my analysis modelled unemployment rate, as I have the employment variable:

In [34]:
for col in indicators.columns:
    X_clean[col] = X_clean.groupby('GEOGRAPHY_CODE')[col].transform(
        lambda x: x.fillna(x.median())
    )
    X_clean[col] = X_clean[col].fillna(X_clean[col].median())  # fallback for any remaining missing with the national median

In [35]:
X_clean.head(50)

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment,Business_growth_rate,Employment_growth_rate,Gross Value Added (GVA) per hour worked (£) [GVA per hour],...,Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],Percentage of premises with gigabit-capable broadband (%) [Broadband availability],Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage],Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications],Percentage of adults that currently smoke cigarettes (%) [Smokers],Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction],Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile],Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]
0,2022,E06000001,Hartlepool,Professional and Business Services,"Accounting, audit and tax consultancy",25.0,175.0,0.000000,0.839751,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
1,2022,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,15.0,0.000000,-1.558145,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
2,2022,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
3,2022,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
4,2022,E06000001,Hartlepool,Financial Services,Asset management and wholesale services,10.0,45.0,-0.374693,0.245122,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
5,2022,E06000001,Hartlepool,Advanced manufacturing,Automotive manufacturing,0.0,400.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
6,2022,E06000001,Hartlepool,Advanced manufacturing,Batteries,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
7,2022,E06000001,Hartlepool,Financial Services,Capital markets and retail investment,20.0,90.0,0.271934,0.056512,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
8,2022,E06000001,Hartlepool,Defence sector,Defence Sector,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
9,2022,E06000001,Hartlepool,Digital and Technology,Digital and Technology,285.0,1395.0,-0.146126,-0.055725,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
10,2022,E06000001,Hartlepool,Creative Industries,Film and TV,5.0,40.0,0.000000,-0.115069,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
11,2022,E06000001,Hartlepool,Financial Services,Insurance and reinsurance markets,0.0,20.0,0.000000,0.646627,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
12,2022,E06000001,Hartlepool,Professional and Business Services,Legal services,10.0,225.0,0.000000,-0.104918,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
13,2022,E06000001,Hartlepool,Life Sciences,Life Sciences,0.0,40.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
14,2022,E06000001,Hartlepool,Professional and Business Services,Management consultancy,70.0,100.0,-0.191667,-1.245666,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
15,2022,E06000001,Hartlepool,Creative Industries,"Music, peforming, and visual arts",10.0,70.0,-0.646627,0.679161,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
16,2022,E06000001,Hartlepool,Advanced manufacturing,Others_Advanced manufacturing,20.0,1085.0,-0.213574,0.430641,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
17,2022,E06000001,Hartlepool,Creative Industries,Others_Creative Industries,75.0,660.0,0.000000,0.086874,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
18,2022,E06000001,Hartlepool,Financial Services,Others_Financial Services,25.0,110.0,0.000000,0.378797,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
19,2022,E06000001,Hartlepool,Professional and Business Services,Others_Professional and Business Services,535.0,2080.0,-0.097682,-0.255204,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
20,2022,E06000001,Hartlepool,Total,Total,2795.0,29340.0,-0.014205,-0.077993,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
21,2022,E06000001,Hartlepool,Creative Industries,Video games,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
22,2022,E06000002,Middlesbrough,Professional and Business Services,"Accounting, audit and tax consultancy",40.0,450.0,0.130053,0.808163,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
23,2022,E06000002,Middlesbrough,Creative Industries,Advertising and marketing,15.0,45.0,0.000000,-1.449473,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
24,2022,E06000002,Middlesbrough,Advanced manufacturing,Aerospace manufacturing,0.0,10.0,0.000000,2.397895,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
25,2022,E06000002,Middlesbrough,Advanced manufacturing,Agritech,0.0,10.0,0.000000,2.397895,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
26,2022,E06000002,Middlesbrough,Financial Services,Asset management and wholesale services,30.0,700.0,0.000000,-0.250998,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
27,2022,E06000002,Middlesbrough,Advanced manufacturing,Automotive manufacturing,0.0,15.0,0.000000,0.374693,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
28,2022,E06000002,Middlesbrough,Advanced manufacturing,Batteries,0.0,0.0,0.000000,0.000000,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
29,2022,E06000002,Middlesbrough,Financial Services,Capital markets and retail investment,20.0,235.0,0.000000,-0.275961,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
30,2022,E06000002,Middlesbrough,Defence sector,Defence Sector,0.0,0.0,0.000000,0.000000,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
31,2022,E06000002,Middlesbrough,Digital and Technology,Digital and Technology,425.0,2505.0,-0.131769,-0.027550,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
32,2022,E06000002,Middlesbrough,Creative Industries,Film and TV,5.0,100.0,0.000000,-0.221161,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
33,2022,E06000002,Middlesbrough,Financial Services,Insurance and reinsurance markets,5.0,75.0,0.000000,1.072637,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
34,2022,E06000002,Middlesbrough,Professional and Business Services,Legal services,80.0,600.0,-0.059898,-0.287266,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
35,2022,E06000002,Middlesbrough,Life Sciences,Life Sciences,0.0,10.0,0.000000,0.000000,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
36,2022,E06000002,Middlesbrough,Professional and Business Services,Management consultancy,120.0,200.0,-0.079407,-1.095290,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
37,2022,E06000002,Middlesbrough,Creative Industries,"Music, peforming, and visual arts",20.0,55.0,0.000000,0.767255,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
38,2022,E06000002,Middlesbrough,Advanced manufacturing,Others_Advanced manufacturing,35.0,680.0,0.325423,0.529601,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
39,2022,E06000002,Middlesbrough,Creative Industries,Others_Creative Industries,140.0,1240.0,-0.101096,0.209936,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
40,2022,E06000002,Middlesbrough,Financial Services,Others_Financial Services,50.0,290.0,0.000000,-0.242879,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
41,2022,E06000002,Middlesbrough,Professional and Business Services,Others_Professional and Business Services,920.0,6560.0,-0.078287,-0.002283,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
42,2022,E06000002,Middlesbrough,Total,Total,4410.0,62680.0,-0.013511,0.000080,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
43,2022,E06000002,Middlesbrough,Creative Industries,Video games,10.0,450.0,0.606136,0.546947,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
44,2022,E06000003,Redcar and Cleveland,Professional and Business Services,"Accounting, audit and tax consultancy",25.0,125.0,0.213574,0.221161,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
45,2022,E06000003,Redcar and Cleveland,Creative Industries,Advertising and marketing,15.0,15.0,0.980829,-1.338285,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
46,2022,E06000003,Redcar and Cleveland,Advanced manufacturing,Aerospace manufacturing,0.0,10.0,-1.791759,2.397895,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
47,2022,E06000003,Redcar and Cleveland,Advanced manufacturing,Agritech,5.0,5.0,0.000000,0.000000,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
48,2022,E06000003,Redcar and Cleveland,Financial Services,Asset management and wholesale services,20.0,75.0,0.000000,0.398908,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
49,2022,E06000003,Redcar and Cleveland,Advanced manufacturing,Automotive manufacturing,0.0,300.0,0.000000,0.000000,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25

In [ ]:
lad_vars = (
    X_clean[X_clean["FRONTIER_SECTOR"] == "Total"]
    .groupby("GEOGRAPHY_CODE")
    .agg(
        GEOGRAPHY_NAME  = ("GEOGRAPHY_NAME", "first"),
        Business_growth = ("Business_growth_rate", "first"),  # adjust col name
        Employ_growth   = ("Employ_growth_rate",   "first"),  # adjust col name
        total_bus       = ("OBS_Value_Business", "first"),
        total_emp       = ("OBS_Value_Employment",  "first"),
    )
    .reset_index()
)

# 1b. Calculate sector shares from non-Total rows
sectors = X_clean[X_clean["FRONTIER_SECTOR"] != "Total"].copy()
sectors = sectors.merge(
    lad_vars[["GEOGRAPHY_CODE", "total_bus", "total_emp"]],
    on="GEOGRAPHY_CODE"
)

# Enterprise share per sector
sectors["ent_share"] = sectors["OBS_Value_Business"] / sectors["total_bus"]
# Employment share per sector
sectors["emp_share"] = sectors["OBS_Value_Employment"]  / sectors["total_emp"]

# 1c. Pivot to wide — one column per Frontier sector
ent_wide = sectors.pivot_table(
    index="GEOGRAPHY_CODE", columns="FRONTIER_SECTOR", values="ent_share"
)
ent_wide.columns = [f"ent_share_{c}" for c in ent_wide.columns]

emp_wide = sectors.pivot_table(
    index="GEOGRAPHY_CODE", columns="FRONTIER_SECTOR", values="emp_share"
)
emp_wide.columns = [f"emp_share_{c}" for c in emp_wide.columns]

# 1d. Merge everything together
df_wide = (
    lad_vars
    .set_index("GEOGRAPHY_CODE")
    .join(ent_wide)
    .join(emp_wide)
    .reset_index()
)

print(f"Wide dataset shape: {df_wide.shape}")  # should be ~350 rows
print(df_wide.head())

In [36]:
ddddd

NameError: name 'ddddd' is not defined

In [ ]:
X = X_clean[indicators.columns].copy()
y_bus = X_clean['Business_growth_rate'].reset_index(drop=True)
y_emp = X_clean['Employment_growth_rate'].reset_index(drop=True)

print(f'X shape: {X.shape}, y_business growth shape: {y_bus.shape}, y_employment growth shape: {y_emp.shape}')

X shape: (7810, 17), y_business growth shape: (7810,), y_employment growth shape: (7810,)

In [ ]:
# Standardize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=indicators.columns, 
                            index=X_clean.index)

# Sector dummies
is8_dummies     = pd.get_dummies(X_clean['IS8_SECTOR'], 
                                  prefix='IS8', drop_first=True)
frontier_dummies = pd.get_dummies(X_clean['FRONTIER_SECTOR'], 
                                   prefix='FS', drop_first=True)

In [ ]:
cddddd

In [ ]:
##### LASSO — variable selection 
lasso_bus = LassoCV(cv=10, random_state=42, max_iter=10000).fit(X_scaled, y_bus)
lasso_emp = LassoCV(cv=10, random_state=42, max_iter=10000).fit(X_scaled, y_emp)

selected_bus = [col for col, coef in zip(indicators.columns, lasso_bus.coef_) if coef != 0]
selected_emp = [col for col, coef in zip(indicators.columns, lasso_emp.coef_) if coef != 0]

# LASSO coefficients summary
lasso_bus_df = pd.DataFrame({
    'Variable'   : indicators.columns,
    'Coefficient': lasso_bus.coef_
}).query('Coefficient != 0').sort_values('Coefficient', key=abs, ascending=False)

lasso_emp_df = pd.DataFrame({
    'Variable'   : indicators.columns,
    'Coefficient': lasso_emp.coef_
}).query('Coefficient != 0').sort_values('Coefficient', key=abs, ascending=False)

C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.903e+00, tolerance: 2.159e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.078e+01, tolerance: 2.159e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.842e-01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.214e+00, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.916e+01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.896e+01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.678e+01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.275e+01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.294e+00, tolerance: 2.094e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.592e+01, tolerance: 2.094e-01
  model = cd_fast.enet_coordinate_descent_gram(

In [ ]:
print(f"LASSO — Business growth selected {len(selected_bus)} variables:")
print(lasso_bus_df.to_string(index=False))

LASSO — Business growth selected 8 variables:
                                                                                             Variable  Coefficient
                                           Gross Value Added (GVA) per hour worked (£) [GVA per hour]    -0.009159
                                                             Gross median weekly pay (£) [Weekly pay]    -0.007358
    Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]     0.006564
                             Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]    -0.004866
                   Percentage of premises with gigabit-capable broadband (%) [Broadband availability]    -0.004678
                                   Percentage of adults that currently smoke cigarettes (%) [Smokers]     0.004444
                                           Employment rate, aged 16 to 64 years (%) [Employment rate]     0.002566
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]     0.000382

In [ ]:
print(f"LASSO — Employment growth selected {len(selected_emp)} variables:")
print(lasso_emp_df.to_string(index=False))

LASSO — Employment growth selected 0 variables:
Empty DataFrame
Columns: [Variable, Coefficient]
Index: []

In [ ]:
# ── Sector dummies ────────────────────────────────────────────────
is8_dummies      = pd.get_dummies(X_clean['IS8_SECTOR'],      drop_first=True).astype(float)
frontier_dummies = pd.get_dummies(X_clean['FRONTIER_SECTOR'], drop_first=True).astype(float)

In [ ]:
# ── Modelos CON estandarización ───────────────────────────────────
def run_ols_scaled(y, dummies, label):
    X_ols = pd.concat([
        X_scaled_df[indicators.columns].reset_index(drop=True),
        dummies.reset_index(drop=True)
    ], axis=1).astype(float)
    X_ols = sm.add_constant(X_ols)
    model = sm.OLS(y, X_ols).fit(cov_type='HC3')
    print(f"\n{'='*60}")
    print(f"MODEL (SCALED): {label}")
    print(model.summary())
    return model

# ── Modelos SIN estandarización ───────────────────────────────────
def run_ols_raw(y, dummies, label):
    X_ols = pd.concat([
        X_clean[indicators.columns].reset_index(drop=True),
        dummies.reset_index(drop=True)
    ], axis=1).astype(float)
    X_ols = sm.add_constant(X_ols)
    model = sm.OLS(y, X_ols).fit(cov_type='HC3')
    print(f"\n{'='*60}")
    print(f"MODEL (RAW): {label}")
    print(model.summary())
    return model

### IS8 FIXED EFFECTS

Business outcome

In [ ]:

print("IS8 with standarized local indicators")
m1_scaled = run_ols_scaled(y_bus, is8_dummies, "M1: Business Growth   + IS8 FE")

IS8 with standarized local indicators

============================================================
MODEL (SCALED): M1: Business Growth   + IS8 FE
                             OLS Regression Results
================================================================================
Dep. Variable:     Business_growth_rate   R-squared:                       0.253
Model:                              OLS   Adj. R-squared:                  0.250
Method:                   Least Squares   F-statistic:                     6.821
Date:                  Sun, 15 Mar 2026   Prob (F-statistic):           1.38e-21
Time:                          15:45:56   Log-Likelihood:                -61410.
No. Observations:                  6035   AIC:                         1.229e+05
Df Residuals:                      6011   BIC:                         1.230e+05
Df Model:                            23
Covariance Type:                    HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                    16.8380     94.754      0.178      0.859    -168.876     202.552
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                3.9636     18.593      0.213      0.831     -32.479      40.406
Gross median weekly pay (£) [Weekly pay]                                                                 14.5785     15.598      0.935      0.350     -15.994      45.151
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                0.4539     50.572      0.009      0.993     -98.666      99.574
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               -0.3302    174.461     -0.002      0.998    -342.268     341.607
Gross disposable household income, per head (£) [GDHI per head]                                          14.3415     61.300      0.234      0.815    -105.804     134.487
Count of births of new enterprises (control rounded to base 5) [New enterprises]                        362.7540   2.57e+04      0.014      0.989      -5e+04    5.07e+04
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                     1538.5020   4.43e+04      0.035      0.972   -8.52e+04    8.83e+04
Count of active enterprises (control rounded to base 5) [Active enterprises]                              0.7924   6.19e+04   1.28e-05      1.000   -1.21e+05    1.21e+05
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                 1719.6717   6152.712      0.279      0.780   -1.03e+04    1.38e+04
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       -6.9944     95.100     -0.074      0.941    -193.388     179.399
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                  1.7020     10.833      0.157      0.875     -19.530      22.934
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        12.9360     17.414      0.743      0.458     -21.195      47.067
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       -0.6279     27.973     -0.022      0.982     -55.454      54.198
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    -0.1328     25.434     -0.005      0.996     -49.982      49.716
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     -2.1807     14.939     -0.146      0.884     -31.462      27.100
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                              0.0524     14.517      0.004      0.997     -28.400      28.505
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                  2.1633     26.500      0.082      0.935     -49.776      54.103
Creative Industries                                                                                     243.1549    108.304      2.245      0.025      30.882     455.428
Defence sector                                                                                          -15.4296    218.148     -0.071      0.944    -442.993     412.134
Digital and Technology                                                                                 3259.9366   1209.364      2.696      0.007     889.626    5630.247
Financial Services                                                                                      248.6127    112.435      2.211      0.027      28.243     468.982
Life Sciences                                                                                            30.5563    199.916      0.153      0.879    -361.272     422.385
Professional and Business Services                                                                      842.7817    202.939      4.153      0.000     445.028    1240.536
==============================================================================
Omnibus:                    15348.248   Durbin-Watson:                   2.126
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        278907765.728
Skew:                          28.266   Prob(JB):                         0.00
Kurtosis:                    1054.649   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [ ]:
print("IS8 without standarized local indicators")
m1_raw    = run_ols_raw   (y_bus, is8_dummies, "M1: Business Growth   + IS8 FE")

IS8 without standarized local indicators

============================================================
MODEL (RAW): M1: Business Growth   + IS8 FE
                             OLS Regression Results
================================================================================
Dep. Variable:     Business_growth_rate   R-squared:                       0.253
Model:                              OLS   Adj. R-squared:                  0.250
Method:                   Least Squares   F-statistic:                     6.821
Date:                  Sun, 15 Mar 2026   Prob (F-statistic):           1.38e-21
Time:                          15:45:56   Log-Likelihood:                -61410.
No. Observations:                  6035   AIC:                         1.229e+05
Df Residuals:                      6011   BIC:                         1.230e+05
Df Model:                            23
Covariance Type:                    HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                  -674.8220    919.283     -0.734      0.463   -2476.583    1126.939
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                0.4787      2.245      0.213      0.831      -3.922       4.880
Gross median weekly pay (£) [Weekly pay]                                                                  0.2162      0.231      0.935      0.350      -0.237       0.670
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                0.0790      8.801      0.009      0.993     -17.171      17.329
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               -0.3285    173.557     -0.002      0.998    -340.493     339.836
Gross disposable household income, per head (£) [GDHI per head]                                           0.0013      0.005      0.234      0.815      -0.009       0.012
Count of births of new enterprises (control rounded to base 5) [New enterprises]                          0.0126      0.892      0.014      0.989      -1.735       1.760
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        0.0521      1.499      0.035      0.972      -2.885       2.989
Count of active enterprises (control rounded to base 5) [Active enterprises]                           3.199e-06      0.250   1.28e-05      1.000      -0.490       0.490
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                    1.7603      6.298      0.279      0.780     -10.584      14.104
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       -0.3819      5.192     -0.074      0.941     -10.559       9.795
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                  0.4855      3.090      0.157      0.875      -5.571       6.543
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]         1.4784      1.990      0.743      0.458      -2.422       5.379
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       -0.1634      7.279     -0.022      0.982     -14.430      14.103
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    -0.5398    103.349     -0.005      0.996    -203.101     202.021
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     -8.9761     61.493     -0.146      0.884    -129.500     111.548
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                              0.2033     56.299      0.004      0.997    -110.140     110.546
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                  5.4539     66.811      0.082      0.935    -125.494     136.402
Creative Industries                                                                                     243.1549    108.304      2.245      0.025      30.882     455.428
Defence sector                                                                                          -15.4296    218.148     -0.071      0.944    -442.993     412.134
Digital and Technology                                                                                 3259.9366   1209.364      2.696      0.007     889.626    5630.247
Financial Services                                                                                      248.6127    112.435      2.211      0.027      28.243     468.982
Life Sciences                                                                                            30.5563    199.916      0.153      0.879    -361.272     422.385
Professional and Business Services                                                                      842.7817    202.939      4.153      0.000     445.028    1240.536
==============================================================================
Omnibus:                    15348.248   Durbin-Watson:                   2.126
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        278907765.728
Skew:                          28.266   Prob(JB):                         0.00
Kurtosis:                    1054.649   Cond. No.                     1.55e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.55e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

Employment outcome

In [ ]:
#With standarizaed local indicators
m2_scaled = run_ols_scaled(y_emp, is8_dummies, "M2: Employment Growth + IS8 FE")

============================================================

MODEL (SCALED): M2: Employment Growth + IS8 FE
                              OLS Regression Results
==================================================================================
Dep. Variable:     Employment_growth_rate   R-squared:                       0.295
Model:                                OLS   Adj. R-squared:                  0.292
Method:                     Least Squares   F-statistic:                     11.13
Date:                    Sun, 15 Mar 2026   Prob (F-statistic):           2.88e-40
Time:                            15:45:56   Log-Likelihood:                -73160.
No. Observations:                    6035   AIC:                         1.464e+05
Df Residuals:                        6011   BIC:                         1.465e+05
Df Model:                              23
Covariance Type:                      HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                   663.9930    642.498      1.033      0.301    -595.280    1923.266
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                              211.2011    139.801      1.511      0.131     -62.803     485.205
Gross median weekly pay (£) [Weekly pay]                                                               -240.3826    213.697     -1.125      0.261    -659.220     178.455
Employment rate, aged 16 to 64 years (%) [Employment rate]                                              113.6692    360.166      0.316      0.752    -592.243     819.582
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                              151.0727   1226.098      0.123      0.902   -2252.035    2554.181
Gross disposable household income, per head (£) [GDHI per head]                                         627.6812    623.162      1.007      0.314    -593.693    1849.056
Count of births of new enterprises (control rounded to base 5) [New enterprises]                      -4202.1830    1.8e+05     -0.023      0.981   -3.57e+05    3.48e+05
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                     9713.2997    3.1e+05      0.031      0.975   -5.98e+05    6.17e+05
Count of active enterprises (control rounded to base 5) [Active enterprises]                          -1.994e+04   4.35e+05     -0.046      0.963   -8.73e+05    8.33e+05
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                 4.264e+04   4.35e+04      0.981      0.326   -4.25e+04    1.28e+05
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       82.2177    669.863      0.123      0.902   -1230.689    1395.124
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                -83.1145     87.887     -0.946      0.344    -255.370      89.141
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]       -53.9912    145.044     -0.372      0.710    -338.272     230.290
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       14.7230    200.480      0.073      0.941    -378.210     407.656
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    72.6774    185.913      0.391      0.696    -291.705     437.059
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     14.6675    112.681      0.130      0.896    -206.184     235.519
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                            -85.4667    114.104     -0.749      0.454    -309.106     138.173
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                -20.2549    189.790     -0.107      0.915    -392.237     351.727
Creative Industries                                                                                     636.1655    819.302      0.776      0.437    -969.637    2241.968
Defence sector                                                                                         -478.6972   1595.754     -0.300      0.764   -3606.317    2648.923
Digital and Technology                                                                                  2.44e+04   9135.734      2.670      0.008    6489.411    4.23e+04
Financial Services                                                                                     3602.2277    767.892      4.691      0.000    2097.186    5107.269
Life Sciences                                                                                           528.3310   1226.323      0.431      0.667   -1875.218    2931.880
Professional and Business Services                                                                     4085.3075    747.462      5.466      0.000    2620.309    5550.306
==============================================================================
Omnibus:                    16259.101   Durbin-Watson:                   1.897
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        470148647.257
Skew:                          32.689   Prob(JB):                         0.00
Kurtosis:                    1368.802   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [ ]:
#Without standarised local indicators
m2_raw    = run_ols_raw   (y_emp, is8_dummies, "M2: Employment Growth + IS8 FE")

============================================================
MODEL (RAW): M2: Employment Growth + IS8 FE
                              OLS Regression Results
==================================================================================
Dep. Variable:     Employment_growth_rate   R-squared:                       0.295
Model:                                OLS   Adj. R-squared:                  0.292
Method:                     Least Squares   F-statistic:                     11.13
Date:                    Sun, 15 Mar 2026   Prob (F-statistic):           2.88e-40
Time:                            15:45:56   Log-Likelihood:                -73160.
No. Observations:                    6035   AIC:                         1.464e+05
Df Residuals:                        6011   BIC:                         1.465e+05
Df Model:                              23
Covariance Type:                      HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                 -2802.3255   6715.504     -0.417      0.676    -1.6e+04    1.04e+04
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               25.5059     16.883      1.511      0.131      -7.584      58.596
Gross median weekly pay (£) [Weekly pay]                                                                 -3.5654      3.170     -1.125      0.261      -9.778       2.647
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               19.7825     62.682      0.316      0.752    -103.072     142.637
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                              150.2896   1219.742      0.123      0.902   -2240.361    2540.940
Gross disposable household income, per head (£) [GDHI per head]                                           0.0559      0.056      1.007      0.314      -0.053       0.165
Count of births of new enterprises (control rounded to base 5) [New enterprises]                         -0.1459      6.249     -0.023      0.981     -12.395      12.103
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        0.3287     10.488      0.031      0.975     -20.227      20.885
Count of active enterprises (control rounded to base 5) [Active enterprises]                             -0.0805      1.756     -0.046      0.963      -3.523       3.362
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                   43.6481     44.480      0.981      0.326     -43.532     130.828
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                        4.4889     36.573      0.123      0.902     -67.193      76.171
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                -23.7107     25.072     -0.946      0.344     -72.851      25.430
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        -6.1703     16.576     -0.372      0.710     -38.659      26.318
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                        3.8311     52.167      0.073      0.941     -98.415     106.077
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]   295.3228    755.451      0.391      0.696   -1185.334    1775.980
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     60.3736    463.812      0.130      0.896    -848.680     969.427
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                           -331.4546    442.514     -0.749      0.454   -1198.767     535.858
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                -51.0659    478.492     -0.107      0.915    -988.894     886.762
Creative Industries                                                                                     636.1655    819.302      0.776      0.437    -969.637    2241.968
Defence sector                                                                                         -478.6972   1595.754     -0.300      0.764   -3606.317    2648.923
Digital and Technology                                                                                  2.44e+04   9135.734      2.670      0.008    6489.411    4.23e+04
Financial Services                                                                                     3602.2277    767.892      4.691      0.000    2097.186    5107.269
Life Sciences                                                                                           528.3310   1226.323      0.431      0.667   -1875.218    2931.880
Professional and Business Services                                                                     4085.3075    747.462      5.466      0.000    2620.309    5550.306
==============================================================================
Omnibus:                    16259.101   Durbin-Watson:                   1.897
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        470148647.257
Skew:                          32.689   Prob(JB):                         0.00
Kurtosis:                    1368.802   Cond. No.                     1.55e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.55e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

## FRONTIER SECTOR FIXED EFFECTS

Business outcome

In [ ]:
# With standarised local indicators
m3_scaled = run_ols_scaled(y_bus, frontier_dummies, "M3: Business Growth   + Frontier FE")

============================================================
MODEL (SCALED): M3: Business Growth   + Frontier FE
                             OLS Regression Results
================================================================================
Dep. Variable:     Business_growth_rate   R-squared:                       0.255
Model:                              OLS   Adj. R-squared:                  0.251
Method:                   Least Squares   F-statistic:                     31.21
Date:                  Sun, 15 Mar 2026   Prob (F-statistic):          7.68e-179
Time:                          15:45:56   Log-Likelihood:                -61405.
No. Observations:                  6035   AIC:                         1.229e+05
Df Residuals:                      6001   BIC:                         1.231e+05
Df Model:                            33
Covariance Type:                    HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                   478.4366      9.047     52.885      0.000     460.705     496.168
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                3.9636     18.753      0.211      0.833     -32.791      40.718
Gross median weekly pay (£) [Weekly pay]                                                                 14.5785     15.738      0.926      0.354     -16.267      45.424
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                0.4539     50.676      0.009      0.993     -98.868      99.776
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               -0.3302    174.363     -0.002      0.998    -342.076     341.415
Gross disposable household income, per head (£) [GDHI per head]                                          14.3415     61.231      0.234      0.815    -105.669     134.352
Count of births of new enterprises (control rounded to base 5) [New enterprises]                        362.7540   2.57e+04      0.014      0.989   -4.99e+04    5.06e+04
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                     1538.5020   4.42e+04      0.035      0.972   -8.52e+04    8.83e+04
Count of active enterprises (control rounded to base 5) [Active enterprises]                              0.7924   6.19e+04   1.28e-05      1.000   -1.21e+05    1.21e+05
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                 1719.6717   6143.136      0.280      0.780   -1.03e+04    1.38e+04
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       -6.9944     95.096     -0.074      0.941    -193.379     179.390
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                  1.7020     11.395      0.149      0.881     -20.632      24.036
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        12.9360     17.713      0.730      0.465     -21.780      47.652
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       -0.6279     28.125     -0.022      0.982     -55.751      54.496
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    -0.1328     25.831     -0.005      0.996     -50.761      50.495
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     -2.1807     15.524     -0.140      0.888     -32.607      28.246
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                              0.0524     15.104      0.003      0.997     -29.551      29.656
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                  2.1633     26.699      0.081      0.935     -50.167      54.493
Advertising and marketing                                                                              -183.1831     69.898     -2.621      0.009    -320.180     -46.186
Aerospace manufacturing                                                                                -458.6197    188.519     -2.433      0.015    -828.109     -89.130
Agritech                                                                                               -473.0986    194.969     -2.427      0.015    -855.231     -90.966
Asset management and wholesale services                                                                 -41.9155     15.819     -2.650      0.008     -72.921     -10.910
Automotive manufacturing                                                                               -436.9718    179.478     -2.435      0.015    -788.742     -85.201
Batteries                                                                                              -477.7042    197.069     -2.424      0.015    -863.953     -91.456
Capital markets and retail investment                                                                  -192.0704     74.741     -2.570      0.010    -338.560     -45.581
Defence Sector                                                                                         -477.0282    196.704     -2.425      0.015    -862.560     -91.496
Digital and Technology                                                                                 2798.3380   1205.681      2.321      0.020     435.247    5161.429
Film and TV                                                                                            -163.3662     61.897     -2.639      0.008    -284.683     -42.049
Insurance and reinsurance markets                                                                      -404.9718    165.243     -2.451      0.014    -728.843     -81.101
Legal services                                                                                          -83.5211     32.781     -2.548      0.011    -147.770     -19.272
Life Sciences                                                                                          -431.0423    176.267     -2.445      0.014    -776.519     -85.566
Management consultancy                                                                                 1227.0704    535.467      2.292      0.022     177.575    2276.566
Music, peforming, and visual arts                                                                       -72.3239     24.668     -2.932      0.003    -120.672     -23.975
Video games                                                                                            -454.9014    187.004     -2.433      0.015    -821.422     -88.381
==============================================================================
Omnibus:                    15353.427   Durbin-Watson:                   2.125
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        280228580.060
Skew:                          28.289   Prob(JB):                         0.00
Kurtosis:                    1057.141   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [ ]:
# Without standarised local indicators
m3_raw    = run_ols_raw   (y_bus, frontier_dummies, "M3: Business Growth   + Frontier FE")

============================================================
MODEL (RAW): M3: Business Growth   + Frontier FE
                             OLS Regression Results
================================================================================
Dep. Variable:     Business_growth_rate   R-squared:                       0.255
Model:                              OLS   Adj. R-squared:                  0.251
Method:                   Least Squares   F-statistic:                     31.21
Date:                  Sun, 15 Mar 2026   Prob (F-statistic):          7.70e-179
Time:                          15:45:56   Log-Likelihood:                -61405.
No. Observations:                  6035   AIC:                         1.229e+05
Df Residuals:                      6001   BIC:                         1.231e+05
Df Model:                            33
Covariance Type:                    HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                  -213.2234    930.688     -0.229      0.819   -2037.338    1610.891
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                0.4787      2.265      0.211      0.833      -3.960       4.917
Gross median weekly pay (£) [Weekly pay]                                                                  0.2162      0.233      0.926      0.354      -0.241       0.674
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                0.0790      8.819      0.009      0.993     -17.207      17.365
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               -0.3285    173.459     -0.002      0.998    -340.302     339.645
Gross disposable household income, per head (£) [GDHI per head]                                           0.0013      0.005      0.234      0.815      -0.009       0.012
Count of births of new enterprises (control rounded to base 5) [New enterprises]                          0.0126      0.891      0.014      0.989      -1.733       1.759
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        0.0521      1.497      0.035      0.972      -2.883       2.987
Count of active enterprises (control rounded to base 5) [Active enterprises]                           3.199e-06      0.250   1.28e-05      1.000      -0.490       0.490
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                    1.7603      6.288      0.280      0.780     -10.564      14.085
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       -0.3819      5.192     -0.074      0.941     -10.558       9.794
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                  0.4855      3.251      0.149      0.881      -5.886       6.857
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]         1.4784      2.024      0.730      0.465      -2.489       5.446
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       -0.1634      7.318     -0.022      0.982     -14.507      14.180
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    -0.5398    104.965     -0.005      0.996    -206.267     205.187
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     -8.9761     63.899     -0.140      0.888    -134.215     116.263
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                              0.2033     58.577      0.003      0.997    -114.606     115.012
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                  5.4539     67.314      0.081      0.935    -126.478     137.386
Advertising and marketing                                                                              -183.1831     69.898     -2.621      0.009    -320.180     -46.186
Aerospace manufacturing                                                                                -458.6197    188.519     -2.433      0.015    -828.109     -89.130
Agritech                                                                                               -473.0986    194.969     -2.427      0.015    -855.231     -90.966
Asset management and wholesale services                                                                 -41.9155     15.819     -2.650      0.008     -72.921     -10.910
Automotive manufacturing                                                                               -436.9718    179.478     -2.435      0.015    -788.742     -85.201
Batteries                                                                                              -477.7042    197.069     -2.424      0.015    -863.953     -91.456
Capital markets and retail investment                                                                  -192.0704     74.741     -2.570      0.010    -338.560     -45.581
Defence Sector                                                                                         -477.0282    196.704     -2.425      0.015    -862.560     -91.496
Digital and Technology                                                                                 2798.3380   1205.681      2.321      0.020     435.247    5161.429
Film and TV                                                                                            -163.3662     61.897     -2.639      0.008    -284.683     -42.049
Insurance and reinsurance markets                                                                      -404.9718    165.243     -2.451      0.014    -728.843     -81.101
Legal services                                                                                          -83.5211     32.781     -2.548      0.011    -147.770     -19.272
Life Sciences                                                                                          -431.0423    176.267     -2.445      0.014    -776.519     -85.566
Management consultancy                                                                                 1227.0704    535.467      2.292      0.022     177.575    2276.566
Music, peforming, and visual arts                                                                       -72.3239     24.668     -2.932      0.003    -120.672     -23.975
Video games                                                                                            -454.9014    187.004     -2.433      0.015    -821.422     -88.381
==============================================================================
Omnibus:                    15353.427   Durbin-Watson:                   2.125
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        280228580.060
Skew:                          28.289   Prob(JB):                         0.00
Kurtosis:                    1057.141   Cond. No.                     1.55e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.55e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

Employment outcome

In [ ]:
m4_scaled = run_ols_scaled(y_emp, frontier_dummies, "M4: Employment Growth + Frontier FE")

============================================================
MODEL (SCALED): M4: Employment Growth + Frontier FE
                              OLS Regression Results
==================================================================================
Dep. Variable:     Employment_growth_rate   R-squared:                       0.295
Model:                                OLS   Adj. R-squared:                  0.291
Method:                     Least Squares   F-statistic:                     21.08
Date:                    Sun, 15 Mar 2026   Prob (F-statistic):          1.10e-117
Time:                            15:45:57   Log-Likelihood:                -73159.
No. Observations:                    6035   AIC:                         1.464e+05
Df Residuals:                        6001   BIC:                         1.466e+05
Df Model:                              33
Covariance Type:                      HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                  4982.1408    611.919      8.142      0.000    3782.801    6181.481
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                              211.2011    140.119      1.507      0.132     -63.427     485.829
Gross median weekly pay (£) [Weekly pay]                                                               -240.3826    213.050     -1.128      0.259    -657.954     177.189
Employment rate, aged 16 to 64 years (%) [Employment rate]                                              113.6692    360.391      0.315      0.752    -592.684     820.022
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                              151.0727   1226.174      0.123      0.902   -2252.184    2554.329
Gross disposable household income, per head (£) [GDHI per head]                                         627.6812    621.639      1.010      0.313    -590.709    1846.071
Count of births of new enterprises (control rounded to base 5) [New enterprises]                      -4202.1830    1.8e+05     -0.023      0.981   -3.57e+05    3.48e+05
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                     9713.2997    3.1e+05      0.031      0.975   -5.98e+05    6.17e+05
Count of active enterprises (control rounded to base 5) [Active enterprises]                          -1.994e+04   4.35e+05     -0.046      0.963   -8.73e+05    8.33e+05
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                 4.264e+04   4.34e+04      0.982      0.326   -4.25e+04    1.28e+05
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       82.2177    669.967      0.123      0.902   -1230.894    1395.329
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                -83.1145     88.685     -0.937      0.349    -256.934      90.705
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]       -53.9912    145.339     -0.371      0.710    -338.851     230.869
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       14.7230    200.763      0.073      0.942    -378.765     408.211
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    72.6774    186.605      0.389      0.697    -293.062     438.417
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     14.6675    113.685      0.129      0.897    -208.151     237.486
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                            -85.4667    114.927     -0.744      0.457    -310.719     139.785
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                -20.2549    190.145     -0.107      0.915    -392.931     352.422
Advertising and marketing                                                                             -3140.0986    959.449     -3.273      0.001   -5020.584   -1259.613
Aerospace manufacturing                                                                               -3966.0423   1275.290     -3.110      0.002   -6465.564   -1466.520
Agritech                                                                                              -4897.3380   1621.701     -3.020      0.003   -8075.814   -1718.862
Asset management and wholesale services                                                                 897.0563   1181.755      0.759      0.448   -1419.142    3213.254
Automotive manufacturing                                                                              -3452.3239   1077.082     -3.205      0.001   -5563.366   -1341.282
Batteries                                                                                             -4956.8873   1646.223     -3.011      0.003   -8183.424   -1730.350
Capital markets and retail investment                                                                  -355.4930    780.702     -0.455      0.649   -1885.640    1174.654
Defence Sector                                                                                        -4796.8451   1583.689     -3.029      0.002   -7900.819   -1692.871
Digital and Technology                                                                                 2.008e+04   9133.634      2.198      0.028    2175.378     3.8e+04
Film and TV                                                                                           -3200.9859    989.740     -3.234      0.001   -5140.841   -1261.131
Insurance and reinsurance markets                                                                     -2689.3239    833.583     -3.226      0.001   -4323.116   -1055.532
Legal services                                                                                        -1476.3662    620.056     -2.381      0.017   -2691.654    -261.078
Life Sciences                                                                                         -3789.8169   1210.582     -3.131      0.002   -6162.515   -1417.119
Management consultancy                                                                                  777.8451   1140.249      0.682      0.495   -1457.002    3012.692
Music, peforming, and visual arts                                                                     -3678.6338   1163.779     -3.161      0.002   -5959.599   -1397.669
Video games                                                                                           -4708.2113   1546.500     -3.044      0.002   -7739.296   -1677.127
==============================================================================
Omnibus:                    16262.678   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        470821625.887
Skew:                          32.708   Prob(JB):                         0.00
Kurtosis:                    1369.779   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [ ]:
m4_raw    = run_ols_raw   (y_emp, frontier_dummies, "M4: Employment Growth + Frontier FE")

============================================================
MODEL (RAW): M4: Employment Growth + Frontier FE
                              OLS Regression Results
==================================================================================
Dep. Variable:     Employment_growth_rate   R-squared:                       0.295
Model:                                OLS   Adj. R-squared:                  0.291
Method:                     Least Squares   F-statistic:                     21.08
Date:                    Sun, 15 Mar 2026   Prob (F-statistic):          1.11e-117
Time:                            15:45:57   Log-Likelihood:                -73159.
No. Observations:                    6035   AIC:                         1.464e+05
Df Residuals:                        6001   BIC:                         1.466e+05
Df Model:                              33
Covariance Type:                      HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                  1515.8223   6748.280      0.225      0.822   -1.17e+04    1.47e+04
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               25.5059     16.922      1.507      0.132      -7.660      58.672
Gross median weekly pay (£) [Weekly pay]                                                                 -3.5654      3.160     -1.128      0.259      -9.759       2.628
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               19.7825     62.721      0.315      0.752    -103.148     142.713
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                              150.2896   1219.818      0.123      0.902   -2240.509    2541.088
Gross disposable household income, per head (£) [GDHI per head]                                           0.0559      0.055      1.010      0.313      -0.053       0.164
Count of births of new enterprises (control rounded to base 5) [New enterprises]                         -0.1459      6.249     -0.023      0.981     -12.394      12.103
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        0.3287     10.488      0.031      0.975     -20.227      20.885
Count of active enterprises (control rounded to base 5) [Active enterprises]                             -0.0805      1.756     -0.046      0.963      -3.523       3.362
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                   43.6481     44.463      0.982      0.326     -43.497     130.793
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                        4.4889     36.579      0.123      0.902     -67.204      76.182
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                -23.7107     25.300     -0.937      0.349     -73.298      25.876
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        -6.1703     16.610     -0.371      0.710     -38.725      26.385
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                        3.8311     52.241      0.073      0.942     -98.559     106.221
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]   295.3228    758.265      0.389      0.697   -1190.850    1781.495
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     60.3736    467.943      0.129      0.897    -856.778     977.525
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                           -331.4546    445.705     -0.744      0.457   -1205.021     542.112
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                -51.0659    479.386     -0.107      0.915    -990.645     888.513
Advertising and marketing                                                                             -3140.0986    959.449     -3.273      0.001   -5020.584   -1259.613
Aerospace manufacturing                                                                               -3966.0423   1275.290     -3.110      0.002   -6465.564   -1466.520
Agritech                                                                                              -4897.3380   1621.701     -3.020      0.003   -8075.814   -1718.862
Asset management and wholesale services                                                                 897.0563   1181.755      0.759      0.448   -1419.142    3213.254
Automotive manufacturing                                                                              -3452.3239   1077.082     -3.205      0.001   -5563.366   -1341.282
Batteries                                                                                             -4956.8873   1646.223     -3.011      0.003   -8183.424   -1730.350
Capital markets and retail investment                                                                  -355.4930    780.702     -0.455      0.649   -1885.640    1174.654
Defence Sector                                                                                        -4796.8451   1583.689     -3.029      0.002   -7900.819   -1692.871
Digital and Technology                                                                                 2.008e+04   9133.634      2.198      0.028    2175.378     3.8e+04
Film and TV                                                                                           -3200.9859    989.740     -3.234      0.001   -5140.841   -1261.131
Insurance and reinsurance markets                                                                     -2689.3239    833.583     -3.226      0.001   -4323.116   -1055.532
Legal services                                                                                        -1476.3662    620.056     -2.381      0.017   -2691.654    -261.078
Life Sciences                                                                                         -3789.8169   1210.582     -3.131      0.002   -6162.515   -1417.119
Management consultancy                                                                                  777.8451   1140.249      0.682      0.495   -1457.002    3012.692
Music, peforming, and visual arts                                                                     -3678.6338   1163.779     -3.161      0.002   -5959.599   -1397.669
Video games                                                                                           -4708.2113   1546.500     -3.044      0.002   -7739.296   -1677.127
==============================================================================
Omnibus:                    16262.678   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        470821625.887
Skew:                          32.708   Prob(JB):                         0.00
Kurtosis:                    1369.779   Cond. No.                     1.55e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.55e+07. This might indicate that there are
strong multicollinearity or other numerical problems.