In [1]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\diane\anaconda3\lib\site-packages (19.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install fastparquet

Requirement already satisfied: fastparquet in c:\users\diane\anaconda3\lib\site-packages (2025.12.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.2)
Requirement already satisfied: numpy in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: cramjam>=2.3 in c:\users\diane\anaconda3\lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\users\diane\anaconda3\lib\site-packages (from fastparquet) (2025.3.2)
Requirement already satisfied: packaging in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\diane\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
!pip install fastparquet

Defaulting to user installation because normal site-packages is not writeable
Collecting fastparquet
  Using cached fastparquet-2025.12.0-cp313-cp313-win_amd64.whl.metadata (4.6 kB)
Requirement already satisfied: pandas>=1.5.0 in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.2)
Requirement already satisfied: numpy in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.3)
Collecting cramjam>=2.3 (from fastparquet)
  Using cached cramjam-2.11.0-cp313-cp313-win_amd64.whl.metadata (681 bytes)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\diane\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Using cached fastparquet-2025.12.0-cp313-cp313-win_amd64.whl (667 kB)
Using cached cramjam-2.11.0-cp313-cp313-win_amd64.whl (1.7 MB)
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Installing collected packages: fsspec, cramjam, fastparquet

   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ------------- -------------------------- 1/3 [cramjam]
   -------------------------- ------------- 2/3 [fastparquet]
   -------------------------- ------------- 2/3 [fastparquet]
   -------------------------- ------------- 2/3 [fastparquet]
   -------------------------- ------------- 2/3 [fastparquet]
   -------------------------- ------------- 2/3 [fastparquet]
   -------------------------- ------------- 2/3 [fastparquet]
   ---------------------------------------- 3/3 [fastparquet]

Successfully installed cramjam-2.11.0 fastparquet-2025.12.0 fsspec-2026.2.0

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Python313\python.exe -m pip install --upgrade pip

# LEVEL MACRO

In [4]:
import pandas as pd
from pathlib import Path

raw_data   = Path("G:/Mi unidad/Master_LSE/Git-hub/Economic_Observatory/Data/raw_data")
clean_data = Path("G:/Mi unidad/Master_LSE/Git-hub/Economic_Observatory/Data/cleaning_data")

In [5]:
import pandas as pd

##LAD = Local Authority District: The main administrative divisions in the UK (like councils)
df0_bus = pd.read_parquet(raw_data / "business_counts" / "Business_counts_IS8_LADs.parquet", engine="fastparquet") 
df0_em = pd.read_parquet(raw_data / "employee_counts" / "Employee_counts_IS8_LADs.parquet", engine="fastparquet")

In [6]:
print(df0_bus.shape)
print(df0_em.shape)

(1249600, 9)
(312400, 8)

In [7]:
df0_bus.head(5)

,YEAR,SIZE_BAND,GEOGRAPHY_CODE,GEOGRAPHY_NAME,GEOGRAPHY_TYPE,IS8_SECTOR,FRONTIER_SECTOR,INDUSTRY_CODE,OBS_VALUE
0,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Aerospace manufacturing,303,0
1,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Aerospace manufacturing,3316,0
2,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Agritech,283,0
3,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Automotive manufacturing,29,0
4,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Batteries,272,0

In [8]:
df0_em.head(5)

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,GEOGRAPHY_TYPE,IS8_SECTOR,FRONTIER_SECTOR,INDUSTRY_CODE,OBS_VALUE
0,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Aerospace manufacturing,303,0
1,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Aerospace manufacturing,3316,0
2,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Agritech,283,0
3,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Automotive manufacturing,29,300
4,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Batteries,272,0

In [9]:
print(df0_bus.info())
print(df0_em.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1249600 entries, 0 to 1249599
Data columns (total 9 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   YEAR             1249600 non-null  int16
 1   SIZE_BAND        1249600 non-null  object
 2   GEOGRAPHY_CODE   1249600 non-null  object
 3   GEOGRAPHY_NAME   1249600 non-null  object
 4   GEOGRAPHY_TYPE   1249600 non-null  object
 5   IS8_SECTOR       1249600 non-null  object
 6   FRONTIER_SECTOR  426000 non-null   object
 7   INDUSTRY_CODE    1249600 non-null  object
 8   OBS_VALUE        1249600 non-null  Int64
dtypes: Int64(1), int16(1), object(7)
memory usage: 79.8+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312400 entries, 0 to 312399
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   YEAR             312400 non-null  int16
 1   GEOGRAPHY_CODE   312400 non-null  object
 2   GEOGRAPHY_NAME   312400 non-null  object
 3   GEOGRAPHY_TYPE   312400 non-null  object
 4   IS8_SECTOR       312400 non-null  object
 5   FRONTIER_SECTOR  106500 non-null  object
 6   INDUSTRY_CODE    312400 non-null  object
 7   OBS_VALUE        312400 non-null  Int64
dtypes: Int64(1), int16(1), object(6)
memory usage: 17.6+ MB
None

In [10]:
print(df0_bus.describe())
print(df0_em.describe())

               YEAR     OBS_VALUE
count  1.249600e+06     1249600.0
mean   2.020500e+03     148.40735
std    2.872282e+00  12244.841201
min    2.016000e+03           0.0
25%    2.018000e+03           0.0
50%    2.020500e+03           0.0
75%    2.023000e+03           5.0
max    2.025000e+03     2654770.0
                YEAR      OBS_VALUE
count  312400.000000       312400.0
mean     2019.500000    5255.035515
std         2.872286  276375.011687
min      2015.000000            0.0
25%      2017.000000            0.0
50%      2019.500000           40.0
75%      2022.000000          250.0
max      2024.000000     31477000.0

In [11]:
print(df0_bus['IS8_SECTOR'].unique())
print(df0_em['IS8_SECTOR'].unique())
print(df0_bus['FRONTIER_SECTOR'].unique())
print(df0_em['FRONTIER_SECTOR'].unique())

['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services' 'Total']
['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services' 'Total']
['Aerospace manufacturing' 'Agritech' 'Automotive manufacturing'
 'Batteries' None 'Advertising and marketing' 'Film and TV'
 'Music, peforming, and visual arts' 'Video games'
 'Asset management and wholesale services'
 'Capital markets and retail investment'
 'Insurance and reinsurance markets'
 'Accounting, audit and tax consultancy' 'Legal services'
 'Management consultancy']
['Aerospace manufacturing' 'Agritech' 'Automotive manufacturing'
 'Batteries' None 'Advertising and marketing' 'Film and TV'
 'Music, peforming, and visual arts' 'Video games'
 'Asset management and wholesale services'
 'Capital markets and retail investment'
 'Insurance and reinsurance markets'
 'Accounting, audit and tax consultancy' 'Legal services'
 'Management consultancy']

In [12]:
group_keys = ["YEAR", "GEOGRAPHY_CODE", "GEOGRAPHY_NAME", "IS8_SECTOR", "FRONTIER_SECTOR"]

df0_bus.loc[df0_bus["IS8_SECTOR"] == "Digital and Technology", "FRONTIER_SECTOR"] = "Digital and Technology"
df0_bus.loc[df0_bus["IS8_SECTOR"] == "Defence sector", "FRONTIER_SECTOR"] = "Defence Sector"
df0_bus.loc[df0_bus["IS8_SECTOR"] == "Life Sciences", "FRONTIER_SECTOR"] = "Life Sciences"


df0_em.loc[df0_em["IS8_SECTOR"] == "Digital and Technology", "FRONTIER_SECTOR"] = "Digital and Technology"
df0_em.loc[df0_em["IS8_SECTOR"] == "Defence sector", "FRONTIER_SECTOR"] = "Defence Sector"
df0_em.loc[df0_em["IS8_SECTOR"] == "Life Sciences", "FRONTIER_SECTOR"] = "Life Sciences"


##This groupby is necessary because we have multiple columns in the businees data because is disaggregate by industry sector and size band. For us is interesting at the frontier
## level
df0_bus_grouped = df0_bus.groupby(group_keys, as_index=False)["OBS_VALUE"].sum()
df0_bus_grouped = df0_bus_grouped.rename(columns={"OBS_VALUE": "OBS_Value_Business"})
print(df0_bus_grouped['IS8_SECTOR'].unique())

## Same here, but the employment data is disaggregate by industry sector.
df0_em_grouped = df0_em.groupby(group_keys, as_index=False)["OBS_VALUE"].sum()
df0_em_grouped = df0_em_grouped.rename(columns={"OBS_VALUE": "OBS_Value_Employment"})
print(df0_em_grouped['IS8_SECTOR'].unique())

## Prioritize the business data available and  only we keep those values from employment data that math with business one.
df_macro_data= df0_bus_grouped.merge(
    df0_em_grouped,
    on=group_keys,
    how="inner",  ##First we have left, but I change this for inner to only keep those values that match in both datasets. Then we have a dataset from 2016 to 2024.      
    indicator=True    
)

print(df_macro_data["_merge"].value_counts())

['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services']
['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services']
_merge
both          54315
left_only         0
right_only        0
Name: count, dtype: int64

In [13]:
#no_match_lef = df_merged[df_merged["_merge"] == "left_only"] ## bygroup at the industry sector level

#print(no_match_lef.shape)
#print(no_match_lef["YEAR"].value_counts())

In [14]:
## Employment data - Not merge with business data
#no_match_rig = df_merged[df_merged["_merge"] == "right_only"]
#print(no_match_rig.shape)
#print(no_match_rig["YEAR"].value_counts())

In [15]:
for col in group_keys:  
    df_macro_data[col] = df_macro_data[col].astype("category")

df_macro_data["OBS_Value_Business"] = df_macro_data["OBS_Value_Business"].astype("float32")
df_macro_data["OBS_Value_Employment"] = df_macro_data["OBS_Value_Employment"].astype("float32")
df_macro_data = df_macro_data.drop(columns=["_merge"])
df_macro_data.head()

df_macro_data.to_excel(clean_data / "Macro_data_business_employment.xlsx", sheet_name="data", index=False)
df_macro_data.to_csv(clean_data / "Macro_data_business_employment.csv", index=False)

In [16]:
print(df_macro_data['IS8_SECTOR'].unique())

['Advanced manufacturing', 'Creative Industries', 'Defence sector', 'Digital and Technology', 'Financial Services', 'Life Sciences', 'Professional and Business Services']
Categories (7, object): ['Advanced manufacturing', 'Creative Industries', 'Defence sector', 'Digital and Technology', 'Financial Services', 'Life Sciences', 'Professional and Business Services']

País (England, Wales...)
 └── Región (London, North East...)
      └── LAD (Local Authority District) 
           └── MSOA (Middle Layer Super Output Area)  
                └── LSOA (Lower Layer Super Output Area)
                     └── OA (Output Area)

# LEVEL MICRO

In [17]:
df1_bus = pd.read_parquet(raw_data / "business_counts" / "Business_counts_IS8_MSOAs.parquet", engine="fastparquet") 
df1_em = pd.read_parquet(raw_data / "employee_counts" / "Employee_counts_IS8_MSOAs.parquet", engine="fastparquet")

In [18]:
df1_bus.head()

,YEAR,SIZE_BAND,GEOGRAPHY_CODE,GEOGRAPHY_NAME,GEOGRAPHY_TYPE,IS8_SECTOR,FRONTIER_SECTOR,INDUSTRY_CODE,OBS_VALUE
0,2016,large,E02000984,Bolton 001,2021 super output areas - middle layer,Advanced manufacturing,Aerospace manufacturing,303,0
1,2016,large,E02000984,Bolton 001,2021 super output areas - middle layer,Advanced manufacturing,Aerospace manufacturing,3316,0
2,2016,large,E02000984,Bolton 001,2021 super output areas - middle layer,Advanced manufacturing,Agritech,283,0
3,2016,large,E02000984,Bolton 001,2021 super output areas - middle layer,Advanced manufacturing,Automotive manufacturing,29,0
4,2016,large,E02000984,Bolton 001,2021 super output areas - middle layer,Advanced manufacturing,Batteries,272,0

In [19]:
print(df1_bus['IS8_SECTOR'].unique())
print(df1_em['IS8_SECTOR'].unique())
print(df1_bus['FRONTIER_SECTOR'].unique())
print(df1_em['FRONTIER_SECTOR'].unique())

['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services' 'Total']
['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services' 'Total']
['Aerospace manufacturing' 'Agritech' 'Automotive manufacturing'
 'Batteries' None 'Advertising and marketing' 'Film and TV'
 'Music, peforming, and visual arts' 'Video games'
 'Asset management and wholesale services'
 'Capital markets and retail investment'
 'Insurance and reinsurance markets'
 'Accounting, audit and tax consultancy' 'Legal services'
 'Management consultancy']
['Aerospace manufacturing' 'Agritech' 'Automotive manufacturing'
 'Batteries' None 'Advertising and marketing' 'Film and TV'
 'Music, peforming, and visual arts' 'Video games'
 'Asset management and wholesale services'
 'Capital markets and retail investment'
 'Insurance and reinsurance markets'
 'Accounting, audit and tax consultancy' 'Legal services'
 'Management consultancy']

In [20]:
df1_bus.loc[df1_bus["IS8_SECTOR"] == "Digital and Technology", "FRONTIER_SECTOR"] = "Digital and Technology"
df1_bus.loc[df1_bus["IS8_SECTOR"] == "Defence sector", "FRONTIER_SECTOR"] = "Defence Sector"
df1_bus.loc[df1_bus["IS8_SECTOR"] == "Life Sciences", "FRONTIER_SECTOR"] = "Life Sciences"


df1_em.loc[df1_em["IS8_SECTOR"] == "Digital and Technology", "FRONTIER_SECTOR"] = "Digital and Technology"
df1_em.loc[df1_em["IS8_SECTOR"] == "Defence sector", "FRONTIER_SECTOR"] = "Defence Sector"
df1_em.loc[df1_em["IS8_SECTOR"] == "Life Sciences", "FRONTIER_SECTOR"] = "Life Sciences"


keys = ["YEAR","GEOGRAPHY_CODE", "GEOGRAPHY_NAME", "IS8_SECTOR", "FRONTIER_SECTOR"]

df1_bus_grouped = df1_bus.groupby(keys, as_index=False)['OBS_VALUE'].sum()
df1_bus_grouped = df1_bus_grouped.rename(columns={'OBS_VALUE': 'OBS_Value_Business'})

df1_em_grouped = df1_em.groupby(keys, as_index=False)['OBS_VALUE'].sum()
df1_em_grouped = df1_em_grouped.rename(columns={'OBS_VALUE': 'OBS_Value_Employment'})


df_micro_data = df1_bus_grouped.merge(df1_em_grouped, on=keys, how='inner', indicator=True)

print(df_micro_data["_merge"].value_counts())

_merge
both          270181
left_only          0
right_only         0
Name: count, dtype: int64

In [21]:
for col in keys:
    df_micro_data[col] = df_micro_data[col].astype('category')

df_micro_data['OBS_Value_Business']   = df_micro_data['OBS_Value_Business'].astype('float32')
df_micro_data['OBS_Value_Employment'] = df_micro_data['OBS_Value_Employment'].astype('float32')
df_micro_data = df_micro_data.drop(columns=["_merge"])

df_micro_data.head()
df_micro_data.to_excel(clean_data / "Micro_data_business_employment.xlsx", sheet_name="data", index=False)
df_micro_data.to_csv(clean_data / "Micro_data_business_employment.csv", index=False)

# DEMOGRAPHIC DATA

UK
 └── Country (England, Wales, Scotland, NI)
      └── Region (London, North East...)
           └── County / Unitary Authority
                └── Combined Authority   ← agrupa LADs voluntariamente
                     └── LAD            ← tus bases LAD
                          └── MSOA      ← tus bases MSOA (aquí!)
                               └── LSOA
                                    └── OA

In [32]:
#Combined Authority / City Region: Es una agrupación voluntaria de varios LADs que se unen para gobernar juntos temas como transporte, vivienda y desarrollo 
#económico. Los más famosos son:
    #Greater Manchester Combined Authority  → agrupa 10 LADs
    #West Midlands Combined Authority       → agrupa Birmingham + 6 LADs
    #West Yorkshire Combined Authority      → agrupa Leeds + 4 LADs

import pandas as pd
# Skip first 4 sheets
xls = pd.ExcelFile(raw_data / "local_indicators" / "ONS_local_indicators_package.xlsx")
print(xls.sheet_names)
sheet_names = xls.sheet_names[4:]

['Notes', 'Voluntary TQV', 'Data dictionary', 'Data inclusivity', 'GVA per hour', 'Weekly pay', 'Employment rate', 'Employment rate (NI)', 'Unemployment rate', 'GDHI per head', 'New enterprises', 'Deaths of enterprises', 'Active enterprises', 'High growth enterprises', 'UK exports', 'Inward FDI', 'Outward FDI', 'Goverment R&D', 'Public transport to employer', 'Drive to employer', 'Cycle to employer', 'Broadband availability', '4G area coverage', 'KS2 attainment', 'GCSE by age 19', 'Ofsted', 'Persistent absences', 'Persistent absences FSM', 'Persistent absences CLA', 'Early years comms', 'Early years literacy', 'Early years maths', 'FE and skills achievements', 'Apprenticeship starts', 'Apprenticeship achievements', 'Level 3+ qualifications', 'Level 3+ qualifications (NI)', 'FE and skills participation', 'Female HLE', 'Male HLE', 'Smokers', 'Reception obesity', 'Year 6 obesity', 'Adult obesity', 'Cancer diagnosis', 'Under 75 mortality rate', 'Under 75 mortality rate (NI)', 'Life satisfaction', 'Worthwhile', 'Happiness', 'Anxiety', 'Net additions', 'Homicide', 'Devolution']

In [33]:
dfs = {}

for sheet_name in sheet_names:
    raw_df = pd.read_excel(xls, sheet_name=sheet_name, header=None)
    
    area_row_idx = raw_df[raw_df.iloc[:,0].astype(str).str.contains("Area Code", na=False)].index
    if len(area_row_idx) == 0:
        print(f"Skipping sheet '{sheet_name}' — no 'Area Code' found")
        continue
    header_row = area_row_idx[0]
    
    df = pd.read_excel(xls, sheet_name=sheet_name, header=header_row)
    
    ci_cols = [c for c in df.columns if "Lower 95% Confidence Interval" in str(c) or "Upper 95% Confidence Interval" in str(c)]
    df = df.drop(columns=ci_cols)

    cols = []
    for c in df.columns:
        if c == 'Area Code':
            cols.append(c)
        else:
            cols.append(f"{c} [{sheet_name}]")
    df.columns = cols
    
    dfs[sheet_name] = df

df_local_indicators = None
for sheet_name, df in dfs.items():
    if df_local_indicators is None:
        df_local_indicators = df
    else:
        df_local_indicators = df_local_indicators.merge(df, on='Area Code', how='outer')

print(df_local_indicators.shape)
df_local_indicators.head()

(790, 321)

,Area Code,ITL Level 1 [GVA per hour],County or Unitary Authority [GVA per hour],Local Authority District [GVA per hour],Gross Value Added (GVA) per hour worked (£) [GVA per hour],Notes [GVA per hour],Country [Weekly pay],Nation [Weekly pay],Region [Weekly pay],County or Unitary Authority [Weekly pay],...,Notes [Net additions],Country [Homicide],Nation [Homicide],Region [Homicide],Police Force Area [Homicide],Homicide Offences (per million population) [Homicide],Observation Status [Homicide],Nation [Devolution],Region [Devolution],% living in an area that has a devolution deal with a directly elected mayor [Devolution]
0,E06000001,NaN,Hartlepool,NaN,29.84,NaN,NaN,NaN,NaN,Hartlepool,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E06000002,NaN,Middlesbrough,NaN,29.50,NaN,NaN,NaN,NaN,Middlesbrough,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E06000003,NaN,Redcar and Cleveland,NaN,28.42,NaN,NaN,NaN,NaN,Redcar and Cleveland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E06000004,NaN,Stockton-on-Tees,NaN,39.76,NaN,NaN,NaN,NaN,Stockton-on-Tees,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E06000005,NaN,Darlington,NaN,28.56,NaN,NaN,NaN,NaN,Darlington,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_local_indicators.to_excel(clean_data / "local_indicators_all_sample.xlsx", sheet_name="_all_local_indicators", index=False)
df_local_indicators.to_csv(clean_data / "local_indicators_all_sample.csv", index=False)

In [35]:
df_macro_data_2022 = df_macro_data[df_macro_data['YEAR'] == 2022].reset_index(drop=True)
df_macro_data_2022.head()

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment
0,2022,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0
1,2022,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0
2,2022,E06000001,Hartlepool,Advanced manufacturing,Automotive manufacturing,0.0,400.0
3,2022,E06000001,Hartlepool,Advanced manufacturing,Batteries,0.0,0.0
4,2022,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,15.0

In [36]:
df_macro_data_2022.shape

(6035, 7)

In [37]:
##Merge between macro data and local indicators both at the LAD level.
df_LAD_local_indicators = df_macro_data_2022.merge(
    df_local_indicators,
    left_on='GEOGRAPHY_CODE', 
    right_on='Area Code',   
    how='inner', 
    indicator=True    
)

print(df_LAD_local_indicators["_merge"].value_counts())

df_LAD_local_indicators.head()

_merge
both          6035
left_only        0
right_only       0
Name: count, dtype: int64

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment,Area Code,ITL Level 1 [GVA per hour],County or Unitary Authority [GVA per hour],...,Country [Homicide],Nation [Homicide],Region [Homicide],Police Force Area [Homicide],Homicide Offences (per million population) [Homicide],Observation Status [Homicide],Nation [Devolution],Region [Devolution],% living in an area that has a devolution deal with a directly elected mayor [Devolution],_merge
0,2022,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0,E06000001,NaN,Hartlepool,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,both
1,2022,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0,E06000001,NaN,Hartlepool,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,both
2,2022,E06000001,Hartlepool,Advanced manufacturing,Automotive manufacturing,0.0,400.0,E06000001,NaN,Hartlepool,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,both
3,2022,E06000001,Hartlepool,Advanced manufacturing,Batteries,0.0,0.0,E06000001,NaN,Hartlepool,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,both
4,2022,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,15.0,E06000001,NaN,Hartlepool,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,both

In [38]:
patterns = {
    'County or Unitary Authority': 'County_or_Unitary_Authority',
    'Region': 'Region',
    'Nation': 'Nation',
    'Country': 'Country'
}

for pattern, new_name in patterns.items():
    # Find all columns matching the pattern
    cols = [c for c in df_LAD_local_indicators.columns if c.startswith(pattern)]
    
    print(f"{pattern}: {cols}")  # verify before dropping
    
    # Keep first, drop the rest, rename
    df_LAD_local_indicators = df_LAD_local_indicators.drop(columns=cols[1:])
    df_LAD_local_indicators = df_LAD_local_indicators.rename(columns={cols[0]: new_name})
print(df_LAD_local_indicators.columns.tolist())

County or Unitary Authority: ['County or Unitary Authority [GVA per hour]', 'County or Unitary Authority [Weekly pay]', 'County or Unitary Authority [Employment rate]', 'County or Unitary Authority [Unemployment rate]', 'County or Unitary Authority [GDHI per head]', 'County or Unitary Authority [New enterprises]', 'County or Unitary Authority [Deaths of enterprises]', 'County or Unitary Authority [Active enterprises]', 'County or Unitary Authority [High growth enterprises]', 'County or Unitary Authority [Public transport to employer]', 'County or Unitary Authority [Drive to employer]', 'County or Unitary Authority [Cycle to employer]', 'County or Unitary Authority [Broadband availability]', 'County or Unitary Authority [4G area coverage]', 'County or Unitary Authority [KS2 attainment]', 'County or Unitary Authority [GCSE by age 19]', 'County or Unitary Authority [Ofsted]', 'County or Unitary Authority [Persistent absences]', 'County or Unitary Authority [Persistent absences FSM]', 'County or Unitary Authority [Persistent absences CLA]', 'County or Unitary Authority [Early years comms]', 'County or Unitary Authority [Early years literacy]', 'County or Unitary Authority [Early years maths]', 'County or Unitary Authority [FE and skills achievements]', 'County or Unitary Authority [Apprenticeship starts]', 'County or Unitary Authority [Apprenticeship achievements]', 'County or Unitary Authority [Level 3+ qualifications]', 'County or Unitary Authority [FE and skills participation]', 'County or Unitary Authority [Female HLE]', 'County or Unitary Authority [Male HLE]', 'County or Unitary Authority [Smokers]', 'County or Unitary Authority [Reception obesity]', 'County or Unitary Authority [Year 6 obesity]', 'County or Unitary Authority [Adult obesity]', 'County or Unitary Authority [Cancer diagnosis]', 'County or Unitary Authority [Under 75 mortality rate]', 'County or Unitary Authority [Life satisfaction]', 'County or Unitary Authority [Worthwhile]', 'County or Unitary Authority [Happiness]', 'County or Unitary Authority [Anxiety]', 'County or Unitary Authority [Net additions]']
Region: ['Region [Weekly pay]', 'Region [Employment rate]', 'Region [Unemployment rate]', 'Region [GDHI per head]', 'Region [New enterprises]', 'Region [Deaths of enterprises]', 'Region [Active enterprises]', 'Region [High growth enterprises]', 'Region [Goverment R&D]', 'Region [Public transport to employer]', 'Region [Drive to employer]', 'Region [Cycle to employer]', 'Region [KS2 attainment]', 'Region [GCSE by age 19]', 'Region [Ofsted]', 'Region [Persistent absences]', 'Region [Persistent absences FSM]', 'Region [Persistent absences CLA]', 'Region [Early years comms]', 'Region [Early years literacy]', 'Region [Early years maths]', 'Region [FE and skills achievements]', 'Region [Apprenticeship starts]', 'Region [Apprenticeship achievements]', 'Region [Level 3+ qualifications]', 'Region [FE and skills participation]', 'Region [Female HLE]', 'Region [Male HLE]', 'Region [Smokers]', 'Region [Reception obesity]', 'Region [Year 6 obesity]', 'Region [Adult obesity]', 'Region [Cancer diagnosis]', 'Region [Under 75 mortality rate]', 'Region [Life satisfaction]', 'Region [Worthwhile]', 'Region [Happiness]', 'Region [Anxiety]', 'Region [Net additions]', 'Region [Homicide]', 'Region [Devolution]']
Nation: ['Nation [Weekly pay]', 'Nation [Employment rate]', 'Nation [Employment rate (NI)]', 'Nation [Unemployment rate]', 'Nation [GDHI per head]', 'Nation [New enterprises]', 'Nation [Deaths of enterprises]', 'Nation [Active enterprises]', 'Nation [High growth enterprises]', 'Nation [UK exports]', 'Nation [Goverment R&D]', 'Nation [Public transport to employer]', 'Nation [Drive to employer]', 'Nation [Cycle to employer]', 'Nation [KS2 attainment]', 'Nation [GCSE by age 19]', 'Nation [Ofsted]', 'Nation [Persistent absences]', 'Nation [Persistent absences FSM]', 'Nation [Persistent absences CLA]', 'Nation [Early years comms]', 'Nation [Early years literacy]', 'Nation [Early years maths]', 'Nation [FE and skills achievements]', 'Nation [Apprenticeship starts]', 'Nation [Apprenticeship achievements]', 'Nation [Level 3+ qualifications]', 'Nation [Level 3+ qualifications (NI)]', 'Nation [FE and skills participation]', 'Nation [Female HLE]', 'Nation [Male HLE]', 'Nation [Smokers]', 'Nation [Reception obesity]', 'Nation [Year 6 obesity]', 'Nation [Adult obesity]', 'Nation [Cancer diagnosis]', 'Nation [Under 75 mortality rate]', 'Nation [Under 75 mortality rate (NI)]', 'Nation [Life satisfaction]', 'Nation [Worthwhile]', 'Nation [Happiness]', 'Nation [Anxiety]', 'Nation [Net additions]', 'Nation [Homicide]', 'Nation [Devolution]']
Country: ['Country [Weekly pay]', 'Country [Employment rate]', 'Country [Unemployment rate]', 'Country [GDHI per head]', 'Country [New enterprises]', 'Country [Deaths of enterprises]', 'Country [Active enterprises]', 'Country [High growth enterprises]', 'Country [UK exports]', 'Country [Inward FDI]', 'Country [Outward FDI]', 'Country [Goverment R&D]', 'Country [Level 3+ qualifications]', 'Country [Female HLE]', 'Country [Male HLE]', 'Country [Smokers]', 'Country [Life satisfaction]', 'Country [Worthwhile]', 'Country [Happiness]', 'Country [Anxiety]', 'Country [Homicide]']
['YEAR', 'GEOGRAPHY_CODE', 'GEOGRAPHY_NAME', 'IS8_SECTOR', 'FRONTIER_SECTOR', 'OBS_Value_Business', 'OBS_Value_Employment', 'Area Code', 'ITL Level 1 [GVA per hour]', 'County_or_Unitary_Authority', 'Local Authority District [GVA per hour]', 'Gross Value Added (GVA) per hour worked (£) [GVA per hour]', 'Notes [GVA per hour]', 'Country', 'Nation', 'Region', 'Local Authority District [Weekly pay]', 'Gross median weekly pay (£) [Weekly pay]', 'Notes [Weekly pay]', 'Local Authority District [Employment rate]', 'Combined Authority or City Region [Employment rate]', 'Employment rate, aged 16 to 64 years (%) [Employment rate]', 'Notes [Employment rate]', 'Local Authority District [Employment rate (NI)]', 'Employment rate, aged 16 to 64 years (%) [Employment rate (NI)]', 'Local Authority District [Unemployment rate]', 'Combined Authority or City Region [Unemployment rate]', 'Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]', 'Notes [Unemployment rate]', 'Local Authority District [GDHI per head]', 'Gross disposable household income, per head (£) [GDHI per head]', 'Notes [GDHI per head]', 'Local Authority District [New enterprises]', 'Count of births of new enterprises (control rounded to base 5) [New enterprises]', 'Notes [New enterprises]', 'Local Authority District [Deaths of enterprises]', 'Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]', 'Notes [Deaths of enterprises]', 'Local Authority District [Active enterprises]', 'Count of active enterprises (control rounded to base 5) [Active enterprises]', 'Notes [Active enterprises]', 'Local Authority District [High growth enterprises]', 'Count of high growth enterprises (control rounded to base 5) [High growth enterprises]', 'Notes [High growth enterprises]', 'ITL Level 1 [UK exports]', 'ITL Level 2 [UK exports]', 'Combined Authority or City Region [UK exports]', 'ITL Level 3 [UK exports]', 'Total value of UK exports (£ million) [UK exports]', 'ITL Level 1 [Inward FDI]', 'ITL Level 2 [Inward FDI]', 'Combined Authority or City Region [Inward FDI]', 'Total FDI international investment position in the UK at end period (£ million) [Inward FDI]', 'Notes [Inward FDI]', 'ITL Level 1 [Outward FDI]', 'ITL Level 2 [Outward FDI]', 'Combined Authority or City Region [Outward FDI]', 'Total FDI international investment position abroad at end period (£ million) [Outward FDI]', 'Notes [Outward FDI]', 'Total UK public-funded gross regional capital and non-capital expenditure on research and development (£ million) [Goverment R&D]', 'Local Authority District [Public transport to employer]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes) [Public transport to employer]', 'Notes [Public transport to employer]', 'Local Authority District [Drive to employer]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes) [Drive to employer]', 'Notes [Drive to employer]', 'Local Authority District [Cycle to employer]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes) [Cycle to employer]', 'Notes [Cycle to employer]', 'Local Authority District [Broadband availability]', 'Percentage of premises with gigabit-capable broadband (%) [Broadband availability]', 'Notes [Broadband availability]', 'Local Authority District [4G area coverage]', 'Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]', 'Notes [4G area coverage]', 'Local Authority District [KS2 attainment]', 'Percentage of pupils in state-funded schools meeting the expected standard in reading, writing and maths at the end of key stage 2 (%) [KS2 attainment]', 'Local Authority District [GCSE by age 19]', 'Percentage of young people achieving GCSEs (and equivalent qualifications) in English and maths by age 19 (%) [GCSE by age 19]', 'Notes [GCSE by age 19]', 'Local Authority District [Ofsted]', 'Percentage of schools rated good or outstanding by Ofsted (%) [Ofsted]', 'Local Authority District [Persistent absences]', 'Percentage of persistent absences (10% or more missed) for all pupils (%) [Persistent absences]', 'Notes [Persistent absences]', 'Local Authority District [Persistent absences FSM]', 'Percentage of persistent absences (10% or more missed) eligible for free school meals in the past 6 years (%) [Persistent absences FSM]', 'Notes [Persistent absences FSM]', 'Local Authority District [Persistent absences CLA]', 'Percentage of persistent absences (10% or more missed) for pupils who are looked after continuously for at least 12 months by local authorities (%) [Persistent absences CLA]', 'Notes [Persistent absences CLA]', 'Local Authority District [Early years comms]', "Percentage of 5-year olds at 'expected level' in communication and language early learning goals (%) [Early years comms]", 'Notes [Early years comms]', 'Local Authority District [Early years literacy]', "Percentage of 5-year olds at 'expected level' in literacy early learning goals (%) [Early years literacy]", 'Notes [Early years literacy]', 'Local Authority District [Early years maths]', "Percentage of 5-year olds at 'expected level' in maths early learning goals (%) [Early years maths]", 'Notes [Early years maths]', 'Local Authority District [FE and skills achievements]', 'Count of 19+ Further Education and Skills Learner Achievements (qualifications) [FE and skills achievements]', 'Notes [FE and skills achievements]', 'Local Authority District [Apprenticeship starts]', 'Combined Authority or City Region [Apprenticeship starts]', 'Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]', 'Observation Status [Apprenticeship starts]', 'Notes [Apprenticeship starts]', 'Local Authority District [Apprenticeship achievements]', 'Combined Authority or City Region [Apprenticeship achievements]', 'Apprenticeships achieved by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship achievements]', 'Observation Status [Apprenticeship achievements]', 'Notes [Apprenticeship achievements]', 'Local Authority District [Level 3+ qualifications]', 'Combined Authority or City Region [Level 3+ qualifications]', 'Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]', 'Notes [Level 3+ qualifications]', 'Local Authority District [Level 3+ qualifications (NI)]', 'Proportion of the population aged 16-64 with NVQ3+ qualification (%) [Level 3+ qualifications (NI)]', 'Local Authority District [FE and skills participation]', 'Combined Authority or City Region [FE and skills participation]', '19+ further education and skills participation (per 100,000 population) [FE and skills participation]', 'Notes [FE and skills participation]', 'Local Authority District [Female HLE]', 'Welsh Health Board [Female HLE]', 'Combined Authority or City Region [Female HLE]', 'Female Healthy Life Expectancy (years) [Female HLE]', 'Notes [Female HLE]', 'Local Authority District [Male HLE]', 'Welsh Health Board [Male HLE]', 'Combined Authority or City Region [Male HLE]', 'Male Healthy Life Expectancy (years) [Male HLE]', 'Notes [Male HLE]', 'Local Authority District [Smokers]', 'Percentage of adults that currently smoke cigarettes (%) [Smokers]', 'Notes [Smokers]', 'Local Authority District [Reception obesity]', 'Combined Authority or City Region [Reception obesity]', 'Proportion of children living with obesity at reception age (%) [Reception obesity]', 'Observation Status [Reception obesity]', 'Local Authority District [Year 6 obesity]', 'Combined Authority or City Region [Year 6 obesity]', 'Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity]', 'Observation Status [Year 6 obesity]', 'Local Authority District [Adult obesity]', 'Combined Authority or City Region [Adult obesity]', 'Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]', 'Notes [Adult obesity]', 'Local Authority District [Cancer diagnosis]', 'Combined Authority or City Region [Cancer diagnosis]', 'Proportion of cancers diagnosed at stages 1 and 2 (%) [Cancer diagnosis]', 'Observation Status [Cancer diagnosis]', 'Local Authority District [Under 75 mortality rate]', 'Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]', 'Observation Status [Under 75 mortality rate]', 'Local Authority District [Under 75 mortality rate (NI)]', 'Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate (NI)]', 'Local Authority District [Life satisfaction]', 'Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]', 'Observation Status [Life satisfaction]', 'Data accuracy [Life satisfaction]', 'Notes [Life satisfaction]', 'Local Authority District [Worthwhile]', 'Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]', 'Observation Status [Worthwhile]', 'Data accuracy [Worthwhile]', 'Notes [Worthwhile]', 'Local Authority District [Happiness]', 'Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]', 'Observation Status [Happiness]', 'Data accuracy [Happiness]', 'Notes [Happiness]', 'Local Authority District [Anxiety]', 'Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]', 'Observation Status [Anxiety]', 'Data accuracy [Anxiety]', 'Notes [Anxiety]', 'Local Authority District [Net additions]', 'Net additions per 1,000 stock [Net additions]', 'Notes [Net additions]', 'Police Force Area [Homicide]', 'Homicide Offences (per million population) [Homicide]', 'Observation Status [Homicide]', '% living in an area that has a devolution deal with a directly elected mayor  [Devolution]', '_merge']

In [39]:
df_LAD_local_indicators.head()

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment,Area Code,ITL Level 1 [GVA per hour],County_or_Unitary_Authority,...,Data accuracy [Anxiety],Notes [Anxiety],Local Authority District [Net additions],"Net additions per 1,000 stock [Net additions]",Notes [Net additions],Police Force Area [Homicide],Homicide Offences (per million population) [Homicide],Observation Status [Homicide],% living in an area that has a devolution deal with a directly elected mayor [Devolution],_merge
0,2022,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0,E06000001,NaN,Hartlepool,...,coefficient of variation is greater than 5% bu...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,both
1,2022,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0,E06000001,NaN,Hartlepool,...,coefficient of variation is greater than 5% bu...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,both
2,2022,E06000001,Hartlepool,Advanced manufacturing,Automotive manufacturing,0.0,400.0,E06000001,NaN,Hartlepool,...,coefficient of variation is greater than 5% bu...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,both
3,2022,E06000001,Hartlepool,Advanced manufacturing,Batteries,0.0,0.0,E06000001,NaN,Hartlepool,...,coefficient of variation is greater than 5% bu...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,both
4,2022,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,15.0,E06000001,NaN,Hartlepool,...,coefficient of variation is greater than 5% bu...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,both

In [44]:
df_LAD_local_indicators.describe()

,OBS_Value_Business,OBS_Value_Employment,Gross Value Added (GVA) per hour worked (£) [GVA per hour],"Employment rate, aged 16 to 64 years (%) [Employment rate (NI)]","Gross disposable household income, per head (£) [GDHI per head]",Count of births of new enterprises (control rounded to base 5) [New enterprises],Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises],Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],Total FDI international investment position in the UK at end period (£ million) [Inward FDI],...,"Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]",Proportion of the population aged 16-64 with NVQ3+ qualification (%) [Level 3+ qualifications (NI)],"19+ further education and skills participation (per 100,000 population) [FE and skills participation]",Proportion of children living with obesity at reception age (%) [Reception obesity],Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity],"Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]","Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]","Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate (NI)]","Net additions per 1,000 stock [Net additions]",% living in an area that has a devolution deal with a directly elected mayor [Devolution]
count,6035.000000,6.035000e+03,5882.000000,0.0,5967.000000,5967.000000,5967.000000,5.967000e+03,5967.000000,0.0,...,5049.000000,0.0,5049.000000,4981.000000,4981.000000,4981.000000,4981.000000,0.0,4981.000000,1.700000e+01
mean,459.300751,3.608229e+03,36.429624,NaN,22440.886040,3704.074074,3800.868946,3.188997e+04,125.683761,NaN,...,954.390572,NaN,5233.552189,8.773504,21.518803,26.285858,29.373295,NaN,9.665529,4.106241e+01
std,7353.239746,5.302837e+04,8.382263,NaN,11287.635075,28957.566706,29717.774005,2.490954e+05,982.509824,NaN,...,267.594402,NaN,1265.251982,1.796656,4.323257,5.751046,7.820262,NaN,5.381971,7.324107e-15
min,0.000000,0.000000e+00,23.840000,NaN,14605.000000,10.000000,10.000000,1.650000e+02,0.000000,NaN,...,264.000000,NaN,2611.000000,3.960400,8.196720,11.579920,16.178490,NaN,0.000000,4.106241e+01
25%,0.000000,1.500000e+01,30.960000,NaN,18127.000000,435.000000,445.000000,4.090000e+03,15.000000,NaN,...,799.000000,NaN,4337.000000,7.490640,18.012420,22.001560,23.453100,NaN,6.000000,4.106241e+01
50%,20.000000,1.400000e+02,34.450000,NaN,20520.000000,645.000000,650.000000,5.900000e+03,25.000000,NaN,...,946.000000,NaN,5005.000000,8.743170,21.770330,25.724460,28.301100,NaN,9.000000,4.106241e+01
75%,80.000000,5.500000e+02,39.020000,NaN,23748.000000,1175.000000,1205.000000,9.545000e+03,35.000000,NaN,...,1098.000000,NaN,5891.000000,10.000000,24.724060,30.364040,34.399990,NaN,13.000000,4.106241e+01
max,296795.000000,2.269075e+06,77.920000,NaN,192005.000000,331540.000000,340200.000000,2.859940e+06,11260.000000,NaN,...,2736.000000,NaN,11994.000000,14.136130,31.652660,40.074380,52.621890,NaN,27.000000,4.106241e+01

In [48]:
## Delete columns with all missing values
df_LAD_local_indicators=df_LAD_local_indicators.dropna(axis=1, how ='all')
print(df_LAD_local_indicators.shape)
df_LAD_local_indicators.describe()

(6035, 109)

,OBS_Value_Business,OBS_Value_Employment,Gross Value Added (GVA) per hour worked (£) [GVA per hour],"Gross disposable household income, per head (£) [GDHI per head]",Count of births of new enterprises (control rounded to base 5) [New enterprises],Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises],Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],Total UK public-funded gross regional capital and non-capital expenditure on research and development (£ million) [Goverment R&D],"Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes) [Public transport to employer]",...,Percentage of 5-year olds at 'expected level' in maths early learning goals (%) [Early years maths],Count of 19+ Further Education and Skills Learner Achievements (qualifications) [FE and skills achievements],"Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]","19+ further education and skills participation (per 100,000 population) [FE and skills participation]",Proportion of children living with obesity at reception age (%) [Reception obesity],Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity],"Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]","Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]","Net additions per 1,000 stock [Net additions]",% living in an area that has a devolution deal with a directly elected mayor [Devolution]
count,6035.000000,6.035000e+03,5882.000000,5967.000000,5967.000000,5967.000000,5.967000e+03,5967.000000,51.000000,4760.000000,...,5015.000000,2193.000000,5049.000000,5049.000000,4981.000000,4981.000000,4981.000000,4981.000000,4981.000000,1.700000e+01
mean,459.300751,3.608229e+03,36.429624,22440.886040,3704.074074,3800.868946,3.188997e+04,125.683761,4410.000000,11.840545,...,77.994576,12516.356589,954.390572,5233.552189,8.773504,21.518803,26.285858,29.373295,9.665529,4.106241e+01
std,7353.239746,5.302837e+04,8.382263,11287.635075,28957.566706,29717.774005,2.490954e+05,982.509824,5138.769506,3.925919,...,3.772581,82499.400309,267.594402,1265.251982,1.796656,4.323257,5.751046,7.820262,5.381971,7.324107e-15
min,0.000000,0.000000e+00,23.840000,14605.000000,10.000000,10.000000,1.650000e+02,0.000000,361.000000,3.224680,...,65.800000,20.000000,264.000000,2611.000000,3.960400,8.196720,11.579920,16.178490,0.000000,4.106241e+01
25%,0.000000,1.500000e+01,30.960000,18127.000000,435.000000,445.000000,4.090000e+03,15.000000,361.000000,9.604423,...,75.400000,3240.000000,799.000000,4337.000000,7.490640,18.012420,22.001560,23.453100,6.000000,4.106241e+01
50%,20.000000,1.400000e+02,34.450000,20520.000000,645.000000,650.000000,5.900000e+03,25.000000,1283.000000,11.185227,...,78.200000,4830.000000,946.000000,5005.000000,8.743170,21.770330,25.724460,28.301100,9.000000,4.106241e+01
75%,80.000000,5.500000e+02,39.020000,23748.000000,1175.000000,1205.000000,9.545000e+03,35.000000,11586.000000,13.357344,...,80.500000,6370.000000,1098.000000,5891.000000,10.000000,24.724060,30.364040,34.399990,13.000000,4.106241e+01
max,296795.000000,2.269075e+06,77.920000,192005.000000,331540.000000,340200.000000,2.859940e+06,11260.000000,11586.000000,44.295678,...,87.700000,944960.000000,2736.000000,11994.000000,14.136130,31.652660,40.074380,52.621890,27.000000,4.106241e+01

In [41]:
##I will export the data in CSV and excel format and then can choice which one is better to work with.
df_LAD_local_indicators.to_excel(clean_data / "local_indicators_with_LAD_all_sample.xlsx", sheet_name="_all_local_indicators", index=False)

df_LAD_local_indicators.to_csv(clean_data / "local_indicators_with_LAD_all_sample.csv", index=False)

## When we decide our region --> We need to correct the next code and export again the data

In [ ]:
df_local_indicators_region = df_local_indicators[~df_local_indicators['Area Code'].astype(str).str.startswith(('S', 'W', 'N', 'na','TLN', 'TLM'))]

In [ ]:
df_local_indicators_region.to_excel(clean_data / "local_indicators_region.xlsx", sheet_name="_all_local_indicators", index=False)

df_local_indicators_region.to_csv(clean_data / "local_indicators_region.csv", index=False)