In [1]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\diane\anaconda3\lib\site-packages (19.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install fastparquet

Requirement already satisfied: fastparquet in c:\users\diane\anaconda3\lib\site-packages (2025.12.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.2)
Requirement already satisfied: numpy in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: cramjam>=2.3 in c:\users\diane\anaconda3\lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\users\diane\anaconda3\lib\site-packages (from fastparquet) (2025.3.2)
Requirement already satisfied: packaging in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\diane\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
!pip install fastparquet

Requirement already satisfied: fastparquet in c:\users\diane\anaconda3\lib\site-packages (2025.12.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.2)
Requirement already satisfied: numpy in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: cramjam>=2.3 in c:\users\diane\anaconda3\lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\users\diane\anaconda3\lib\site-packages (from fastparquet) (2025.3.2)
Requirement already satisfied: packaging in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\diane\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)

# LEVEL MACRO

In [47]:
import pandas as pd
from pathlib import Path

raw_data   = Path("G:/Mi unidad/Master_LSE/Git-hub/Economic_Observatory/Data/raw_data")
clean_data = Path("G:/Mi unidad/Master_LSE/Git-hub/Economic_Observatory/Data/cleaning_data")

In [48]:
import pandas as pd

##LAD = Local Authority District: The main administrative divisions in the UK (like councils)
df0_bus = pd.read_parquet(raw_data / "business_counts" / "Business_counts_IS8_LADs.parquet", engine="fastparquet") 
df0_em = pd.read_parquet(raw_data / "employee_counts" / "Employee_counts_IS8_LADs.parquet", engine="fastparquet")

In [49]:
print(df0_bus.shape)
print(df0_em.shape)

(1249600, 9)
(312400, 8)

In [50]:
df0_bus.head(5)

,YEAR,SIZE_BAND,GEOGRAPHY_CODE,GEOGRAPHY_NAME,GEOGRAPHY_TYPE,IS8_SECTOR,FRONTIER_SECTOR,INDUSTRY_CODE,OBS_VALUE
0,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Aerospace manufacturing,303,0
1,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Aerospace manufacturing,3316,0
2,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Agritech,283,0
3,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Automotive manufacturing,29,0
4,2016,large,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Batteries,272,0

In [51]:
df0_em.head(5)

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,GEOGRAPHY_TYPE,IS8_SECTOR,FRONTIER_SECTOR,INDUSTRY_CODE,OBS_VALUE
0,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Aerospace manufacturing,303,0
1,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Aerospace manufacturing,3316,0
2,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Agritech,283,0
3,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Automotive manufacturing,29,300
4,2015,E06000001,Hartlepool,local authorities: district / unitary (as of A...,Advanced manufacturing,Batteries,272,0

In [52]:
print(df0_bus.info())
print(df0_em.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1249600 entries, 0 to 1249599
Data columns (total 9 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   YEAR             1249600 non-null  int16
 1   SIZE_BAND        1249600 non-null  object
 2   GEOGRAPHY_CODE   1249600 non-null  object
 3   GEOGRAPHY_NAME   1249600 non-null  object
 4   GEOGRAPHY_TYPE   1249600 non-null  object
 5   IS8_SECTOR       1249600 non-null  object
 6   FRONTIER_SECTOR  426000 non-null   object
 7   INDUSTRY_CODE    1249600 non-null  object
 8   OBS_VALUE        1249600 non-null  Int64
dtypes: Int64(1), int16(1), object(7)
memory usage: 79.8+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312400 entries, 0 to 312399
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   YEAR             312400 non-null  int16
 1   GEOGRAPHY_CODE   312400 non-null  object
 2   GEOGRAPHY_NAME   312400 non-null  object
 3   GEOGRAPHY_TYPE   312400 non-null  object
 4   IS8_SECTOR       312400 non-null  object
 5   FRONTIER_SECTOR  106500 non-null  object
 6   INDUSTRY_CODE    312400 non-null  object
 7   OBS_VALUE        312400 non-null  Int64
dtypes: Int64(1), int16(1), object(6)
memory usage: 17.6+ MB
None

In [53]:
print(df0_bus.describe())
print(df0_em.describe())

               YEAR     OBS_VALUE
count  1.249600e+06     1249600.0
mean   2.020500e+03     148.40735
std    2.872282e+00  12244.841201
min    2.016000e+03           0.0
25%    2.018000e+03           0.0
50%    2.020500e+03           0.0
75%    2.023000e+03           5.0
max    2.025000e+03     2654770.0
                YEAR      OBS_VALUE
count  312400.000000       312400.0
mean     2019.500000    5255.035515
std         2.872286  276375.011687
min      2015.000000            0.0
25%      2017.000000            0.0
50%      2019.500000           40.0
75%      2022.000000          250.0
max      2024.000000     31477000.0

In [54]:
print(df0_bus['IS8_SECTOR'].unique())
print(df0_em['IS8_SECTOR'].unique())
print(df0_bus['FRONTIER_SECTOR'].unique())
print(df0_em['FRONTIER_SECTOR'].unique())

['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services' 'Total']
['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services' 'Total']
['Aerospace manufacturing' 'Agritech' 'Automotive manufacturing'
 'Batteries' None 'Advertising and marketing' 'Film and TV'
 'Music, peforming, and visual arts' 'Video games'
 'Asset management and wholesale services'
 'Capital markets and retail investment'
 'Insurance and reinsurance markets'
 'Accounting, audit and tax consultancy' 'Legal services'
 'Management consultancy']
['Aerospace manufacturing' 'Agritech' 'Automotive manufacturing'
 'Batteries' None 'Advertising and marketing' 'Film and TV'
 'Music, peforming, and visual arts' 'Video games'
 'Asset management and wholesale services'
 'Capital markets and retail investment'
 'Insurance and reinsurance markets'
 'Accounting, audit and tax consultancy' 'Legal services'
 'Management consultancy']

In [55]:
group_keys = ["YEAR", "GEOGRAPHY_CODE", "GEOGRAPHY_NAME", "IS8_SECTOR", "FRONTIER_SECTOR"]

df0_bus.loc[df0_bus["IS8_SECTOR"] == "Digital and Technology", "FRONTIER_SECTOR"] = "Digital and Technology"
df0_bus.loc[df0_bus["IS8_SECTOR"] == "Defence sector", "FRONTIER_SECTOR"] = "Defence Sector"
df0_bus.loc[df0_bus["IS8_SECTOR"] == "Life Sciences", "FRONTIER_SECTOR"] = "Life Sciences"


df0_em.loc[df0_em["IS8_SECTOR"] == "Digital and Technology", "FRONTIER_SECTOR"] = "Digital and Technology"
df0_em.loc[df0_em["IS8_SECTOR"] == "Defence sector", "FRONTIER_SECTOR"] = "Defence Sector"
df0_em.loc[df0_em["IS8_SECTOR"] == "Life Sciences", "FRONTIER_SECTOR"] = "Life Sciences"


##This groupby is necessary because we have multiple columns in the businees data because is disaggregate by industry sector and size band. For us is interesting at the frontier
## level
df0_bus_grouped = df0_bus.groupby(group_keys, as_index=False)["OBS_VALUE"].sum()
df0_bus_grouped = df0_bus_grouped.rename(columns={"OBS_VALUE": "OBS_Value_Business"})
print(df0_bus_grouped['IS8_SECTOR'].unique())

## Same here, but the employment data is disaggregate by industry sector.
df0_em_grouped = df0_em.groupby(group_keys, as_index=False)["OBS_VALUE"].sum()
df0_em_grouped = df0_em_grouped.rename(columns={"OBS_VALUE": "OBS_Value_Employment"})
print(df0_em_grouped['IS8_SECTOR'].unique())

## Prioritize the business data available and  only we keep those values from employment data that math with business one.
df_micro_data= df0_bus_grouped.merge(
    df0_em_grouped,
    on=group_keys,
    how="inner",  ##First we have left, but I change this for inner to only keep those values that match in both datasets. Then we have a dataset from 2016 to 2024.      
    indicator=True    
)

print(df_micro_data["_merge"].value_counts())

['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services']
['Advanced manufacturing' 'Creative Industries' 'Defence sector'
 'Digital and Technology' 'Financial Services' 'Life Sciences'
 'Professional and Business Services']
_merge
both          54315
left_only         0
right_only        0
Name: count, dtype: int64

In [56]:
#no_match_lef = df_merged[df_merged["_merge"] == "left_only"] ## bygroup at the industry sector level

#print(no_match_lef.shape)
#print(no_match_lef["YEAR"].value_counts())

In [57]:
## Emolyment data - Not merge with business data
#no_match_rig = df_merged[df_merged["_merge"] == "right_only"]
#print(no_match_rig.shape)
#print(no_match_rig["YEAR"].value_counts())

In [58]:
for col in group_keys:  
    df_micro_data[col] = df_micro_data[col].astype("category")

df_micro_data["OBS_Value_Business"] = df_micro_data["OBS_Value_Business"].astype("float32")
df_micro_data["OBS_Value_Employment"] = df_micro_data["OBS_Value_Employment"].astype("float32")
df_micro_data = df_micro_data.drop(columns=["_merge"])
df_micro_data.head()

df_micro_data.to_excel(clean_data / "Micro_data_business_employment.xlsx", sheet_name="data", index=False)

In [59]:
print(df_micro_data['IS8_SECTOR'].unique())

['Advanced manufacturing', 'Creative Industries', 'Defence sector', 'Digital and Technology', 'Financial Services', 'Life Sciences', 'Professional and Business Services']
Categories (7, object): ['Advanced manufacturing', 'Creative Industries', 'Defence sector', 'Digital and Technology', 'Financial Services', 'Life Sciences', 'Professional and Business Services']

País (England, Wales...)
 └── Región (London, North East...)
      └── LAD (Local Authority District) 
           └── MSOA (Middle Layer Super Output Area)  
                └── LSOA (Lower Layer Super Output Area)
                     └── OA (Output Area)

# LEVEL MICRO

In [60]:
df1_bus = pd.read_parquet(raw_data / "business_counts" / "Business_counts_IS8_MSOAs.parquet", engine="fastparquet") 
df1_em = pd.read_parquet(raw_data / "employee_counts" / "Employee_counts_IS8_MSOAs.parquet", engine="fastparquet")


df1_bus.loc[df1_bus["IS8_SECTOR"] == "Digital and Technology", "FRONTIER_SECTOR"] = "Digital and Technology"
df1_bus.loc[df1_bus["IS8_SECTOR"] == "Defence sector", "FRONTIER_SECTOR"] = "Defence Sector"
df1_bus.loc[df1_bus["IS8_SECTOR"] == "Life Sciences", "FRONTIER_SECTOR"] = "Life Sciences"


df1_em.loc[df1_em["IS8_SECTOR"] == "Digital and Technology", "FRONTIER_SECTOR"] = "Digital and Technology"
df1_em.loc[df1_em["IS8_SECTOR"] == "Defence sector", "FRONTIER_SECTOR"] = "Defence Sector"
df1_em.loc[df1_em["IS8_SECTOR"] == "Life Sciences", "FRONTIER_SECTOR"] = "Life Sciences"


keys = ["YEAR","GEOGRAPHY_CODE", "GEOGRAPHY_NAME", "IS8_SECTOR", "FRONTIER_SECTOR"]

df1_bus_grouped = df1_bus.groupby(keys, as_index=False)['OBS_VALUE'].sum()
df1_bus_grouped = df1_bus_grouped.rename(columns={'OBS_VALUE': 'OBS_Value_Business'})

df1_em_grouped = df1_em.groupby(keys, as_index=False)['OBS_VALUE'].sum()
df1_em_grouped = df1_em_grouped.rename(columns={'OBS_VALUE': 'OBS_Value_Employment'})


df_macro_data = df1_bus_grouped.merge(df1_em_grouped, on=keys, how='inner', indicator=True)

print(df_macro_data["_merge"].value_counts())

_merge
both          270181
left_only          0
right_only         0
Name: count, dtype: int64

In [61]:
for col in keys:
    df_macro_data[col] = df_macro_data[col].astype('category')

df_macro_data['OBS_Value_Business']   = df_macro_data['OBS_Value_Business'].astype('float32')
df_macro_data['OBS_Value_Employment'] = df_macro_data['OBS_Value_Employment'].astype('float32')
df_macro_data = df_macro_data.drop(columns=["_merge"])

df_macro_data.head()
df_macro_data.to_excel(clean_data / "Macro_data_business_employment.xlsx", sheet_name="data", index=False)

# MERGE WITH DEMOGRAPHIC DATA

UK
 └── Country (England, Wales, Scotland, NI)
      └── Region (London, North East...)
           └── County / Unitary Authority
                └── Combined Authority   ← agrupa LADs voluntariamente
                     └── LAD            ← tus bases LAD
                          └── MSOA      ← tus bases MSOA (aquí!)
                               └── LSOA
                                    └── OA

In [ ]:
#Combined Authority / City Region: Es una agrupación voluntaria de varios LADs que se unen para gobernar juntos temas como transporte, vivienda y desarrollo 
#económico. Los más famosos son:
    #Greater Manchester Combined Authority  → agrupa 10 LADs
    #West Midlands Combined Authority       → agrupa Birmingham + 6 LADs
    #West Yorkshire Combined Authority      → agrupa Leeds + 4 LADs

import pandas as pd
# Skip first 4 sheets
xls = pd.ExcelFile(raw_data / "local_indicators" / "ONS_local_indicators_package.xlsx")
print(xls.sheet_names)
sheet_names = xls.sheet_names[4:]

['Notes', 'Voluntary TQV', 'Data dictionary', 'Data inclusivity', 'GVA per hour', 'Weekly pay', 'Employment rate', 'Employment rate (NI)', 'Unemployment rate', 'GDHI per head', 'New enterprises', 'Deaths of enterprises', 'Active enterprises', 'High growth enterprises', 'UK exports', 'Inward FDI', 'Outward FDI', 'Goverment R&D', 'Public transport to employer', 'Drive to employer', 'Cycle to employer', 'Broadband availability', '4G area coverage', 'KS2 attainment', 'GCSE by age 19', 'Ofsted', 'Persistent absences', 'Persistent absences FSM', 'Persistent absences CLA', 'Early years comms', 'Early years literacy', 'Early years maths', 'FE and skills achievements', 'Apprenticeship starts', 'Apprenticeship achievements', 'Level 3+ qualifications', 'Level 3+ qualifications (NI)', 'FE and skills participation', 'Female HLE', 'Male HLE', 'Smokers', 'Reception obesity', 'Year 6 obesity', 'Adult obesity', 'Cancer diagnosis', 'Under 75 mortality rate', 'Under 75 mortality rate (NI)', 'Life satisfaction', 'Worthwhile', 'Happiness', 'Anxiety', 'Net additions', 'Homicide', 'Devolution']

In [ ]:
dfs = []

for sheet_name in sheet_names:
    # Read the whole sheet first as raw
    raw_df = pd.read_excel(xls, sheet_name=sheet_name, header=None)
    
    # Find the row where 'Area Code' appears
    area_row_idx = raw_df[raw_df.iloc[:,0].astype(str).str.contains("Area Code", na=False)].index
    if len(area_row_idx) == 0:
        print(f"Skipping sheet '{sheet_name}' because no 'Area Code' found")
        continue
    header_row = area_row_idx[0]
    
    # Now read the sheet again using the correct header
    df = pd.read_excel(xls, sheet_name=sheet_name, header=header_row)
    
    # Drop confidence interval columns if they exist
    ci_cols = [c for c in df.columns if "Lower 95% Confidence Interval" in str(c) or "Upper 95% Confidence Interval" in str(c)]
    df = df.drop(columns=ci_cols)

    # Drop completely empty columns
    df = df.dropna(axis=1, how='all')
    
    # Identify numeric columns (including numbers stored as text)
    numeric_cols = []
    for col in df.columns:
        temp = pd.to_numeric(df[col], errors='coerce')
        if temp.notna().any():
            numeric_cols.append(col)
    
    if not numeric_cols:
        continue  # skip if no numeric column
    
    # Identifier columns
    id_cols = [c for c in df.columns if c not in numeric_cols]

    df_long = df.melt(
        id_vars=id_cols,
        value_vars=numeric_cols,
        var_name='Metric',
        value_name='Metric_Value'
    )

    df_long['Metric_Value'] = pd.to_numeric(df_long['Metric_Value'], errors='coerce')
    df_long['Sheet'] = sheet_name
    dfs.append(df_long)

df_all = pd.concat(dfs, ignore_index=True)

code_cols = [c for c in df_all.columns if 'Code' in c or 'Area' in c]
for col in code_cols:
    df_all[col] = df_all[col].astype('category')

print(df_all.info())
df_all.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26240 entries, 0 to 26239
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Area Code                          26240 non-null  category
 1   ITL Level 1                        54 non-null     object
 2   County or Unitary Authority        6086 non-null   object
 3   Local Authority District           18448 non-null  object
 4   Notes                              963 non-null    object
 5   Metric                             26240 non-null  object
 6   Metric_Value                       25852 non-null  float64
 7   Sheet                              26240 non-null  object
 8   Country                            74 non-null     object
 9   Nation                             196 non-null    object
 10  Region                             650 non-null    object
 11  Combined Authority or City Region  348 non-null    object
 12  ITL Level 2                        120 non-null    object
 13  ITL Level 3                        179 non-null    object
 14  Observation Status                 240 non-null    object
 15  Welsh Health Board                 42 non-null     object
 16  Data accuracy                      4908 non-null   object
 17  Police Force Area                  43 non-null     category
dtypes: category(2), float64(1), object(15)
memory usage: 3.3+ MB
None

In [ ]:
cols = [
    "Area Code",
    "Country",
    "Nation",
    "Region",
    "Combined Authority or City Region",
    "County or Unitary Authority",
    "Local Authority District",
    "Metric",
    "Metric_Value",
    "Notes",
    "Data accuracy",
    "Observation Status",
    "Sheet",
    "ITL Level 1",
    "ITL Level 2",
    "ITL Level 3",
    "Welsh Health Board",
    "Police Force Area"
]

df_all = df_all[cols]
##Long format is appropiate for graphs, but when we want to run regressions, maybe we need to come back to wide format?
df_all.to_excel(clean_data / "local_indicators_Diane.xlsx", sheet_name="_all_local_indicators", index=False)

In [ ]:
# Ensure both are strings
df_all["Area Code"] = df_all["Area Code"].astype(str).str.strip()
df_merged["GEOGRAPHY_CODE"] = df_merged["GEOGRAPHY_CODE"].astype(str).str.strip()
# Codes in df_all (demographic data) that exist in LDA
matched = df_all["Area Code"].isin(df_merged["GEOGRAPHY_CODE"])
print(f"Matched: {matched.sum()} / {len(df_all)} rows")

Matched: 21753 / 26240 rows

In [ ]:
df_grouped = (
    df_all
    .groupby(["Area Code", "Metric"], as_index=False)
    .agg({
        "Metric_Value": "mean" 
    })
)

df_grouped.head()

   Area Code                                             Metric  Metric_Value
0  E06000001  19+ further education and skills participation...   9800.000000
1  E06000001  Age-standardised mortality rate for those aged...     37.852970
2  E06000001  Apprenticeships achieved by adults aged 16+ ba...    601.000000
3  E06000001  Apprenticeships started by adults aged 16+ bas...   1173.000000
4  E06000001  Average travel time in minutes to reach neares...      7.790802

In [ ]:
metrics = df_all["Metric"].unique()
print(f"Total metrics: {len(metrics)}")
print("\n".join(sorted(metrics)))

Total metrics: 50
% living in an area that has a devolution deal with a directly elected mayor
19+ further education and skills participation (per 100,000 population)
Age-standardised mortality rate for those aged under 75 (per 100,000 population)
Apprenticeships achieved by adults aged 16+ based on home address (per 100,000 population)
Apprenticeships started by adults aged 16+ based on home address (per 100,000 population)
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes)
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes)
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes)
Count of 19+ Further Education and Skills Learner Achievements (qualifications)
Count of active enterprises (control rounded to base 5)
Count of births of new enterprises (control rounded to base 5)
Count of deaths of enterprises (control rounded to base 5)
Count of high growth enterprises (control rounded to base 5)
Employment rate, aged 16 to 64 years (%)
Female Healthy Life Expectancy (years)
Gross Value Added (GVA) per hour worked (£)
Gross disposable household income, per head (£)
Gross median weekly pay (£)
Homicide Offences (per million population)
Lower 95% Confidence Interval
Male Healthy Life Expectancy (years)
Mean anxiety yesterday scored 0 (not at all) - 10 (completely)
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely)
Mean happiness yesterday scored 0 (not at all) - 10 (completely)
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely)
Modelled unemployment rate, aged 16 years and over (%)
Net additions per 1,000 stock
Percentage of 4G coverage by at least one mobile network operator (%)
Percentage of 5-year olds at 'expected level' in communication and language early learning goals (%)
Percentage of 5-year olds at 'expected level' in literacy early learning goals (%)
Percentage of 5-year olds at 'expected level' in maths early learning goals (%)
Percentage of adults that currently smoke cigarettes (%)
Percentage of persistent absences (10% or more missed) eligible for free school meals in the past 6 years (%)
Percentage of persistent absences (10% or more missed) for all pupils (%)
Percentage of persistent absences (10% or more missed) for pupils who are looked after continuously for at least 12 months by local authorities (%)
Percentage of premises with gigabit-capable broadband (%)
Percentage of pupils in state-funded schools meeting the expected standard in reading, writing and maths at the end of key stage 2 (%)
Percentage of schools rated good or outstanding by Ofsted (%)
Percentage of young people achieving GCSEs (and equivalent qualifications) in English and maths by age 19 (%)
Proportion of adults living with obesity, aged 18 years and over (%)
Proportion of cancers diagnosed at stages 1 and 2 (%)
Proportion of children living with obesity at Year 6 age (%)
Proportion of children living with obesity at reception age (%)
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%)
Proportion of the population aged 16-64 with NVQ3+ qualification (%)
Total FDI international investment position abroad at end period (£ million)
Total FDI international investment position in the UK at end period (£ million)
Total UK public-funded gross regional capital and non-capital expenditure on research and development (£ million)
Total value of UK exports (£ million)
Upper 95% Confidence Interval

In [ ]:
pd.Series(sorted(df_all["Metric"].unique())).to_excel(
    clean_data / "metrics_list.xlsx", 
    index=False,
    header=["Metric"]
)

xxx

NameError: name 'xxx' is not defined

In [ ]:
df_merged_2022 = df_merged[df_merged["YEAR"] == 2022].copy()

In [ ]:
import pandas as pd

# Ensure codes are strings and stripped
df_grouped["Area Code"] = df_grouped["Area Code"].astype(str).str.strip()
df_merged["GEOGRAPHY_CODE"] = df_merged["GEOGRAPHY_CODE"].astype(str).str.strip()

# --- Step 1: Filter df_merged to 2022 rows ---
df_merged_2022 = df_merged[df_merged["YEAR"] == 2022].copy()

# --- Step 2: Pivot df_grouped to wide format ---
df_metrics_wide = df_grouped.pivot_table(
    index="Area Code",
    columns="Metric",
    values="Metric_Value",
    aggfunc="first"  # or "mean" if duplicates exist
).reset_index()

# Flatten columns if pivot_table created a MultiIndex
df_metrics_wide.columns.name = None

# --- Step 3: Merge 2022 metrics into 2022 rows only ---
df_merged_2022_final = df_merged_2022.merge(
    df_metrics_wide,
    left_on="GEOGRAPHY_CODE",
    right_on="Area Code",
    how="left"
)

# Drop the extra Area Code column from pivot
df_merged_2022_final = df_merged_2022_final.drop(columns=["Area Code"])

# --- Step 4: Optional: combine with other years back ---
df_final = pd.concat([
    df_merged[df_merged["YEAR"] != 2022],
    df_merged_2022_final
], ignore_index=True)

print(df_final.info())
df_final.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51120 entries, 0 to 51119
Data columns (total 57 columns):
 #   Column                                                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                                                               --------------  -----
 0   YEAR                                                                                                                                                 51120 non-null  category
 1   GEOGRAPHY_CODE                                                                                                                                       51120 non-null  object
 2   GEOGRAPHY_NAME                                                                                                                                       51120 non-null  category
 3   IS8_SECTOR                                                                                                                                           51120 non-null  category
 4   FRONTIER_SECTOR                                                                                                                                      51120 non-null  category
 5   OBS_Value_Business                                                                                                                                   51120 non-null  float32
 6   OBS_Value_Employment                                                                                                                                 51120 non-null  float32
 7   % living in an area that has a devolution deal with a directly elected mayor                                                                         16 non-null     float64
 8   19+ further education and skills participation (per 100,000 population)                                                                              4752 non-null   float64
 9   Age-standardised mortality rate for those aged under 75 (per 100,000 population)                                                                     4688 non-null   float64
 10  Apprenticeships achieved by adults aged 16+ based on home address (per 100,000 population)                                                           4736 non-null   float64
 11  Apprenticeships started by adults aged 16+ based on home address (per 100,000 population)                                                            4752 non-null   float64
 12  Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes)                               4480 non-null   float64
 13  Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes)                             4480 non-null   float64
 14  Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes)       4480 non-null   float64
 15  Count of 19+ Further Education and Skills Learner Achievements (qualifications)                                                                      2064 non-null   float64
 16  Count of active enterprises (control rounded to base 5)                                                                                              5616 non-null   float64
 17  Count of births of new enterprises (control rounded to base 5)                                                                                       5616 non-null   float64
 18  Count of deaths of enterprises (control rounded to base 5)                                                                                           5616 non-null   float64
 19  Count of high growth enterprises (control rounded to base 5)                                                                                         5616 non-null   float64
 20  Employment rate, aged 16 to 64 years (%)                                                                                                             5584 non-null   float64
 21  Female Healthy Life Expectancy (years)                                                                                                               2928 non-null   float64
 22  Gross Value Added (GVA) per hour worked (£)                                                                                                          5536 non-null   float64
 23  Gross disposable household income, per head (£)                                                                                                      5616 non-null   float64
 24  Gross median weekly pay (£)                                                                                                                          5648 non-null   float64
 25  Homicide Offences (per million population)                                                                                                           48 non-null     float64
 26  Lower 95% Confidence Interval                                                                                                                        5680 non-null   float64
 27  Male Healthy Life Expectancy (years)                                                                                                                 2928 non-null   float64
 28  Mean anxiety yesterday scored 0 (not at all) - 10 (completely)                                                                                       5424 non-null   float64
 29  Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely)                                                              5424 non-null   float64
 30  Mean happiness yesterday scored 0 (not at all) - 10 (completely)                                                                                     5424 non-null   float64
 31  Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely)                                                                    5424 non-null   float64
 32  Modelled unemployment rate, aged 16 years and over (%)                                                                                               5344 non-null   float64
 33  Net additions per 1,000 stock                                                                                                                        4688 non-null   float64
 34  Percentage of 4G coverage by at least one mobile network operator (%)                                                                                5536 non-null   float64
 35  Percentage of 5-year olds at 'expected level' in communication and language early learning goals (%)                                                 4720 non-null   float64
 36  Percentage of 5-year olds at 'expected level' in literacy early learning goals (%)                                                                   4720 non-null   float64
 37  Percentage of 5-year olds at 'expected level' in maths early learning goals (%)                                                                      4720 non-null   float64
 38  Percentage of adults that currently smoke cigarettes (%)                                                                                             5568 non-null   float64
 39  Percentage of persistent absences (10% or more missed) eligible for free school meals in the past 6 years (%)                                        2048 non-null   float64
 40  Percentage of persistent absences (10% or more missed) for all pupils (%)                                                                            2048 non-null   float64
 41  Percentage of persistent absences (10% or more missed) for pupils who are looked after continuously for at least 12 months by local authorities (%)  2032 non-null   float64
 42  Percentage of premises with gigabit-capable broadband (%)                                                                                            5536 non-null   float64
 43  Percentage of pupils in state-funded schools meeting the expected standard in reading, writing and maths at the end of key stage 2 (%)               2128 non-null   float64
 44  Percentage of schools rated good or outstanding by Ofsted (%)                                                                                        2096 non-null   float64
 45  Percentage of young people achieving GCSEs (and equivalent qualifications) in English and maths by age 19 (%)                                        4672 non-null   float64
 46  Proportion of adults living with obesity, aged 18 years and over (%)                                                                                 4688 non-null   float64
 47  Proportion of cancers diagnosed at stages 1 and 2 (%)                                                                                                4224 non-null   float64
 48  Proportion of children living with obesity at Year 6 age (%)                                                                                         4688 non-null   float64
 49  Proportion of children living with obesity at reception age (%)                                                                                      4688 non-null   float64
 50  Proportion of the population aged 16 to 64 with NVQ3+ qualification (%)                                                                              5584 non-null   float64
 51  Proportion of the population aged 16-64 with NVQ3+ qualification (%)                                                                                 0 non-null      float64
 52  Total FDI international investment position abroad at end period (£ million)                                                                         0 non-null      float64
 53  Total FDI international investment position in the UK at end period (£ million)                                                                      0 non-null      float64
 54  Total UK public-funded gross regional capital and non-capital expenditure on research and development (£ million)                                    48 non-null     float64
 55  Total value of UK exports (£ million)                                                                                                                16 non-null     float64
 56  Upper 95% Confidence Interval                                                                                                                        5680 non-null   float64
dtypes: category(4), float32(2), float64(50), object(1)
memory usage: 20.5+ MB
None

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment,% living in an area that has a devolution deal with a directly elected mayor,"19+ further education and skills participation (per 100,000 population)","Age-standardised mortality rate for those aged under 75 (per 100,000 population)",...,Proportion of cancers diagnosed at stages 1 and 2 (%),Proportion of children living with obesity at Year 6 age (%),Proportion of children living with obesity at reception age (%),Proportion of the population aged 16 to 64 with NVQ3+ qualification (%),Proportion of the population aged 16-64 with NVQ3+ qualification (%),Total FDI international investment position abroad at end period (£ million),Total FDI international investment position in the UK at end period (£ million),Total UK public-funded gross regional capital and non-capital expenditure on research and development (£ million),Total value of UK exports (£ million),Upper 95% Confidence Interval
0,2016,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016,E06000001,Hartlepool,Advanced manufacturing,Automotive manufacturing,0.0,300.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016,E06000001,Hartlepool,Advanced manufacturing,Batteries,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,50.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_final.to_csv(clean_data /  "IS8_Business_Employment_Demography.csv") #Industry data on macroregion level + Demographic infos
df_merged_msoa.to_csv(clean_data / "MSOA_Business_Employment.csv") #Industry data on microregion level (we do not receive data on that granularity)

#Remember the demographic data is from 2022 only. So, the rest is missing value.