## Analysis process - Dianela

In [65]:
%pip install fastparquet

Requirement already satisfied: fastparquet in c:\users\diane\appdata\roaming\python\python313\site-packages (2025.12.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.2)
Requirement already satisfied: numpy in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: cramjam>=2.3 in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (2026.2.0)
Requirement already satisfied: packaging in c:\users\diane\appdata\roaming\python\python313\site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\diane\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\diane\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
from pathlib import Path

root = next(p for p in Path.cwd().parents if (p / "config.yml").exists())

panel = pd.read_parquet(
    root / "data/processed_data/analysis_panel.parquet", engine='fastparquet'
)
print(panel.shape)
print(panel.dtypes)
panel.head(20)

(17150, 57)
YEAR                               int16
GEOGRAPHY_CODE                  category
GEOGRAPHY_NAME                  category
IS8_SECTOR                      category
EMPLOYEES                        float32
BUSINESSES                       float32
gva_per_hour                     float64
weekly_pay                       float64
employment_rate                  float64
unemployment_rate                float64
gdhi_per_head                    float64
new_enterprises                  float64
deaths_of_enterprises            float64
active_enterprises               float64
high_growth_enterprises          float64
public_transport_to_employer     float64
drive_to_employer                float64
cycle_to_employer                float64
broadband_availability           float64
4g_area_coverage                 float64
ks2_attainment                   float64
gcse_by_age_19                   float64
ofsted                           float64
persistent_absences              float64
persistent_absences_fsm          float64
persistent_absences_cla          float64
early_years_comms                float64
early_years_literacy             float64
early_years_maths                float64
fe_and_skills_achievements       float64
apprenticeship_starts            float64
apprenticeship_achievements      float64
level_3+_qualifications          float64
fe_and_skills_participation      float64
female_hle                       float64
male_hle                         float64
smokers                          float64
reception_obesity                float64
year_6_obesity                   float64
adult_obesity                    float64
cancer_diagnosis                 float64
under_75_mortality_rate          float64
life_satisfaction                float64
worthwhile                       float64
happiness                        float64
anxiety                          float64
net_additions                    float64
lq_bus                           float64
emp_share                        float64
lq_emp                           float64
growth_emp                       float64
cagr_emp                         float64
growth_bus                       float64
cagr_bus                         float64
related_variety                  float64
size_large_share                 float64
size_micro_share                 float64
dtype: object

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,EMPLOYEES,BUSINESSES,gva_per_hour,weekly_pay,employment_rate,unemployment_rate,...,lq_bus,emp_share,lq_emp,growth_emp,cagr_emp,growth_bus,cagr_bus,related_variety,size_large_share,size_micro_share
0,2016,E06000001,Hartlepool,Advanced Manufacturing,1470.0,25.0,29.84,521.2,69.7,4.6,...,0.840582,0.048197,1.661003,0.010204,0.001693,-0.200000,-0.036508,1.332179,0.000000,1.000000
1,2016,E06000001,Hartlepool,Creative Industries,450.0,110.0,29.84,521.2,69.7,4.6,...,0.355425,0.014754,0.297588,0.744444,0.097176,-0.090909,-0.015760,2.200516,0.000000,1.000000
2,2016,E06000001,Hartlepool,Defence,0.0,0.0,29.84,521.2,69.7,4.6,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
3,2016,E06000001,Hartlepool,Digital and Technologies,1510.0,440.0,29.84,521.2,69.7,4.6,...,1.362619,0.049508,0.701351,-0.076159,-0.013116,-0.352273,-0.069823,1.072313,0.000000,1.000000
4,2016,E06000001,Hartlepool,Financial Services,285.0,40.0,29.84,521.2,69.7,4.6,...,0.383770,0.009344,0.157782,-0.070175,-0.012053,0.375000,0.054509,1.213008,0.000000,0.750000
5,2016,E06000001,Hartlepool,Life Sciences,40.0,0.0,29.84,521.2,69.7,4.6,...,0.000000,0.001311,0.456144,0.000000,0.000000,NaN,NaN,0.000000,NaN,NaN
6,2016,E06000001,Hartlepool,Professional and Business Services,2630.0,870.0,29.84,521.2,69.7,4.6,...,0.991174,0.086230,0.483176,-0.019011,-0.003194,-0.264368,-0.049884,1.830641,0.000000,0.965517
7,2016,E06000002,Middlesbrough,Advanced Manufacturing,620.0,25.0,29.50,481.9,68.8,5.1,...,0.587201,0.010622,0.366062,0.153226,0.024045,0.400000,0.057681,1.332179,0.000000,0.800000
8,2016,E06000002,Middlesbrough,Creative Industries,1320.0,180.0,29.50,481.9,68.8,5.1,...,0.406288,0.022614,0.456128,0.431818,0.061650,0.055556,0.009052,2.328951,0.000000,1.000000
9,2016,E06000002,Middlesbrough,Defence,0.0,0.0,29.50,481.9,68.8,5.1,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
10,2016,E06000002,Middlesbrough,Digital and Technologies,2600.0,565.0,29.50,481.9,68.8,5.1,...,1.222297,0.044543,0.631018,-0.036538,-0.006185,-0.247788,-0.046348,1.376962,0.000000,0.973451
11,2016,E06000002,Middlesbrough,Financial Services,1645.0,115.0,29.50,481.9,68.8,5.1,...,0.770752,0.028182,0.475870,-0.209726,-0.038470,-0.086957,-0.015048,1.481863,0.000000,0.782609
12,2016,E06000002,Middlesbrough,Life Sciences,10.0,0.0,29.50,481.9,68.8,5.1,...,0.000000,0.000171,0.059587,0.000000,0.000000,NaN,NaN,0.000000,NaN,NaN
13,2016,E06000002,Middlesbrough,Professional and Business Services,6925.0,1280.0,29.50,481.9,68.8,5.1,...,1.018702,0.118640,0.664783,0.127798,0.020247,-0.093750,-0.016273,2.055287,0.007812,0.929688
14,2016,E06000003,Redcar and Cleveland,Advanced Manufacturing,1910.0,35.0,28.42,478.1,74.9,3.6,...,0.876607,0.048172,1.660134,-0.476440,-0.102238,0.000000,0.000000,1.277034,0.000000,0.714286
15,2016,E06000003,Redcar and Cleveland,Creative Industries,415.0,130.0,28.42,478.1,74.9,3.6,...,0.312892,0.010467,0.211109,-0.084337,-0.014577,0.115385,0.018367,2.140633,0.000000,1.000000
16,2016,E06000003,Redcar and Cleveland,Defence,0.0,0.0,28.42,478.1,74.9,3.6,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
17,2016,E06000003,Redcar and Cleveland,Digital and Technologies,1865.0,560.0,28.42,478.1,74.9,3.6,...,1.291834,0.047037,0.666337,-0.308311,-0.059587,-0.357143,-0.070993,1.093751,0.000000,0.955357
18,2016,E06000003,Redcar and Cleveland,Financial Services,370.0,65.0,28.42,478.1,74.9,3.6,...,0.464537,0.009332,0.157569,-0.229730,-0.042570,0.000000,0.000000,1.230932,0.000000,0.692308
19,2016,E06000003,Redcar and Cleveland,Life Sciences,50.0,0.0,28.42,478.1,74.9,3.6,...,0.000000,0.001261,0.438600,1.400000,0.157094,NaN,NaN,0.000000,NaN,NaN

In [ ]:
# ─────────────────────────────────────────────
# 2. DROP METADATA COLUMNS
# ─────────────────────────────────────────────
drop_patterns = [
    'Local Authority District', 'Observation Status', 'Data accuracy',
    'Country', 'Nation', 'Total value of UK', 'Total UK',
    '% living in', 'Homicide Offences', '_merge', 'Area Code',
    'County_or_Unitary_Authority',
]
df = df.drop(columns=[c for c in df.columns
                       if any(c.startswith(p) for p in drop_patterns)])

# ─────────────────────────────────────────────
# 3. DEFINE INDICATOR COLUMNS
#    Excludes reverse-causality and no-EEG-mechanism
#    variables per codebook
# ─────────────────────────────────────────────
ID_COLS      = ['YEAR', 'GEOGRAPHY_CODE', 'GEOGRAPHY_NAME', 'IS8_SECTOR']
OUTCOME_COLS = ['OBS_Value_Business', 'OBS_Value_Employment', 'growth_firms', 'growth_emp']

EXCLUDED = [
    # Reverse causality — outcomes of IS8 presence
    'Gross Value Added (GVA) per hour worked (£) [GVA per hour]',
    'Gross median weekly pay (£) [Weekly pay]',
    'Gross disposable household income, per head (£) [GDHI per head]',
    'Employment rate, aged 16 to 64 years (%) [Employment rate]',
    'Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]',
    # Health — no EEG mechanism
    'Percentage of adults that currently smoke cigarettes (%) [Smokers]',
    'Proportion of children living with obesity at reception age (%) [Reception obesity]',
    'Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity]',
    'Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]',
    'Proportion of cancers diagnosed at stages 1 and 2 (%) [Cancer diagnosis]',
    'Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]',
    # Wellbeing — outcomes, not enablers
    'Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]',
    'Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]',
    'Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]',
    'Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]',
    # Early years — 15-20yr lag
    "Percentage of 5-year olds at 'expected level' in communication and language early learning goals (%) [Early years comms]",
    "Percentage of 5-year olds at 'expected level' in literacy early learning goals (%) [Early years literacy]",
    "Percentage of 5-year olds at 'expected level' in maths early learning goals (%) [Early years maths]",
    # Below LAD resolution
    'Percentage of pupils in state-funded schools meeting the expected standard in reading, writing and maths at the end of key stage 2 (%) [KS2 attainment]',
    'Percentage of young people achieving GCSEs (and equivalent qualifications) in English and maths by age 19 (%) [GCSE by age 19]',
    'Percentage of schools rated good or outstanding by Ofsted (%) [Ofsted]',
    'Percentage of persistent absences (10% or more missed) for all pupils (%) [Persistent absences]',
    'Percentage of persistent absences (10% or more missed) eligible for free school meals in the past 6 years (%) [Persistent absences FSM]',
    'Percentage of persistent absences (10% or more missed) for pupils who are looked after continuously for at least 12 months by local authorities (%) [Persistent absences CLA]',
    'Count of 19+ Further Education and Skills Learner Achievements (qualifications) [FE and skills achievements]',
    'Female Healthy Life Expectancy (years) [Female HLE]',
    'Male Healthy Life Expectancy (years) [Male HLE]',
]

INDICATOR_COLS = [c for c in df.columns
                  if c not in ID_COLS + OUTCOME_COLS + EXCLUDED]

# Convert to numeric
for col in INDICATOR_COLS:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print(f"\nIndicators retained ({len(INDICATOR_COLS)}):")
for c in INDICATOR_COLS:
    print(f"  {c}")

# ─────────────────────────────────────────────
# 4. BUILD LAD-LEVEL CONTROLS
#    (indicators repeat across sectors — collapse
#     to one row per LAD by taking the mean)
# ─────────────────────────────────────────────
x_lad = (
    df.groupby('GEOGRAPHY_CODE')[INDICATOR_COLS]
    .mean(numeric_only=True)
    .reset_index()
)

Indicators retained (14):
  Count of births of new enterprises (control rounded to base 5) [New enterprises]
  Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]
  Count of active enterprises (control rounded to base 5) [Active enterprises]
  Count of high growth enterprises (control rounded to base 5) [High growth enterprises]
  Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes) [Public transport to employer]
  Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes) [Drive to employer]
  Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes) [Cycle to employer]
  Percentage of premises with gigabit-capable broadband (%) [Broadband availability]
  Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]
  Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]
  Apprenticeships achieved by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship achievements]
  Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]
  19+ further education and skills participation (per 100,000 population) [FE and skills participation]
  Net additions per 1,000 stock [Net additions]

In [55]:
# ─────────────────────────────────────────────
# 5. IMPUTE MISSING → LAD median
# ─────────────────────────────────────────────
for col in INDICATOR_COLS:
    x_lad[col] = x_lad[col].fillna(x_lad[col].median())

print(f"\nMissing after imputation: {x_lad[INDICATOR_COLS].isnull().sum().sum()}")

Missing after imputation: 0

In [56]:
# ─────────────────────────────────────────────
# 6. PIVOT OUTCOMES TO WIDE
#    growth_firms + growth_emp
#    One row per LAD, one column per IS8 sector
# ─────────────────────────────────────────────
def pivot_outcome(data, outcome_var, prefix):
    wide = (
        data[['GEOGRAPHY_CODE', 'IS8_SECTOR', outcome_var]]
        .pivot_table(index='GEOGRAPHY_CODE', columns='IS8_SECTOR',
                     values=outcome_var, aggfunc='first')
        .reset_index()
    )
    wide.columns.name = None
    wide.columns = (
        ['GEOGRAPHY_CODE'] +
        [prefix + c.replace(' ', '_') for c in wide.columns[1:]]
    )
    return wide

y_firms = pivot_outcome(df, 'growth_firms', 'gfirms_')
y_emp   = pivot_outcome(df, 'growth_emp',   'gemp_')

In [60]:
# ─────────────────────────────────────────────
# 7. MERGE CONTROLS + OUTCOMES
#    Final dataset: 355 rows × (indicators + sectors)
# ─────────────────────────────────────────────
lad_df = x_lad.merge(y_firms, on='GEOGRAPHY_CODE', how='inner')
lad_df = lad_df.merge(y_emp,   on='GEOGRAPHY_CODE', how='inner')
print(f"\nFinal LAD dataset: {lad_df.shape}")

gfirms_cols = [c for c in lad_df.columns if c.startswith('gfirms_')]
gemp_cols   = [c for c in lad_df.columns if c.startswith('gemp_')]
print(f"Business growth columns : {gfirms_cols}")
print(f"Employment growth columns: {gemp_cols}")

# ─────────────────────────────────────────────
# 8. STANDARDISE X
# ─────────────────────────────────────────────
scaler   = StandardScaler()
X_scaled = scaler.fit_transform(lad_df[INDICATOR_COLS].astype(float))

Final LAD dataset: (355, 29)
Business growth columns : ['gfirms_Advanced_manufacturing', 'gfirms_Creative_Industries', 'gfirms_Defence_sector', 'gfirms_Digital_and_Technology', 'gfirms_Financial_Services', 'gfirms_Life_Sciences', 'gfirms_Professional_and_Business_Services']
Employment growth columns: ['gemp_Advanced_manufacturing', 'gemp_Creative_Industries', 'gemp_Defence_sector', 'gemp_Digital_and_Technology', 'gemp_Financial_Services', 'gemp_Life_Sciences', 'gemp_Professional_and_Business_Services']

In [61]:
# ─────────────────────────────────────────────
# 9. LASSO — one model per IS8 sector
# ─────────────────────────────────────────────
# Short labels for display
short_labels = {c: c.split('[')[0].strip()[:55] for c in INDICATOR_COLS}

def run_lasso(X_sc, y_series, sector_name):
    """Fit LassoCV on non-null observations. Return selected vars + R²."""
    mask = y_series.notna()
    n    = mask.sum()
    if n < 30:
        print(f"\n  {sector_name}: skipped (only {n} non-null LADs)")
        return pd.Series(dtype=float), np.nan

    model = LassoCV(cv=10, random_state=42, max_iter=10000).fit(
        X_sc[mask], y_series[mask]
    )
    coefs    = pd.Series(model.coef_, index=INDICATOR_COLS)
    selected = coefs[coefs != 0].sort_values(key=abs, ascending=False)
    r2       = model.score(X_sc[mask], y_series[mask])

    print(f"\n{'─'*60}")
    print(f"SECTOR: {sector_name}")
    print(f"  N LADs      : {n}")
    print(f"  Best alpha  : {model.alpha_:.5f}")
    print(f"  R² (train)  : {r2:.3f}")
    print(f"  Selected {len(selected)} variable(s):")
    if len(selected) == 0:
        print("    (none — all coefficients shrunk to zero)")
    for var, val in selected.items():
        print(f"    {val:+.4f}  {short_labels[var]}")

    return selected, r2

print("\n" + "═"*60)
print("LASSO: BUSINESS COUNT GROWTH (growth_firms) per IS8 sector")
print("═"*60)
results_firms = {}
for col in gfirms_cols:
    sector = col.replace('gfirms_', '').replace('_', ' ')
    sel, r2 = run_lasso(X_scaled, lad_df[col], sector)
    results_firms[sector] = {'selected': sel, 'r2': r2}

print("\n" + "═"*60)
print("LASSO: EMPLOYMENT GROWTH (growth_emp) per IS8 sector")
print("═"*60)
results_emp = {}
for col in gemp_cols:
    sector = col.replace('gemp_', '').replace('_', ' ')
    sel, r2 = run_lasso(X_scaled, lad_df[col], sector)
    results_emp[sector] = {'selected': sel, 'r2': r2}

════════════════════════════════════════════════════════════
LASSO: BUSINESS COUNT GROWTH (growth_firms) per IS8 sector
════════════════════════════════════════════════════════════

────────────────────────────────────────────────────────────
SECTOR: Advanced manufacturing
  N LADs      : 355
  Best alpha  : 0.01885
  R² (train)  : 0.015
  Selected 1 variable(s):
    -0.0098  Percentage of premises with gigabit-capable broadband (

────────────────────────────────────────────────────────────
SECTOR: Creative Industries
  N LADs      : 355
  Best alpha  : 0.00023
  R² (train)  : 0.092
  Selected 11 variable(s):
    +0.0255  Average travel time in minutes to reach nearest large e
    -0.0200  Average travel time in minutes to reach nearest large e
    -0.0120  Apprenticeships started by adults aged 16+ based on hom
    -0.0103  Percentage of premises with gigabit-capable broadband (
    +0.0067  19+ further education and skills participation (per 100
    +0.0067  Apprenticeships achieved by adults aged 16+ based on ho
    -0.0042  Proportion of the population aged 16 to 64 with NVQ3+ q
    -0.0035  Average travel time in minutes to reach nearest large e
    -0.0017  Percentage of 4G coverage by at least one mobile networ
    -0.0008  Net additions per 1,000 stock
    +0.0007  Count of high growth enterprises (control rounded to ba

────────────────────────────────────────────────────────────
SECTOR: Defence sector
  N LADs      : 355
  Best alpha  : 0.01755
  R² (train)  : 0.000
  Selected 0 variable(s):
    (none — all coefficients shrunk to zero)

────────────────────────────────────────────────────────────
SECTOR: Digital and Technology
  N LADs      : 355
  Best alpha  : 0.00230
  R² (train)  : 0.071
  Selected 5 variable(s):
    -0.0107  Percentage of premises with gigabit-capable broadband (
    +0.0036  Percentage of 4G coverage by at least one mobile networ
    -0.0026  Apprenticeships started by adults aged 16+ based on hom
    +0.0024  Average travel time in minutes to reach nearest large e
    +0.0007  19+ further education and skills participation (per 100

────────────────────────────────────────────────────────────
SECTOR: Financial Services
  N LADs      : 355
  Best alpha  : 0.00708
  R² (train)  : 0.030
  Selected 2 variable(s):
    +0.0054  Average travel time in minutes to reach nearest large e
    +0.0039  Apprenticeships started by adults aged 16+ based on hom

────────────────────────────────────────────────────────────
SECTOR: Life Sciences
  N LADs      : 355
  Best alpha  : 0.03022
  R² (train)  : 0.000
  Selected 0 variable(s):
    (none — all coefficients shrunk to zero)

────────────────────────────────────────────────────────────
SECTOR: Professional and Business Services
  N LADs      : 355
  Best alpha  : 0.00278
  R² (train)  : 0.050
  Selected 4 variable(s):
    -0.0063  Percentage of premises with gigabit-capable broadband (
    -0.0051  Proportion of the population aged 16 to 64 with NVQ3+ q
    +0.0038  19+ further education and skills participation (per 100
    +0.0004  Apprenticeships achieved by adults aged 16+ based on ho

════════════════════════════════════════════════════════════
LASSO: EMPLOYMENT GROWTH (growth_emp) per IS8 sector
════════════════════════════════════════════════════════════

────────────────────────────────────────────────────────────
SECTOR: Advanced manufacturing
  N LADs      : 355
  Best alpha  : 0.02458
  R² (train)  : 0.000
  Selected 0 variable(s):
    (none — all coefficients shrunk to zero)

────────────────────────────────────────────────────────────
SECTOR: Creative Industries
  N LADs      : 355
  Best alpha  : 0.02885
  R² (train)  : 0.000
  Selected 0 variable(s):
    (none — all coefficients shrunk to zero)

────────────────────────────────────────────────────────────
SECTOR: Defence sector
  N LADs      : 355
  Best alpha  : 0.03512
  R² (train)  : 0.000
  Selected 0 variable(s):
    (none — all coefficients shrunk to zero)

────────────────────────────────────────────────────────────
SECTOR: Digital and Technology
  N LADs      : 355
  Best alpha  : 0.02025
  R² (train)  : 0.056
  Selected 2 variable(s):
    +0.0211  Proportion of the population aged 16 to 64 with NVQ3+ q
    -0.0128  Average travel time in minutes to reach nearest large e

────────────────────────────────────────────────────────────
SECTOR: Financial Services
  N LADs      : 355
  Best alpha  : 0.03300
  R² (train)  : 0.005
  Selected 1 variable(s):
    +0.0049  Average travel time in minutes to reach nearest large e

────────────────────────────────────────────────────────────
SECTOR: Life Sciences
  N LADs      : 355
  Best alpha  : 0.00864
  R² (train)  : 0.049
  Selected 8 variable(s):
    +0.1328  Proportion of the population aged 16 to 64 with NVQ3+ q
    +0.0616  19+ further education and skills participation (per 100
    -0.0604  Percentage of premises with gigabit-capable broadband (
    -0.0470  Net additions per 1,000 stock
    -0.0358  Average travel time in minutes to reach nearest large e
    -0.0347  Percentage of 4G coverage by at least one mobile networ
    -0.0311  Apprenticeships started by adults aged 16+ based on hom
    -0.0063  Average travel time in minutes to reach nearest large e

────────────────────────────────────────────────────────────
SECTOR: Professional and Business Services
  N LADs      : 355
  Best alpha  : 0.01404
  R² (train)  : 0.037
  Selected 1 variable(s):
    +0.0162  Proportion of the population aged 16 to 64 with NVQ3+ q

In [ ]:
# ─────────────────────────────────────────────
# 10. SUMMARY TABLE
#     How many sectors selected each variable?
# ─────────────────────────────────────────────
def build_summary(results_dict, label):
    rows = []
    for sector, res in results_dict.items():
        if isinstance(res['selected'], pd.Series):
            for var, coef in res['selected'].items():
                rows.append({'Sector': sector, 'Variable': var, 'Coefficient': coef})
    if not rows:
        print(f"\nNo variables selected for {label}.")
        return pd.DataFrame()
    summary = pd.DataFrame(rows)
    freq = (
        summary
        .groupby('Variable')
        .agg(
            N_sectors  = ('Sector',      'count'),
            Mean_coef  = ('Coefficient', 'mean'),
            Sectors    = ('Sector',      lambda x: ', '.join(sorted(x)))
        )
        .sort_values('N_sectors', ascending=False)
        .reset_index()
    )
    freq['Variable_short'] = freq['Variable'].map(short_labels)
    print("\n" + "═"*60)
    print(f"SELECTION FREQUENCY — {label}")
    print("═"*60)
    print(freq[['Variable_short', 'N_sectors', 'Mean_coef', 'Sectors']].to_string(index=False))
    return freq

freq_firms = build_summary(results_firms, "Business Growth (growth_firms)")
freq_emp   = build_summary(results_emp,   "Employment Growth (growth_emp)")

# ─────────────────────────────────────────────
# 11. PLOT — coefficient heatmap
# ─────────────────────────────────────────────
def plot_heatmap(results_dict, freq_df, outcome_label, fname):
    if freq_df.empty:
        return
    all_vars = freq_df['Variable'].tolist()
    sectors  = list(results_dict.keys())
    mat = pd.DataFrame(0.0,
                       index=[short_labels[v] for v in all_vars],
                       columns=sectors)
    for sector, res in results_dict.items():
        if isinstance(res['selected'], pd.Series):
            for var, coef in res['selected'].items():
                if short_labels[var] in mat.index:
                    mat.loc[short_labels[var], sector] = coef

    vmax = np.abs(mat.values).max() or 1
    fig, ax = plt.subplots(figsize=(max(10, len(sectors) * 1.6),
                                    max(4,  len(all_vars) * 0.55 + 1.5)))
    im = ax.imshow(mat.values, aspect='auto', cmap='RdBu_r',
                   vmin=-vmax, vmax=vmax)
    ax.set_xticks(range(len(sectors)))
    ax.set_xticklabels([s.replace(' ', '\n') for s in sectors], fontsize=9)
    ax.set_yticks(range(len(mat.index)))
    ax.set_yticklabels(mat.index, fontsize=9)
    plt.colorbar(im, ax=ax, label='LASSO coefficient (standardised X)')
    ax.set_title(f'LASSO — {outcome_label} by IS8 Sector\n'
                 'Red = positive, Blue = negative, White = not selected',
                 fontsize=10, fontweight='bold', pad=12)
    plt.tight_layout()
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()

plot_heatmap(results_firms, freq_firms,
             'Business Count Growth (growth_firms)', 'lasso_heatmap_growth_firms.png')
plot_heatmap(results_emp,   freq_emp,
             'Employment Growth (growth_emp)',        'lasso_heatmap_growth_emp.png')

print("\n✓ Done.")
print(f"  LADs: {len(lad_df)}  |  Indicators: {len(INDICATOR_COLS)}  |  Models: {len(gfirms_cols) + len(gemp_cols)}")

In [19]:
cols_to_drop = [col for col in analysis_data.columns if 
                col.startswith('Local Authority District') or
                col.startswith('Notes') or
                col.startswith('Data accuracy') or
                col.startswith('Observation Status') or
                col.startswith('Country') or
                col.startswith('Nation') or
                col.startswith('Total value of UK') or               
                col.startswith('Total UK') or 
                col.startswith('% living in') or 
                col.startswith('Homicide Offences')]
# Drop merged variable and pattern-matched columns
analysis_data = analysis_data.drop(columns=['_merge', 'Area Code'] + cols_to_drop)

print(f"Columns dropped: {len(cols_to_drop) + 2}")
print(f"Remaining columns: {analysis_data.shape[1]}")

Columns dropped: 60
Remaining columns: 50

In [20]:
# Columns to exclude from indicators
cols_to_exclude = ['YEAR', 'GEOGRAPHY_CODE', 'GEOGRAPHY_NAME', 
                   'IS8_SECTOR','OBS_Value_Business', 'OBS_Value_Employment',
                   'growth_firms', 'growth_emp']

x = analysis_data.drop(columns=cols_to_exclude)
y = analysis_data[cols_to_exclude]

In [21]:
#With the previous code, I realised that some of the indicators were not numeric, so I will convert them to numeric:
cols_to_convert = [
    'Gross median weekly pay (£) [Weekly pay]',
    'Employment rate, aged 16 to 64 years (%) [Employment rate]',
    'Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]',
    'Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]',
    'Percentage of adults that currently smoke cigarettes (%) [Smokers]',
    'Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]',
    'Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]',
    'Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]',
    'Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]'
]
for col in cols_to_convert:
    x[col] = pd.to_numeric(x[col], errors='coerce')

print(x.dtypes)

County_or_Unitary_Authority                                                                                                                                                       object
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                                                                                       float64
Gross median weekly pay (£) [Weekly pay]                                                                                                                                         float64
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                                                                                       float64
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                                                                                                       float64
Gross disposable household income, per head (£) [GDHI per head]                                                                                                                  float64
Count of births of new enterprises (control rounded to base 5) [New enterprises]                                                                                                 float64
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                                                                                               float64
Count of active enterprises (control rounded to base 5) [Active enterprises]                                                                                                     float64
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                                                                                           float64
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes) [Public transport to employer]    float64
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes) [Drive to employer]                                       float64
Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes) [Cycle to employer]                                     float64
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                                                                                               float64
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                                                                                         float64
Percentage of pupils in state-funded schools meeting the expected standard in reading, writing and maths at the end of key stage 2 (%) [KS2 attainment]                          float64
Percentage of young people achieving GCSEs (and equivalent qualifications) in English and maths by age 19 (%) [GCSE by age 19]                                                    object
Percentage of schools rated good or outstanding by Ofsted (%) [Ofsted]                                                                                                            object
Percentage of persistent absences (10% or more missed) for all pupils (%) [Persistent absences]                                                                                  float64
Percentage of persistent absences (10% or more missed) eligible for free school meals in the past 6 years (%) [Persistent absences FSM]                                          float64
Percentage of persistent absences (10% or more missed) for pupils who are looked after continuously for at least 12 months by local authorities (%) [Persistent absences CLA]     object
Percentage of 5-year olds at 'expected level' in communication and language early learning goals (%) [Early years comms]                                                         float64
Percentage of 5-year olds at 'expected level' in literacy early learning goals (%) [Early years literacy]                                                                        float64
Percentage of 5-year olds at 'expected level' in maths early learning goals (%) [Early years maths]                                                                              float64
Count of 19+ Further Education and Skills Learner Achievements (qualifications) [FE and skills achievements]                                                                     float64
Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]                                                                float64
Apprenticeships achieved by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship achievements]                                                          object
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]                                                                                float64
19+ further education and skills participation (per 100,000 population) [FE and skills participation]                                                                            float64
Female Healthy Life Expectancy (years) [Female HLE]                                                                                                                               object
Male Healthy Life Expectancy (years) [Male HLE]                                                                                                                                   object
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                                                                                               float64
Proportion of children living with obesity at reception age (%) [Reception obesity]                                                                                              float64
Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity]                                                                                                    float64
Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]                                                                                             float64
Proportion of cancers diagnosed at stages 1 and 2 (%) [Cancer diagnosis]                                                                                                          object
Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]                                                                       float64
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]                                                                            float64
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]                                                                             float64
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                                                                                                     float64
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                                                                                         float64
Net additions per 1,000 stock [Net additions]                                                                                                                                    float64
dtype: object

In [22]:
x_controls = x.groupby("County_or_Unitary_Authority").mean(numeric_only=True).reset_index()
x_controls.head(10)

,County_or_Unitary_Authority,Gross Value Added (GVA) per hour worked (£) [GVA per hour],Gross median weekly pay (£) [Weekly pay],"Employment rate, aged 16 to 64 years (%) [Employment rate]","Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]","Gross disposable household income, per head (£) [GDHI per head]",Count of births of new enterprises (control rounded to base 5) [New enterprises],Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises],Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],...,Percentage of adults that currently smoke cigarettes (%) [Smokers],Proportion of children living with obesity at reception age (%) [Reception obesity],Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity],"Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]","Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]",Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction],Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile],Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety],"Net additions per 1,000 stock [Net additions]"
0,Bath and North East Somerset,28.45,564.1,80.2,2.4,23101.0,835.0,945.0,8980.0,50.0,...,11.5,7.44048,17.30205,21.68340,20.12109,7.38,7.66,7.20,3.59,6.0
1,Bedford,32.74,625.3,77.6,4.5,21328.0,965.0,1025.0,8075.0,30.0,...,11.8,8.33333,21.47806,24.02529,29.30756,7.46,7.71,7.59,3.35,18.0
2,Blackburn with Darwen,28.48,496.0,67.9,4.7,15025.0,815.0,855.0,6270.0,35.0,...,19.4,10.35354,24.72406,22.97324,48.34618,7.24,7.80,7.43,3.07,9.0
3,Blackpool,28.32,463.7,71.1,4.2,16717.0,795.0,565.0,4670.0,20.0,...,18.8,11.98630,26.92308,35.62741,52.62189,7.49,7.64,7.31,3.50,3.0
4,"Bournemouth, Christchurch and Poole",34.79,545.9,77.9,NaN,21751.0,1935.0,1935.0,17220.0,75.0,...,10.1,6.90162,18.96104,27.92590,27.00597,7.57,7.73,7.37,3.10,4.0
5,Bracknell Forest,49.02,669.8,80.0,3.0,23748.0,520.0,565.0,5040.0,30.0,...,14.6,7.24638,19.41392,24.98433,26.02915,7.55,7.74,7.67,3.41,8.0
6,Brighton and Hove,39.36,572.3,72.4,4.7,24834.0,2165.0,2200.0,16810.0,55.0,...,12.8,6.80751,17.02586,19.12000,27.78213,7.39,7.67,7.03,3.31,7.0
7,"Bristol, City of",33.63,591.2,76.7,3.5,21084.0,2540.0,2380.0,20545.0,115.0,...,14.8,8.91089,21.59827,24.82034,29.88635,7.31,7.33,7.20,3.44,8.0
8,Buckinghamshire,38.65,640.5,80.5,NaN,28440.0,3075.0,3620.0,33810.0,100.0,...,10.6,7.11150,17.12219,20.51092,21.06846,7.63,7.84,7.47,3.26,16.0
9,Central Bedfordshire,34.00,659.8,82.8,NaN,22509.0,1315.0,1490.0,13060.0,35.0,...,15.0,6.24093,17.98246,30.36404,23.27008,7.32,7.75,7.28,3.21,18.0

In [23]:
y.head(25)

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,OBS_Value_Business,OBS_Value_Employment,growth_firms,growth_emp
0,2022,E06000001,Hartlepool,Advanced manufacturing,20.0,1485.0,-0.213574,0.295338
1,2022,E06000001,Hartlepool,Creative Industries,100.0,785.0,-0.094410,0.032323
2,2022,E06000001,Hartlepool,Defence sector,0.0,0.0,0.000000,0.000000
3,2022,E06000001,Hartlepool,Digital and Technology,285.0,1395.0,-0.146126,-0.055725
4,2022,E06000001,Hartlepool,Financial Services,55.0,265.0,0.000000,0.255620
5,2022,E06000001,Hartlepool,Life Sciences,0.0,40.0,0.000000,0.000000
6,2022,E06000001,Hartlepool,Professional and Business Services,640.0,2580.0,-0.103643,-0.264062
7,2022,E06000002,Middlesbrough,Advanced manufacturing,35.0,715.0,0.325423,0.555087
8,2022,E06000002,Middlesbrough,Creative Industries,190.0,1890.0,-0.051031,0.160251
9,2022,E06000002,Middlesbrough,Defence sector,0.0,0.0,0.000000,0.000000
10,2022,E06000002,Middlesbrough,Digital and Technology,425.0,2505.0,-0.131769,-0.027550
11,2022,E06000002,Middlesbrough,Financial Services,105.0,1300.0,0.000000,-0.210614
12,2022,E06000002,Middlesbrough,Life Sciences,0.0,10.0,0.000000,0.000000
13,2022,E06000002,Middlesbrough,Professional and Business Services,1160.0,7810.0,-0.070657,-0.045670
14,2022,E06000003,Redcar and Cleveland,Advanced manufacturing,35.0,1000.0,-0.130053,-0.135278
15,2022,E06000003,Redcar and Cleveland,Creative Industries,145.0,380.0,0.187816,0.096361
16,2022,E06000003,Redcar and Cleveland,Defence sector,0.0,0.0,0.000000,0.000000
17,2022,E06000003,Redcar and Cleveland,Digital and Technology,360.0,1290.0,-0.053922,-0.252003
18,2022,E06000003,Redcar and Cleveland,Financial Services,65.0,285.0,0.000000,0.150661
19,2022,E06000003,Redcar and Cleveland,Life Sciences,0.0,120.0,0.000000,0.000000
20,2022,E06000003,Redcar and Cleveland,Professional and Business Services,875.0,4485.0,-0.060893,-0.347651
21,2022,E06000004,Stockton-on-Tees,Advanced manufacturing,85.0,4630.0,0.123614,-0.110293
22,2022,E06000004,Stockton-on-Tees,Creative Industries,340.0,1590.0,-0.043048,-0.156751
23,2022,E06000004,Stockton-on-Tees,Defence sector,0.0,0.0,0.000000,0.000000
24,2022,E06000004,Stockton-on-Tees,Digital and Technology,825.0,6025.0,-0.092444,-0.252383

In [24]:
y_pivot = y.pivot_table(
    index=['YEAR', 'GEOGRAPHY_CODE', 'GEOGRAPHY_NAME'],
    columns='IS8_SECTOR',
    values=['OBS_Value_Business', 'OBS_Value_Employment', 'growth_firms', 'growth_emp'],
    aggfunc='first'
).reset_index()

# Flatten MultiIndex columns
y_pivot.columns = [
    '_'.join(col).strip('_') if isinstance(col, tuple) else col
    for col in y_pivot.columns
]
y_pivot.columns.name = None

# Rename prefixes to shorter versions
y_pivot.columns = (y_pivot.columns
    .str.replace('OBS_Value_Business_', 'count_bus_')
    .str.replace('OBS_Value_Employment_', 'count_em_')
    .str.replace('growth_firms_', 'gfirms_')
    .str.replace('growth_emp_', 'gemp_')
    .str.replace(' ', '_')
)
print(y_pivot.shape)
y_pivot.head()

(355, 31)

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,count_bus_Advanced_manufacturing,count_bus_Creative_Industries,count_bus_Defence_sector,count_bus_Digital_and_Technology,count_bus_Financial_Services,count_bus_Life_Sciences,count_bus_Professional_and_Business_Services,...,gemp_Financial_Services,gemp_Life_Sciences,gemp_Professional_and_Business_Services,gfirms_Advanced_manufacturing,gfirms_Creative_Industries,gfirms_Defence_sector,gfirms_Digital_and_Technology,gfirms_Financial_Services,gfirms_Life_Sciences,gfirms_Professional_and_Business_Services
0,2022,E06000001,Hartlepool,20.0,100.0,0.0,285.0,55.0,0.0,640.0,...,0.255620,0.000000,-0.264062,-0.213574,-0.094410,0.0,-0.146126,0.000000,0.0,-0.103643
1,2022,E06000002,Middlesbrough,35.0,190.0,0.0,425.0,105.0,0.0,1160.0,...,-0.210614,0.000000,-0.045670,0.325423,-0.051031,0.0,-0.131769,0.000000,0.0,-0.070657
2,2022,E06000003,Redcar and Cleveland,35.0,145.0,0.0,360.0,65.0,0.0,875.0,...,0.150661,0.000000,-0.347651,-0.130053,0.187816,0.0,-0.053922,0.000000,0.0,-0.060893
3,2022,E06000004,Stockton-on-Tees,85.0,340.0,0.0,825.0,210.0,5.0,1990.0,...,-0.640111,-0.055263,-0.261752,0.123614,-0.043048,0.0,-0.092444,0.000000,0.0,-0.049006
4,2022,E06000005,Darlington,30.0,210.0,0.0,310.0,135.0,0.0,1005.0,...,0.206492,0.000000,-0.006210,0.000000,-0.090559,0.0,-0.120994,-0.036105,0.0,0.050979

In [28]:
fd_area_code = y_pivot.merge(
    x_controls,
    left_on='GEOGRAPHY_NAME',
    right_on='County_or_Unitary_Authority',
    how='left'
).drop(columns='County_or_Unitary_Authority')

print(fd_area_code.shape)
fd_area_code.head(50)

(355, 65)

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,count_bus_Advanced_manufacturing,count_bus_Creative_Industries,count_bus_Defence_sector,count_bus_Digital_and_Technology,count_bus_Financial_Services,count_bus_Life_Sciences,count_bus_Professional_and_Business_Services,...,Percentage of adults that currently smoke cigarettes (%) [Smokers],Proportion of children living with obesity at reception age (%) [Reception obesity],Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity],"Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]","Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]",Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction],Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile],Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety],"Net additions per 1,000 stock [Net additions]"
0,2022,E06000001,Hartlepool,20.0,100.0,0.0,285.0,55.0,0.0,640.0,...,14.3,12.68293,27.46781,35.35587,37.85297,7.29,7.75,7.57,3.48,11.0
1,2022,E06000002,Middlesbrough,35.0,190.0,0.0,425.0,105.0,0.0,1160.0,...,16.5,12.84153,28.53470,35.29352,40.03257,7.35,7.64,7.05,3.07,9.0
2,2022,E06000003,Redcar and Cleveland,35.0,145.0,0.0,360.0,65.0,0.0,875.0,...,13.7,9.44882,24.67949,34.80189,34.35631,7.25,7.67,7.49,3.25,7.0
3,2022,E06000004,Stockton-on-Tees,85.0,340.0,0.0,825.0,210.0,5.0,1990.0,...,13.2,9.71564,26.26263,32.84926,28.35783,7.33,7.62,7.29,3.23,7.0
4,2022,E06000005,Darlington,30.0,210.0,0.0,310.0,135.0,0.0,1005.0,...,11.5,11.93416,24.20635,29.99722,30.46435,7.32,7.63,7.17,3.38,10.0
5,2022,E06000006,Halton,85.0,185.0,0.0,420.0,110.0,15.0,1030.0,...,13.3,11.61049,28.00000,35.98169,42.19316,7.49,7.79,7.45,3.35,6.0
6,2022,E06000007,Warrington,90.0,740.0,0.0,1510.0,275.0,5.0,3895.0,...,9.9,9.06921,22.15686,29.54306,35.18737,7.45,7.69,7.32,3.18,16.0
7,2022,E06000008,Blackburn with Darwen,90.0,245.0,0.0,330.0,240.0,10.0,1355.0,...,19.4,10.35354,24.72406,22.97324,48.34618,7.24,7.80,7.43,3.07,9.0
8,2022,E06000009,Blackpool,25.0,245.0,0.0,270.0,135.0,5.0,685.0,...,18.8,11.98630,26.92308,35.62741,52.62189,7.49,7.64,7.31,3.50,3.0
9,2022,E06000010,"Kingston upon Hull, City of",170.0,340.0,0.0,430.0,230.0,15.0,1430.0,...,18.9,11.54472,26.75439,39.37604,48.33016,7.38,7.73,7.32,3.51,5.0
10,2022,E06000011,East Riding of Yorkshire,200.0,850.0,5.0,1010.0,405.0,10.0,3280.0,...,10.2,9.09091,21.36752,27.77749,26.93487,7.40,7.69,7.30,3.26,11.0
11,2022,E06000012,North East Lincolnshire,70.0,170.0,0.0,315.0,110.0,0.0,1025.0,...,21.8,11.64179,24.35897,34.66712,40.59289,7.71,8.02,7.82,2.94,6.0
12,2022,E06000013,North Lincolnshire,70.0,200.0,0.0,335.0,155.0,0.0,1140.0,...,15.4,10.00000,22.25064,37.05170,37.51008,7.66,7.94,7.55,2.98,7.0
13,2022,E06000014,York,60.0,785.0,0.0,780.0,275.0,15.0,2465.0,...,8.7,7.84314,18.73278,18.55740,27.46663,7.57,7.68,7.45,3.45,5.0
14,2022,E06000015,Derby,100.0,655.0,0.0,900.0,315.0,10.0,2265.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2022,E06000016,Leicester,125.0,930.0,0.0,980.0,1350.0,5.0,2920.0,...,13.1,9.40722,24.97262,24.48076,45.09029,7.36,7.59,7.24,3.21,12.0
16,2022,E06000017,Rutland,15.0,170.0,0.0,155.0,50.0,0.0,650.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2022,E06000018,Nottingham,95.0,895.0,0.0,965.0,800.0,25.0,2930.0,...,21.2,11.12760,29.00662,30.32567,49.00583,7.24,7.49,7.24,3.45,14.0
18,2022,E06000019,"Herefordshire, County of",125.0,775.0,0.0,735.0,210.0,10.0,2250.0,...,12.2,8.05970,21.61383,29.32307,27.96138,7.64,7.83,7.64,2.93,7.0
19,2022,E06000020,Telford and Wrekin,150.0,445.0,0.0,610.0,150.0,5.0,1365.0,...,16.7,11.24402,25.27473,32.43691,36.78850,7.49,7.83,7.52,2.81,22.0
20,2022,E06000021,Stoke-on-Trent,130.0,330.0,0.0,455.0,220.0,10.0,1225.0,...,16.3,12.00717,29.87421,33.98047,44.12523,7.16,7.59,7.32,3.39,4.0
21,2022,E06000022,Bath and North East Somerset,65.0,1310.0,0.0,1060.0,300.0,20.0,3270.0,...,11.5,7.44048,17.30205,21.68340,20.12109,7.38,7.66,7.20,3.59,6.0
22,2022,E06000023,"Bristol, City of",190.0,3370.0,0.0,2735.0,1005.0,45.0,7025.0,...,14.8,8.91089,21.59827,24.82034,29.88635,7.31,7.33,7.20,3.44,8.0
23,2022,E06000024,North Somerset,80.0,950.0,0.0,990.0,370.0,5.0,2740.0,...,10.4,7.38095,17.67241,22.98933,24.43116,7.62,7.89,7.60,2.89,10.0
24,2022,E06000025,South Gloucestershire,145.0,1005.0,0.0,1415.0,400.0,5.0,3135.0,...,12.2,6.47709,18.71166,21.91625,20.82167,7.65,7.83,7.36,3.14,14.0
25,2022,E06000026,Plymouth,50.0,465.0,0.0,495.0,200.0,0.0,1625.0,...,14.7,9.72516,20.00000,33.55532,32.08919,7.45,7.72,7.71,3.23,3.0
26,2022,E06000027,Torbay,35.0,265.0,0.0,275.0,125.0,5.0,895.0,...,18.4,9.24370,21.11111,30.47454,29.01015,7.42,7.90,7.39,3.31,4.0
27,2022,E06000030,Swindon,70.0,810.0,0.0,1020.0,275.0,5.0,2215.0,...,9.5,8.82957,22.32143,29.66910,30.30657,7.43,7.71,7.43,3.22,10.0
28,2022,E06000031,Peterborough,85.0,560.0,0.0,715.0,295.0,5.0,1920.0,...,12.2,9.71223,25.16667,32.15236,34.56339,7.25,7.50,7.14,3.61,9.0
29,2022,E06000032,Luton,120.0,610.0,0.0,760.0,220.0,10.0,1980.0,...,21.1,9.34256,28.19315,27.30573,37.44936,7.30,7.95,7.64,2.64,14.0
30,2022,E06000033,Southend-on-Sea,50.0,765.0,0.0,670.0,305.0,15.0,2150.0,...,14.0,8.13648,21.77033,33.47711,32.29461,7.36,7.77,7.31,3.24,4.0
31,2022,E06000034,Thurrock,40.0,400.0,0.0,520.0,120.0,0.0,1455.0,...,16.7,10.92784,25.96349,28.18842,32.57315,7.64,7.81,7.51,3.35,3.0
32,2022,E06000035,Medway,90.0,685.0,0.0,840.0,230.0,5.0,2305.0,...,8.9,10.00000,23.12139,37.19724,33.21610,7.29,7.80,7.29,3.29,8.0
33,2022,E06000036,Bracknell Forest,40.0,820.0,0.0,820.0,190.0,10.0,1665.0,...,14.6,7.24638,19.41392,24.98433,26.02915,7.55,7.74,7.67,3.41,8.0
34,2022,E06000037,West Berkshire,100.0,1205.0,0.0,1425.0,300.0,20.0,3155.0,...,11.3,6.79612,17.66467,24.51517,21.38680,7.50,7.65,7.44,3.11,9.0
35,2022,E06000038,Reading,50.0,1315.0,0.0,1585.0,325.0,10.0,2395.0,...,14.4,9.39948,23.78378,33.48682,33.21870,7.43,7.75,7.42,3.22,12.0
36,2022,E06000039,Slough,50.0,1100.0,0.0,1260.0,170.0,10.0,1760.0,...,15.2,10.35294,27.37069,23.84362,44.61835,7.25,7.64,7.40,3.28,6.0
37,2022,E06000040,Windsor and Maidenhead,70.0,1685.0,0.0,1565.0,355.0,25.0,4330.0,...,8.6,6.59341,18.83117,18.92948,21.20473,7.59,7.70,7.49,3.35,5.0
38,2022,E06000041,Wokingham,70.0,1935.0,0.0,2215.0,265.0,20.0,3610.0,...,4.6,4.89691,14.44444,22.38780,20.02442,7.57,7.73,7.42,3.11,12.0
39,2022,E06000042,Milton Keynes,150.0,2125.0,0.0,2450.0,545.0,15.0,4400.0,...,13.8,9.53678,23.51454,25.80772,25.66095,7.51,7.70,7.40,3.80,24.0
40,2022,E06000043,Brighton and Hove,95.0,3345.0,0.0,2105.0,370.0,25.0,5110.0,...,12.8,6.80751,17.02586,19.12000,27.78213,7.39,7.67,7.03,3.31,7.0
41,2022,E06000044,Portsmouth,85.0,535.0,5.0,595.0,165.0,5.0,1590.0,...,14.7,10.66351,25.73363,26.47421,33.00659,7.38,7.74,7.37,3.38,0.0
42,2022,E06000045,Southampton,115.0,595.0,0.0,690.0,250.0,10.0,2040.0,...,13.2,9.47776,26.18182,24.90351,35.28392,7.23,7.54,7.07,3.81,3.0
43,2022,E06000046,Isle of Wight,110.0,390.0,0.0,360.0,115.0,5.0,1070.0,...,9.5,9.41704,21.67300,21.49244,23.75621,7.42,7.68,7.53,3.19,5.0
44,2022,E06000047,County Durham,185.0,715.0,0.0,1040.0,385.0,10.0,3175.0,...,15.4,11.81818,25.62724,34.20071,36.64737,7.56,7.63,7.37,3.13,6.0
45,2022,E06000049,Cheshire East,250.0,1985.0,0.0,2200.0,845.0,55.0,7370.0,...,9.4,9.19395,18.86121,21.09539,28.16624,7.65,7.82,7.56,3.27,12.0
46,2022,E06000050,Cheshire West and Chester,175.0,1230.0,0.0,1440.0,535.0,20.0,5025.0,...,8.9,8.57143,19.83356,27.47997,29.11583,7.44,7.66,7.29,3.09,8.0
47,2022,E06000051,Shropshire,160.0,895.0,0.0,1050.0,395.0,10.0,3685.0,...,10.0,8.59375,17.60436,31.96290,27.32109,7.75,8.07,7.66,2.70,10.0
48,2022,E06000052,Cornwall,265.0,1655.0,0.0,1510.0,595.0,20.0,4845.0,...,10.3,NaN,NaN,26.65514,NaN,7.53,7.70,7.51,2.89,9.0
49,2022,E06000053,Isles of Scilly,0.0,0.0,0.0,0.0,0.0,0.0,15.0,...,NaN,NaN,NaN,22.79511,NaN,NaN,NaN,NaN,NaN,2.0

In [ ]:
threshold = 0.01  # drop columns with more than 1% missing
missing_pct = fd_area_code.isnull().mean()  # gives proportion (0 to 1)
cols_to_keep = missing_pct[missing_pct < threshold].index.tolist()
cols_to_drop = missing_pct[missing_pct >= threshold].index.tolist()

print(f"Columns kept:    {len(cols_to_keep)}")
print(f"Columns dropped: {len(cols_to_drop)}")
print(f"\nDropped columns:\n{cols_to_drop}")

# Apply
X_clean = fd_area_code[cols_to_keep]

X_clean.head()

Columns kept:    31
Columns dropped: 34

Dropped columns:
['Gross Value Added (GVA) per hour worked (£) [GVA per hour]', 'Gross median weekly pay (£) [Weekly pay]', 'Employment rate, aged 16 to 64 years (%) [Employment rate]', 'Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]', 'Gross disposable household income, per head (£) [GDHI per head]', 'Count of births of new enterprises (control rounded to base 5) [New enterprises]', 'Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]', 'Count of active enterprises (control rounded to base 5) [Active enterprises]', 'Count of high growth enterprises (control rounded to base 5) [High growth enterprises]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by public transport or walking (minutes) [Public transport to employer]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by car (minutes) [Drive to employer]', 'Average travel time in minutes to reach nearest large employment centre (500 to 4999 jobs available), by cycle (minutes) [Cycle to employer]', 'Percentage of premises with gigabit-capable broadband (%) [Broadband availability]', 'Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]', 'Percentage of pupils in state-funded schools meeting the expected standard in reading, writing and maths at the end of key stage 2 (%) [KS2 attainment]', 'Percentage of persistent absences (10% or more missed) for all pupils (%) [Persistent absences]', 'Percentage of persistent absences (10% or more missed) eligible for free school meals in the past 6 years (%) [Persistent absences FSM]', "Percentage of 5-year olds at 'expected level' in communication and language early learning goals (%) [Early years comms]", "Percentage of 5-year olds at 'expected level' in literacy early learning goals (%) [Early years literacy]", "Percentage of 5-year olds at 'expected level' in maths early learning goals (%) [Early years maths]", 'Count of 19+ Further Education and Skills Learner Achievements (qualifications) [FE and skills achievements]', 'Apprenticeships started by adults aged 16+ based on home address (per 100,000 population) [Apprenticeship starts]', 'Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]', '19+ further education and skills participation (per 100,000 population) [FE and skills participation]', 'Percentage of adults that currently smoke cigarettes (%) [Smokers]', 'Proportion of children living with obesity at reception age (%) [Reception obesity]', 'Proportion of children living with obesity at Year 6 age (%) [Year 6 obesity]', 'Proportion of adults living with obesity, aged 18 years and over (%) [Adult obesity]', 'Age-standardised mortality rate for those aged under 75 (per 100,000 population) [Under 75 mortality rate]', 'Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]', 'Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]', 'Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]', 'Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]', 'Net additions per 1,000 stock [Net additions]']

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,count_bus_Advanced_manufacturing,count_bus_Creative_Industries,count_bus_Defence_sector,count_bus_Digital_and_Technology,count_bus_Financial_Services,count_bus_Life_Sciences,count_bus_Professional_and_Business_Services,...,gemp_Financial_Services,gemp_Life_Sciences,gemp_Professional_and_Business_Services,gfirms_Advanced_manufacturing,gfirms_Creative_Industries,gfirms_Defence_sector,gfirms_Digital_and_Technology,gfirms_Financial_Services,gfirms_Life_Sciences,gfirms_Professional_and_Business_Services
0,2022,E06000001,Hartlepool,20.0,100.0,0.0,285.0,55.0,0.0,640.0,...,0.255620,0.000000,-0.264062,-0.213574,-0.094410,0.0,-0.146126,0.000000,0.0,-0.103643
1,2022,E06000002,Middlesbrough,35.0,190.0,0.0,425.0,105.0,0.0,1160.0,...,-0.210614,0.000000,-0.045670,0.325423,-0.051031,0.0,-0.131769,0.000000,0.0,-0.070657
2,2022,E06000003,Redcar and Cleveland,35.0,145.0,0.0,360.0,65.0,0.0,875.0,...,0.150661,0.000000,-0.347651,-0.130053,0.187816,0.0,-0.053922,0.000000,0.0,-0.060893
3,2022,E06000004,Stockton-on-Tees,85.0,340.0,0.0,825.0,210.0,5.0,1990.0,...,-0.640111,-0.055263,-0.261752,0.123614,-0.043048,0.0,-0.092444,0.000000,0.0,-0.049006
4,2022,E06000005,Darlington,30.0,210.0,0.0,310.0,135.0,0.0,1005.0,...,0.206492,0.000000,-0.006210,0.000000,-0.090559,0.0,-0.120994,-0.036105,0.0,0.050979

In [ ]:
#Variables with growth rates:
X_clean= X_clean.rename(columns={
    'growth_firms': 'Business_growth_rate',
    'growth_emp': 'Employment_growth_rate'
})

In [ ]:
X_clean.head()

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment,Business_growth_rate,Employment_growth_rate,Gross Value Added (GVA) per hour worked (£) [GVA per hour],...,Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],Percentage of premises with gigabit-capable broadband (%) [Broadband availability],Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage],Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications],Percentage of adults that currently smoke cigarettes (%) [Smokers],Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction],Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile],Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]
0,2022,E06000001,Hartlepool,Professional and Business Services,"Accounting, audit and tax consultancy",25.0,175.0,0.000000,0.839751,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
1,2022,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,15.0,0.000000,-1.558145,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
2,2022,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
3,2022,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
4,2022,E06000001,Hartlepool,Financial Services,Asset management and wholesale services,10.0,45.0,-0.374693,0.245122,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48

In [ ]:
#With the previous code, I realised that some of the indicators were not numeric, so I will convert them to numeric:
cols_to_convert = [
    'Gross median weekly pay (£) [Weekly pay]',
    'Employment rate, aged 16 to 64 years (%) [Employment rate]',
    'Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]',
    'Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]',
    'Percentage of adults that currently smoke cigarettes (%) [Smokers]',
    'Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]',
    'Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]',
    'Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]',
    'Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]'
]
for col in cols_to_convert:
    X_clean[col] = pd.to_numeric(X_clean[col], errors='coerce')

print(X_clean.dtypes)

YEAR                                                                                                       int64
GEOGRAPHY_CODE                                                                                            object
GEOGRAPHY_NAME                                                                                            object
IS8_SECTOR                                                                                                object
FRONTIER_SECTOR                                                                                           object
OBS_Value_Business                                                                                       float64
OBS_Value_Employment                                                                                     float64
Business_growth_rate                                                                                     float64
Employment_growth_rate                                                                                   float64
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               float64
Gross median weekly pay (£) [Weekly pay]                                                                 float64
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               float64
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               float64
Gross disposable household income, per head (£) [GDHI per head]                                          float64
Count of births of new enterprises (control rounded to base 5) [New enterprises]                         float64
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                       float64
Count of active enterprises (control rounded to base 5) [Active enterprises]                             float64
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                   float64
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       float64
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                 float64
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        float64
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       float64
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    float64
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     float64
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                             float64
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                 float64
dtype: object

In [ ]:
##Number of missing values after conversion
print(X_clean.isnull().sum())

YEAR                                                                                                       0
GEOGRAPHY_CODE                                                                                             0
GEOGRAPHY_NAME                                                                                             0
IS8_SECTOR                                                                                                 0
FRONTIER_SECTOR                                                                                            0
OBS_Value_Business                                                                                         0
OBS_Value_Employment                                                                                       0
Business_growth_rate                                                                                       0
Employment_growth_rate                                                                                     0
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               198
Gross median weekly pay (£) [Weekly pay]                                                                  44
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               132
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               462
Gross disposable household income, per head (£) [GDHI per head]                                           88
Count of births of new enterprises (control rounded to base 5) [New enterprises]                          88
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        88
Count of active enterprises (control rounded to base 5) [Active enterprises]                              88
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                    88
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       198
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                 198
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        132
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       154
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    352
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     352
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                             352
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                 352
dtype: int64

In [ ]:
total = len(X_clean)
missing_pct = (X_clean.isnull().sum() / total * 100).round(1)
print(missing_pct[missing_pct > 0])

Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               2.5
Gross median weekly pay (£) [Weekly pay]                                                                 0.6
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               1.7
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               5.9
Gross disposable household income, per head (£) [GDHI per head]                                          1.1
Count of births of new enterprises (control rounded to base 5) [New enterprises]                         1.1
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                       1.1
Count of active enterprises (control rounded to base 5) [Active enterprises]                             1.1
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                   1.1
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       2.5
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                 2.5
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        1.7
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       2.0
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    4.5
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     4.5
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                             4.5
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                 4.5
dtype: float64

In [ ]:
# How many LADs needed the national median fallback?
lads_with_all_missing = X_clean.groupby('GEOGRAPHY_CODE')[col].apply(
    lambda x: x.isnull().all()
).sum()

print(f"LADs with no data at all for {col}: {lads_with_all_missing}")

LADs with no data at all for Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]: 16

One important thing — the wellbeing variables (Life satisfaction, Happiness, Worthwhile, Anxiety) and Unemployment rate tend to be missing in the same 16-21 LADs. This is likely because smaller or more rural LADs don't report these statistics.

For approximately 16-21 LADs (~5%) where no local data was available, missing values were imputed using the national median. These LADs are predominantly smaller or rural authorities with limited data reporting.

In [ ]:
# Columns to exclude from indicators
cols_to_exclude = ['YEAR', 'GEOGRAPHY_CODE', 'GEOGRAPHY_NAME', 
                   'IS8_SECTOR', 'FRONTIER_SECTOR', 
                   'OBS_Value_Business', 'OBS_Value_Employment',
                   'Business_growth_rate', 'Employment_growth_rate']

# X — only local indicators
indicators = X_clean.drop(columns=cols_to_exclude)

In [ ]:
##Imputations
fallback_summary = {}
for col in indicators.columns:
    lads_all_missing = X_clean.groupby('GEOGRAPHY_CODE')[col].apply(
        lambda x: x.isnull().all()
    ).sum()
    fallback_summary[col] = lads_all_missing
    
fallback_df = pd.DataFrame.from_dict(
    fallback_summary, orient='index', columns=['LADs using national median']
)

fallback_df = fallback_df[fallback_df['LADs using national median'] > 0].sort_values(
    'LADs using national median', ascending=False
)
print(fallback_df)
print(f"Total LADs in dataset: {X_clean['GEOGRAPHY_CODE'].nunique()}")

                                                    LADs using national median
Modelled unemployment rate, aged 16 years and o...                          21
Mean satisfaction with your life nowadays score...                          16
Mean feeling things done in life are worthwhile...                          16
Mean happiness yesterday scored 0 (not at all) ...                          16
Mean anxiety yesterday scored 0 (not at all) - ...                          16
Gross Value Added (GVA) per hour worked (£) [GV...                           9
Percentage of 4G coverage by at least one mobil...                           9
Percentage of premises with gigabit-capable bro...                           9
Percentage of adults that currently smoke cigar...                           7
Employment rate, aged 16 to 64 years (%) [Emplo...                           6
Proportion of the population aged 16 to 64 with...                           6
Count of births of new enterprises (control rou...                           4
Count of high growth enterprises (control round...                           4
Count of deaths of enterprises (control rounded...                           4
Gross disposable household income, per head (£)...                           4
Count of active enterprises (control rounded to...                           4
Gross median weekly pay (£) [Weekly pay]                                     2
Total LADs in dataset: 355

In [ ]:
## I will drop of my analysis modelled unemployment rate, as I have the employment variable:

In [ ]:
for col in indicators.columns:
    X_clean[col] = X_clean.groupby('GEOGRAPHY_CODE')[col].transform(
        lambda x: x.fillna(x.median())
    )
    X_clean[col] = X_clean[col].fillna(X_clean[col].median())  # fallback for any remaining missing with the national median

In [ ]:
X_clean.head(50)

,YEAR,GEOGRAPHY_CODE,GEOGRAPHY_NAME,IS8_SECTOR,FRONTIER_SECTOR,OBS_Value_Business,OBS_Value_Employment,Business_growth_rate,Employment_growth_rate,Gross Value Added (GVA) per hour worked (£) [GVA per hour],...,Count of active enterprises (control rounded to base 5) [Active enterprises],Count of high growth enterprises (control rounded to base 5) [High growth enterprises],Percentage of premises with gigabit-capable broadband (%) [Broadband availability],Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage],Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications],Percentage of adults that currently smoke cigarettes (%) [Smokers],Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction],Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile],Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness],Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]
0,2022,E06000001,Hartlepool,Professional and Business Services,"Accounting, audit and tax consultancy",25.0,175.0,0.000000,0.839751,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
1,2022,E06000001,Hartlepool,Creative Industries,Advertising and marketing,10.0,15.0,0.000000,-1.558145,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
2,2022,E06000001,Hartlepool,Advanced manufacturing,Aerospace manufacturing,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
3,2022,E06000001,Hartlepool,Advanced manufacturing,Agritech,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
4,2022,E06000001,Hartlepool,Financial Services,Asset management and wholesale services,10.0,45.0,-0.374693,0.245122,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
5,2022,E06000001,Hartlepool,Advanced manufacturing,Automotive manufacturing,0.0,400.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
6,2022,E06000001,Hartlepool,Advanced manufacturing,Batteries,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
7,2022,E06000001,Hartlepool,Financial Services,Capital markets and retail investment,20.0,90.0,0.271934,0.056512,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
8,2022,E06000001,Hartlepool,Defence sector,Defence Sector,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
9,2022,E06000001,Hartlepool,Digital and Technology,Digital and Technology,285.0,1395.0,-0.146126,-0.055725,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
10,2022,E06000001,Hartlepool,Creative Industries,Film and TV,5.0,40.0,0.000000,-0.115069,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
11,2022,E06000001,Hartlepool,Financial Services,Insurance and reinsurance markets,0.0,20.0,0.000000,0.646627,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
12,2022,E06000001,Hartlepool,Professional and Business Services,Legal services,10.0,225.0,0.000000,-0.104918,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
13,2022,E06000001,Hartlepool,Life Sciences,Life Sciences,0.0,40.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
14,2022,E06000001,Hartlepool,Professional and Business Services,Management consultancy,70.0,100.0,-0.191667,-1.245666,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
15,2022,E06000001,Hartlepool,Creative Industries,"Music, peforming, and visual arts",10.0,70.0,-0.646627,0.679161,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
16,2022,E06000001,Hartlepool,Advanced manufacturing,Others_Advanced manufacturing,20.0,1085.0,-0.213574,0.430641,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
17,2022,E06000001,Hartlepool,Creative Industries,Others_Creative Industries,75.0,660.0,0.000000,0.086874,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
18,2022,E06000001,Hartlepool,Financial Services,Others_Financial Services,25.0,110.0,0.000000,0.378797,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
19,2022,E06000001,Hartlepool,Professional and Business Services,Others_Professional and Business Services,535.0,2080.0,-0.097682,-0.255204,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
20,2022,E06000001,Hartlepool,Total,Total,2795.0,29340.0,-0.014205,-0.077993,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
21,2022,E06000001,Hartlepool,Creative Industries,Video games,0.0,0.0,0.000000,0.000000,29.84,...,2430.0,10.0,91.4,99.98,56.4,14.3,7.29,7.75,7.57,3.48
22,2022,E06000002,Middlesbrough,Professional and Business Services,"Accounting, audit and tax consultancy",40.0,450.0,0.130053,0.808163,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
23,2022,E06000002,Middlesbrough,Creative Industries,Advertising and marketing,15.0,45.0,0.000000,-1.449473,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
24,2022,E06000002,Middlesbrough,Advanced manufacturing,Aerospace manufacturing,0.0,10.0,0.000000,2.397895,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
25,2022,E06000002,Middlesbrough,Advanced manufacturing,Agritech,0.0,10.0,0.000000,2.397895,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
26,2022,E06000002,Middlesbrough,Financial Services,Asset management and wholesale services,30.0,700.0,0.000000,-0.250998,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
27,2022,E06000002,Middlesbrough,Advanced manufacturing,Automotive manufacturing,0.0,15.0,0.000000,0.374693,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
28,2022,E06000002,Middlesbrough,Advanced manufacturing,Batteries,0.0,0.0,0.000000,0.000000,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
29,2022,E06000002,Middlesbrough,Financial Services,Capital markets and retail investment,20.0,235.0,0.000000,-0.275961,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
30,2022,E06000002,Middlesbrough,Defence sector,Defence Sector,0.0,0.0,0.000000,0.000000,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
31,2022,E06000002,Middlesbrough,Digital and Technology,Digital and Technology,425.0,2505.0,-0.131769,-0.027550,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
32,2022,E06000002,Middlesbrough,Creative Industries,Film and TV,5.0,100.0,0.000000,-0.221161,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
33,2022,E06000002,Middlesbrough,Financial Services,Insurance and reinsurance markets,5.0,75.0,0.000000,1.072637,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
34,2022,E06000002,Middlesbrough,Professional and Business Services,Legal services,80.0,600.0,-0.059898,-0.287266,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
35,2022,E06000002,Middlesbrough,Life Sciences,Life Sciences,0.0,10.0,0.000000,0.000000,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
36,2022,E06000002,Middlesbrough,Professional and Business Services,Management consultancy,120.0,200.0,-0.079407,-1.095290,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
37,2022,E06000002,Middlesbrough,Creative Industries,"Music, peforming, and visual arts",20.0,55.0,0.000000,0.767255,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
38,2022,E06000002,Middlesbrough,Advanced manufacturing,Others_Advanced manufacturing,35.0,680.0,0.325423,0.529601,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
39,2022,E06000002,Middlesbrough,Creative Industries,Others_Creative Industries,140.0,1240.0,-0.101096,0.209936,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
40,2022,E06000002,Middlesbrough,Financial Services,Others_Financial Services,50.0,290.0,0.000000,-0.242879,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
41,2022,E06000002,Middlesbrough,Professional and Business Services,Others_Professional and Business Services,920.0,6560.0,-0.078287,-0.002283,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
42,2022,E06000002,Middlesbrough,Total,Total,4410.0,62680.0,-0.013511,0.000080,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
43,2022,E06000002,Middlesbrough,Creative Industries,Video games,10.0,450.0,0.606136,0.546947,29.50,...,4040.0,15.0,94.2,100.00,48.7,16.5,7.35,7.64,7.05,3.07
44,2022,E06000003,Redcar and Cleveland,Professional and Business Services,"Accounting, audit and tax consultancy",25.0,125.0,0.213574,0.221161,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
45,2022,E06000003,Redcar and Cleveland,Creative Industries,Advertising and marketing,15.0,15.0,0.980829,-1.338285,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
46,2022,E06000003,Redcar and Cleveland,Advanced manufacturing,Aerospace manufacturing,0.0,10.0,-1.791759,2.397895,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
47,2022,E06000003,Redcar and Cleveland,Advanced manufacturing,Agritech,5.0,5.0,0.000000,0.000000,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
48,2022,E06000003,Redcar and Cleveland,Financial Services,Asset management and wholesale services,20.0,75.0,0.000000,0.398908,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25
49,2022,E06000003,Redcar and Cleveland,Advanced manufacturing,Automotive manufacturing,0.0,300.0,0.000000,0.000000,28.42,...,3420.0,10.0,87.8,99.17,53.3,13.7,7.25,7.67,7.49,3.25

In [ ]:
lad_vars = (
    X_clean[X_clean["FRONTIER_SECTOR"] == "Total"]
    .groupby("GEOGRAPHY_CODE")
    .agg(
        GEOGRAPHY_NAME  = ("GEOGRAPHY_NAME", "first"),
        Business_growth = ("Business_growth_rate", "first"),  # adjust col name
        Employ_growth   = ("Employ_growth_rate",   "first"),  # adjust col name
        total_bus       = ("OBS_Value_Business", "first"),
        total_emp       = ("OBS_Value_Employment",  "first"),
    )
    .reset_index()
)

# 1b. Calculate sector shares from non-Total rows
sectors = X_clean[X_clean["FRONTIER_SECTOR"] != "Total"].copy()
sectors = sectors.merge(
    lad_vars[["GEOGRAPHY_CODE", "total_bus", "total_emp"]],
    on="GEOGRAPHY_CODE"
)

# Enterprise share per sector
sectors["ent_share"] = sectors["OBS_Value_Business"] / sectors["total_bus"]
# Employment share per sector
sectors["emp_share"] = sectors["OBS_Value_Employment"]  / sectors["total_emp"]

# 1c. Pivot to wide — one column per Frontier sector
ent_wide = sectors.pivot_table(
    index="GEOGRAPHY_CODE", columns="FRONTIER_SECTOR", values="ent_share"
)
ent_wide.columns = [f"ent_share_{c}" for c in ent_wide.columns]

emp_wide = sectors.pivot_table(
    index="GEOGRAPHY_CODE", columns="FRONTIER_SECTOR", values="emp_share"
)
emp_wide.columns = [f"emp_share_{c}" for c in emp_wide.columns]

# 1d. Merge everything together
df_wide = (
    lad_vars
    .set_index("GEOGRAPHY_CODE")
    .join(ent_wide)
    .join(emp_wide)
    .reset_index()
)

print(f"Wide dataset shape: {df_wide.shape}")  # should be ~350 rows
print(df_wide.head())

In [ ]:
ddddd

NameError: name 'ddddd' is not defined

In [ ]:
X = X_clean[indicators.columns].copy()
y_bus = X_clean['Business_growth_rate'].reset_index(drop=True)
y_emp = X_clean['Employment_growth_rate'].reset_index(drop=True)

print(f'X shape: {X.shape}, y_business growth shape: {y_bus.shape}, y_employment growth shape: {y_emp.shape}')

X shape: (7810, 17), y_business growth shape: (7810,), y_employment growth shape: (7810,)

In [ ]:
# Standardize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=indicators.columns, 
                            index=X_clean.index)

# Sector dummies
is8_dummies     = pd.get_dummies(X_clean['IS8_SECTOR'], 
                                  prefix='IS8', drop_first=True)
frontier_dummies = pd.get_dummies(X_clean['FRONTIER_SECTOR'], 
                                   prefix='FS', drop_first=True)

In [ ]:
cddddd

In [ ]:
##### LASSO — variable selection 
lasso_bus = LassoCV(cv=10, random_state=42, max_iter=10000).fit(X_scaled, y_bus)
lasso_emp = LassoCV(cv=10, random_state=42, max_iter=10000).fit(X_scaled, y_emp)

selected_bus = [col for col, coef in zip(indicators.columns, lasso_bus.coef_) if coef != 0]
selected_emp = [col for col, coef in zip(indicators.columns, lasso_emp.coef_) if coef != 0]

# LASSO coefficients summary
lasso_bus_df = pd.DataFrame({
    'Variable'   : indicators.columns,
    'Coefficient': lasso_bus.coef_
}).query('Coefficient != 0').sort_values('Coefficient', key=abs, ascending=False)

lasso_emp_df = pd.DataFrame({
    'Variable'   : indicators.columns,
    'Coefficient': lasso_emp.coef_
}).query('Coefficient != 0').sort_values('Coefficient', key=abs, ascending=False)

C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.903e+00, tolerance: 2.159e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.078e+01, tolerance: 2.159e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.842e-01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.214e+00, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.916e+01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.896e+01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.678e+01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.275e+01, tolerance: 2.082e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.294e+00, tolerance: 2.094e-01
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\diane\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.592e+01, tolerance: 2.094e-01
  model = cd_fast.enet_coordinate_descent_gram(

In [ ]:
print(f"LASSO — Business growth selected {len(selected_bus)} variables:")
print(lasso_bus_df.to_string(index=False))

LASSO — Business growth selected 8 variables:
                                                                                             Variable  Coefficient
                                           Gross Value Added (GVA) per hour worked (£) [GVA per hour]    -0.009159
                                                             Gross median weekly pay (£) [Weekly pay]    -0.007358
    Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]     0.006564
                             Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]    -0.004866
                   Percentage of premises with gigabit-capable broadband (%) [Broadband availability]    -0.004678
                                   Percentage of adults that currently smoke cigarettes (%) [Smokers]     0.004444
                                           Employment rate, aged 16 to 64 years (%) [Employment rate]     0.002566
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]     0.000382

In [ ]:
print(f"LASSO — Employment growth selected {len(selected_emp)} variables:")
print(lasso_emp_df.to_string(index=False))

LASSO — Employment growth selected 0 variables:
Empty DataFrame
Columns: [Variable, Coefficient]
Index: []

In [ ]:
# ── Sector dummies ────────────────────────────────────────────────
is8_dummies      = pd.get_dummies(X_clean['IS8_SECTOR'],      drop_first=True).astype(float)
frontier_dummies = pd.get_dummies(X_clean['FRONTIER_SECTOR'], drop_first=True).astype(float)

In [ ]:
# ── Modelos CON estandarización ───────────────────────────────────
def run_ols_scaled(y, dummies, label):
    X_ols = pd.concat([
        X_scaled_df[indicators.columns].reset_index(drop=True),
        dummies.reset_index(drop=True)
    ], axis=1).astype(float)
    X_ols = sm.add_constant(X_ols)
    model = sm.OLS(y, X_ols).fit(cov_type='HC3')
    print(f"\n{'='*60}")
    print(f"MODEL (SCALED): {label}")
    print(model.summary())
    return model

# ── Modelos SIN estandarización ───────────────────────────────────
def run_ols_raw(y, dummies, label):
    X_ols = pd.concat([
        X_clean[indicators.columns].reset_index(drop=True),
        dummies.reset_index(drop=True)
    ], axis=1).astype(float)
    X_ols = sm.add_constant(X_ols)
    model = sm.OLS(y, X_ols).fit(cov_type='HC3')
    print(f"\n{'='*60}")
    print(f"MODEL (RAW): {label}")
    print(model.summary())
    return model

### IS8 FIXED EFFECTS

Business outcome

In [ ]:

print("IS8 with standarized local indicators")
m1_scaled = run_ols_scaled(y_bus, is8_dummies, "M1: Business Growth   + IS8 FE")

IS8 with standarized local indicators

============================================================
MODEL (SCALED): M1: Business Growth   + IS8 FE
                             OLS Regression Results
================================================================================
Dep. Variable:     Business_growth_rate   R-squared:                       0.253
Model:                              OLS   Adj. R-squared:                  0.250
Method:                   Least Squares   F-statistic:                     6.821
Date:                  Sun, 15 Mar 2026   Prob (F-statistic):           1.38e-21
Time:                          15:45:56   Log-Likelihood:                -61410.
No. Observations:                  6035   AIC:                         1.229e+05
Df Residuals:                      6011   BIC:                         1.230e+05
Df Model:                            23
Covariance Type:                    HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                    16.8380     94.754      0.178      0.859    -168.876     202.552
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                3.9636     18.593      0.213      0.831     -32.479      40.406
Gross median weekly pay (£) [Weekly pay]                                                                 14.5785     15.598      0.935      0.350     -15.994      45.151
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                0.4539     50.572      0.009      0.993     -98.666      99.574
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               -0.3302    174.461     -0.002      0.998    -342.268     341.607
Gross disposable household income, per head (£) [GDHI per head]                                          14.3415     61.300      0.234      0.815    -105.804     134.487
Count of births of new enterprises (control rounded to base 5) [New enterprises]                        362.7540   2.57e+04      0.014      0.989      -5e+04    5.07e+04
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                     1538.5020   4.43e+04      0.035      0.972   -8.52e+04    8.83e+04
Count of active enterprises (control rounded to base 5) [Active enterprises]                              0.7924   6.19e+04   1.28e-05      1.000   -1.21e+05    1.21e+05
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                 1719.6717   6152.712      0.279      0.780   -1.03e+04    1.38e+04
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       -6.9944     95.100     -0.074      0.941    -193.388     179.399
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                  1.7020     10.833      0.157      0.875     -19.530      22.934
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        12.9360     17.414      0.743      0.458     -21.195      47.067
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       -0.6279     27.973     -0.022      0.982     -55.454      54.198
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    -0.1328     25.434     -0.005      0.996     -49.982      49.716
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     -2.1807     14.939     -0.146      0.884     -31.462      27.100
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                              0.0524     14.517      0.004      0.997     -28.400      28.505
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                  2.1633     26.500      0.082      0.935     -49.776      54.103
Creative Industries                                                                                     243.1549    108.304      2.245      0.025      30.882     455.428
Defence sector                                                                                          -15.4296    218.148     -0.071      0.944    -442.993     412.134
Digital and Technology                                                                                 3259.9366   1209.364      2.696      0.007     889.626    5630.247
Financial Services                                                                                      248.6127    112.435      2.211      0.027      28.243     468.982
Life Sciences                                                                                            30.5563    199.916      0.153      0.879    -361.272     422.385
Professional and Business Services                                                                      842.7817    202.939      4.153      0.000     445.028    1240.536
==============================================================================
Omnibus:                    15348.248   Durbin-Watson:                   2.126
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        278907765.728
Skew:                          28.266   Prob(JB):                         0.00
Kurtosis:                    1054.649   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [ ]:
print("IS8 without standarized local indicators")
m1_raw    = run_ols_raw   (y_bus, is8_dummies, "M1: Business Growth   + IS8 FE")

IS8 without standarized local indicators

============================================================
MODEL (RAW): M1: Business Growth   + IS8 FE
                             OLS Regression Results
================================================================================
Dep. Variable:     Business_growth_rate   R-squared:                       0.253
Model:                              OLS   Adj. R-squared:                  0.250
Method:                   Least Squares   F-statistic:                     6.821
Date:                  Sun, 15 Mar 2026   Prob (F-statistic):           1.38e-21
Time:                          15:45:56   Log-Likelihood:                -61410.
No. Observations:                  6035   AIC:                         1.229e+05
Df Residuals:                      6011   BIC:                         1.230e+05
Df Model:                            23
Covariance Type:                    HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                  -674.8220    919.283     -0.734      0.463   -2476.583    1126.939
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                0.4787      2.245      0.213      0.831      -3.922       4.880
Gross median weekly pay (£) [Weekly pay]                                                                  0.2162      0.231      0.935      0.350      -0.237       0.670
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                0.0790      8.801      0.009      0.993     -17.171      17.329
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               -0.3285    173.557     -0.002      0.998    -340.493     339.836
Gross disposable household income, per head (£) [GDHI per head]                                           0.0013      0.005      0.234      0.815      -0.009       0.012
Count of births of new enterprises (control rounded to base 5) [New enterprises]                          0.0126      0.892      0.014      0.989      -1.735       1.760
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        0.0521      1.499      0.035      0.972      -2.885       2.989
Count of active enterprises (control rounded to base 5) [Active enterprises]                           3.199e-06      0.250   1.28e-05      1.000      -0.490       0.490
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                    1.7603      6.298      0.279      0.780     -10.584      14.104
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       -0.3819      5.192     -0.074      0.941     -10.559       9.795
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                  0.4855      3.090      0.157      0.875      -5.571       6.543
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]         1.4784      1.990      0.743      0.458      -2.422       5.379
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       -0.1634      7.279     -0.022      0.982     -14.430      14.103
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    -0.5398    103.349     -0.005      0.996    -203.101     202.021
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     -8.9761     61.493     -0.146      0.884    -129.500     111.548
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                              0.2033     56.299      0.004      0.997    -110.140     110.546
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                  5.4539     66.811      0.082      0.935    -125.494     136.402
Creative Industries                                                                                     243.1549    108.304      2.245      0.025      30.882     455.428
Defence sector                                                                                          -15.4296    218.148     -0.071      0.944    -442.993     412.134
Digital and Technology                                                                                 3259.9366   1209.364      2.696      0.007     889.626    5630.247
Financial Services                                                                                      248.6127    112.435      2.211      0.027      28.243     468.982
Life Sciences                                                                                            30.5563    199.916      0.153      0.879    -361.272     422.385
Professional and Business Services                                                                      842.7817    202.939      4.153      0.000     445.028    1240.536
==============================================================================
Omnibus:                    15348.248   Durbin-Watson:                   2.126
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        278907765.728
Skew:                          28.266   Prob(JB):                         0.00
Kurtosis:                    1054.649   Cond. No.                     1.55e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.55e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

Employment outcome

In [ ]:
#With standarizaed local indicators
m2_scaled = run_ols_scaled(y_emp, is8_dummies, "M2: Employment Growth + IS8 FE")

============================================================

MODEL (SCALED): M2: Employment Growth + IS8 FE
                              OLS Regression Results
==================================================================================
Dep. Variable:     Employment_growth_rate   R-squared:                       0.295
Model:                                OLS   Adj. R-squared:                  0.292
Method:                     Least Squares   F-statistic:                     11.13
Date:                    Sun, 15 Mar 2026   Prob (F-statistic):           2.88e-40
Time:                            15:45:56   Log-Likelihood:                -73160.
No. Observations:                    6035   AIC:                         1.464e+05
Df Residuals:                        6011   BIC:                         1.465e+05
Df Model:                              23
Covariance Type:                      HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                   663.9930    642.498      1.033      0.301    -595.280    1923.266
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                              211.2011    139.801      1.511      0.131     -62.803     485.205
Gross median weekly pay (£) [Weekly pay]                                                               -240.3826    213.697     -1.125      0.261    -659.220     178.455
Employment rate, aged 16 to 64 years (%) [Employment rate]                                              113.6692    360.166      0.316      0.752    -592.243     819.582
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                              151.0727   1226.098      0.123      0.902   -2252.035    2554.181
Gross disposable household income, per head (£) [GDHI per head]                                         627.6812    623.162      1.007      0.314    -593.693    1849.056
Count of births of new enterprises (control rounded to base 5) [New enterprises]                      -4202.1830    1.8e+05     -0.023      0.981   -3.57e+05    3.48e+05
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                     9713.2997    3.1e+05      0.031      0.975   -5.98e+05    6.17e+05
Count of active enterprises (control rounded to base 5) [Active enterprises]                          -1.994e+04   4.35e+05     -0.046      0.963   -8.73e+05    8.33e+05
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                 4.264e+04   4.35e+04      0.981      0.326   -4.25e+04    1.28e+05
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       82.2177    669.863      0.123      0.902   -1230.689    1395.124
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                -83.1145     87.887     -0.946      0.344    -255.370      89.141
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]       -53.9912    145.044     -0.372      0.710    -338.272     230.290
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       14.7230    200.480      0.073      0.941    -378.210     407.656
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    72.6774    185.913      0.391      0.696    -291.705     437.059
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     14.6675    112.681      0.130      0.896    -206.184     235.519
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                            -85.4667    114.104     -0.749      0.454    -309.106     138.173
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                -20.2549    189.790     -0.107      0.915    -392.237     351.727
Creative Industries                                                                                     636.1655    819.302      0.776      0.437    -969.637    2241.968
Defence sector                                                                                         -478.6972   1595.754     -0.300      0.764   -3606.317    2648.923
Digital and Technology                                                                                  2.44e+04   9135.734      2.670      0.008    6489.411    4.23e+04
Financial Services                                                                                     3602.2277    767.892      4.691      0.000    2097.186    5107.269
Life Sciences                                                                                           528.3310   1226.323      0.431      0.667   -1875.218    2931.880
Professional and Business Services                                                                     4085.3075    747.462      5.466      0.000    2620.309    5550.306
==============================================================================
Omnibus:                    16259.101   Durbin-Watson:                   1.897
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        470148647.257
Skew:                          32.689   Prob(JB):                         0.00
Kurtosis:                    1368.802   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [ ]:
#Without standarised local indicators
m2_raw    = run_ols_raw   (y_emp, is8_dummies, "M2: Employment Growth + IS8 FE")

============================================================
MODEL (RAW): M2: Employment Growth + IS8 FE
                              OLS Regression Results
==================================================================================
Dep. Variable:     Employment_growth_rate   R-squared:                       0.295
Model:                                OLS   Adj. R-squared:                  0.292
Method:                     Least Squares   F-statistic:                     11.13
Date:                    Sun, 15 Mar 2026   Prob (F-statistic):           2.88e-40
Time:                            15:45:56   Log-Likelihood:                -73160.
No. Observations:                    6035   AIC:                         1.464e+05
Df Residuals:                        6011   BIC:                         1.465e+05
Df Model:                              23
Covariance Type:                      HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                 -2802.3255   6715.504     -0.417      0.676    -1.6e+04    1.04e+04
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               25.5059     16.883      1.511      0.131      -7.584      58.596
Gross median weekly pay (£) [Weekly pay]                                                                 -3.5654      3.170     -1.125      0.261      -9.778       2.647
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               19.7825     62.682      0.316      0.752    -103.072     142.637
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                              150.2896   1219.742      0.123      0.902   -2240.361    2540.940
Gross disposable household income, per head (£) [GDHI per head]                                           0.0559      0.056      1.007      0.314      -0.053       0.165
Count of births of new enterprises (control rounded to base 5) [New enterprises]                         -0.1459      6.249     -0.023      0.981     -12.395      12.103
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        0.3287     10.488      0.031      0.975     -20.227      20.885
Count of active enterprises (control rounded to base 5) [Active enterprises]                             -0.0805      1.756     -0.046      0.963      -3.523       3.362
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                   43.6481     44.480      0.981      0.326     -43.532     130.828
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                        4.4889     36.573      0.123      0.902     -67.193      76.171
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                -23.7107     25.072     -0.946      0.344     -72.851      25.430
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        -6.1703     16.576     -0.372      0.710     -38.659      26.318
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                        3.8311     52.167      0.073      0.941     -98.415     106.077
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]   295.3228    755.451      0.391      0.696   -1185.334    1775.980
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     60.3736    463.812      0.130      0.896    -848.680     969.427
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                           -331.4546    442.514     -0.749      0.454   -1198.767     535.858
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                -51.0659    478.492     -0.107      0.915    -988.894     886.762
Creative Industries                                                                                     636.1655    819.302      0.776      0.437    -969.637    2241.968
Defence sector                                                                                         -478.6972   1595.754     -0.300      0.764   -3606.317    2648.923
Digital and Technology                                                                                  2.44e+04   9135.734      2.670      0.008    6489.411    4.23e+04
Financial Services                                                                                     3602.2277    767.892      4.691      0.000    2097.186    5107.269
Life Sciences                                                                                           528.3310   1226.323      0.431      0.667   -1875.218    2931.880
Professional and Business Services                                                                     4085.3075    747.462      5.466      0.000    2620.309    5550.306
==============================================================================
Omnibus:                    16259.101   Durbin-Watson:                   1.897
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        470148647.257
Skew:                          32.689   Prob(JB):                         0.00
Kurtosis:                    1368.802   Cond. No.                     1.55e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.55e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

## FRONTIER SECTOR FIXED EFFECTS

Business outcome

In [ ]:
# With standarised local indicators
m3_scaled = run_ols_scaled(y_bus, frontier_dummies, "M3: Business Growth   + Frontier FE")

============================================================
MODEL (SCALED): M3: Business Growth   + Frontier FE
                             OLS Regression Results
================================================================================
Dep. Variable:     Business_growth_rate   R-squared:                       0.255
Model:                              OLS   Adj. R-squared:                  0.251
Method:                   Least Squares   F-statistic:                     31.21
Date:                  Sun, 15 Mar 2026   Prob (F-statistic):          7.68e-179
Time:                          15:45:56   Log-Likelihood:                -61405.
No. Observations:                  6035   AIC:                         1.229e+05
Df Residuals:                      6001   BIC:                         1.231e+05
Df Model:                            33
Covariance Type:                    HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                   478.4366      9.047     52.885      0.000     460.705     496.168
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                3.9636     18.753      0.211      0.833     -32.791      40.718
Gross median weekly pay (£) [Weekly pay]                                                                 14.5785     15.738      0.926      0.354     -16.267      45.424
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                0.4539     50.676      0.009      0.993     -98.868      99.776
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               -0.3302    174.363     -0.002      0.998    -342.076     341.415
Gross disposable household income, per head (£) [GDHI per head]                                          14.3415     61.231      0.234      0.815    -105.669     134.352
Count of births of new enterprises (control rounded to base 5) [New enterprises]                        362.7540   2.57e+04      0.014      0.989   -4.99e+04    5.06e+04
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                     1538.5020   4.42e+04      0.035      0.972   -8.52e+04    8.83e+04
Count of active enterprises (control rounded to base 5) [Active enterprises]                              0.7924   6.19e+04   1.28e-05      1.000   -1.21e+05    1.21e+05
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                 1719.6717   6143.136      0.280      0.780   -1.03e+04    1.38e+04
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       -6.9944     95.096     -0.074      0.941    -193.379     179.390
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                  1.7020     11.395      0.149      0.881     -20.632      24.036
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        12.9360     17.713      0.730      0.465     -21.780      47.652
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       -0.6279     28.125     -0.022      0.982     -55.751      54.496
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    -0.1328     25.831     -0.005      0.996     -50.761      50.495
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     -2.1807     15.524     -0.140      0.888     -32.607      28.246
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                              0.0524     15.104      0.003      0.997     -29.551      29.656
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                  2.1633     26.699      0.081      0.935     -50.167      54.493
Advertising and marketing                                                                              -183.1831     69.898     -2.621      0.009    -320.180     -46.186
Aerospace manufacturing                                                                                -458.6197    188.519     -2.433      0.015    -828.109     -89.130
Agritech                                                                                               -473.0986    194.969     -2.427      0.015    -855.231     -90.966
Asset management and wholesale services                                                                 -41.9155     15.819     -2.650      0.008     -72.921     -10.910
Automotive manufacturing                                                                               -436.9718    179.478     -2.435      0.015    -788.742     -85.201
Batteries                                                                                              -477.7042    197.069     -2.424      0.015    -863.953     -91.456
Capital markets and retail investment                                                                  -192.0704     74.741     -2.570      0.010    -338.560     -45.581
Defence Sector                                                                                         -477.0282    196.704     -2.425      0.015    -862.560     -91.496
Digital and Technology                                                                                 2798.3380   1205.681      2.321      0.020     435.247    5161.429
Film and TV                                                                                            -163.3662     61.897     -2.639      0.008    -284.683     -42.049
Insurance and reinsurance markets                                                                      -404.9718    165.243     -2.451      0.014    -728.843     -81.101
Legal services                                                                                          -83.5211     32.781     -2.548      0.011    -147.770     -19.272
Life Sciences                                                                                          -431.0423    176.267     -2.445      0.014    -776.519     -85.566
Management consultancy                                                                                 1227.0704    535.467      2.292      0.022     177.575    2276.566
Music, peforming, and visual arts                                                                       -72.3239     24.668     -2.932      0.003    -120.672     -23.975
Video games                                                                                            -454.9014    187.004     -2.433      0.015    -821.422     -88.381
==============================================================================
Omnibus:                    15353.427   Durbin-Watson:                   2.125
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        280228580.060
Skew:                          28.289   Prob(JB):                         0.00
Kurtosis:                    1057.141   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [ ]:
# Without standarised local indicators
m3_raw    = run_ols_raw   (y_bus, frontier_dummies, "M3: Business Growth   + Frontier FE")

============================================================
MODEL (RAW): M3: Business Growth   + Frontier FE
                             OLS Regression Results
================================================================================
Dep. Variable:     Business_growth_rate   R-squared:                       0.255
Model:                              OLS   Adj. R-squared:                  0.251
Method:                   Least Squares   F-statistic:                     31.21
Date:                  Sun, 15 Mar 2026   Prob (F-statistic):          7.70e-179
Time:                          15:45:56   Log-Likelihood:                -61405.
No. Observations:                  6035   AIC:                         1.229e+05
Df Residuals:                      6001   BIC:                         1.231e+05
Df Model:                            33
Covariance Type:                    HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                  -213.2234    930.688     -0.229      0.819   -2037.338    1610.891
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                                0.4787      2.265      0.211      0.833      -3.960       4.917
Gross median weekly pay (£) [Weekly pay]                                                                  0.2162      0.233      0.926      0.354      -0.241       0.674
Employment rate, aged 16 to 64 years (%) [Employment rate]                                                0.0790      8.819      0.009      0.993     -17.207      17.365
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                               -0.3285    173.459     -0.002      0.998    -340.302     339.645
Gross disposable household income, per head (£) [GDHI per head]                                           0.0013      0.005      0.234      0.815      -0.009       0.012
Count of births of new enterprises (control rounded to base 5) [New enterprises]                          0.0126      0.891      0.014      0.989      -1.733       1.759
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        0.0521      1.497      0.035      0.972      -2.883       2.987
Count of active enterprises (control rounded to base 5) [Active enterprises]                           3.199e-06      0.250   1.28e-05      1.000      -0.490       0.490
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                    1.7603      6.288      0.280      0.780     -10.564      14.085
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       -0.3819      5.192     -0.074      0.941     -10.558       9.794
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                  0.4855      3.251      0.149      0.881      -5.886       6.857
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]         1.4784      2.024      0.730      0.465      -2.489       5.446
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       -0.1634      7.318     -0.022      0.982     -14.507      14.180
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    -0.5398    104.965     -0.005      0.996    -206.267     205.187
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     -8.9761     63.899     -0.140      0.888    -134.215     116.263
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                              0.2033     58.577      0.003      0.997    -114.606     115.012
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                  5.4539     67.314      0.081      0.935    -126.478     137.386
Advertising and marketing                                                                              -183.1831     69.898     -2.621      0.009    -320.180     -46.186
Aerospace manufacturing                                                                                -458.6197    188.519     -2.433      0.015    -828.109     -89.130
Agritech                                                                                               -473.0986    194.969     -2.427      0.015    -855.231     -90.966
Asset management and wholesale services                                                                 -41.9155     15.819     -2.650      0.008     -72.921     -10.910
Automotive manufacturing                                                                               -436.9718    179.478     -2.435      0.015    -788.742     -85.201
Batteries                                                                                              -477.7042    197.069     -2.424      0.015    -863.953     -91.456
Capital markets and retail investment                                                                  -192.0704     74.741     -2.570      0.010    -338.560     -45.581
Defence Sector                                                                                         -477.0282    196.704     -2.425      0.015    -862.560     -91.496
Digital and Technology                                                                                 2798.3380   1205.681      2.321      0.020     435.247    5161.429
Film and TV                                                                                            -163.3662     61.897     -2.639      0.008    -284.683     -42.049
Insurance and reinsurance markets                                                                      -404.9718    165.243     -2.451      0.014    -728.843     -81.101
Legal services                                                                                          -83.5211     32.781     -2.548      0.011    -147.770     -19.272
Life Sciences                                                                                          -431.0423    176.267     -2.445      0.014    -776.519     -85.566
Management consultancy                                                                                 1227.0704    535.467      2.292      0.022     177.575    2276.566
Music, peforming, and visual arts                                                                       -72.3239     24.668     -2.932      0.003    -120.672     -23.975
Video games                                                                                            -454.9014    187.004     -2.433      0.015    -821.422     -88.381
==============================================================================
Omnibus:                    15353.427   Durbin-Watson:                   2.125
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        280228580.060
Skew:                          28.289   Prob(JB):                         0.00
Kurtosis:                    1057.141   Cond. No.                     1.55e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.55e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

Employment outcome

In [ ]:
m4_scaled = run_ols_scaled(y_emp, frontier_dummies, "M4: Employment Growth + Frontier FE")

============================================================
MODEL (SCALED): M4: Employment Growth + Frontier FE
                              OLS Regression Results
==================================================================================
Dep. Variable:     Employment_growth_rate   R-squared:                       0.295
Model:                                OLS   Adj. R-squared:                  0.291
Method:                     Least Squares   F-statistic:                     21.08
Date:                    Sun, 15 Mar 2026   Prob (F-statistic):          1.10e-117
Time:                            15:45:57   Log-Likelihood:                -73159.
No. Observations:                    6035   AIC:                         1.464e+05
Df Residuals:                        6001   BIC:                         1.466e+05
Df Model:                              33
Covariance Type:                      HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                  4982.1408    611.919      8.142      0.000    3782.801    6181.481
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                              211.2011    140.119      1.507      0.132     -63.427     485.829
Gross median weekly pay (£) [Weekly pay]                                                               -240.3826    213.050     -1.128      0.259    -657.954     177.189
Employment rate, aged 16 to 64 years (%) [Employment rate]                                              113.6692    360.391      0.315      0.752    -592.684     820.022
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                              151.0727   1226.174      0.123      0.902   -2252.184    2554.329
Gross disposable household income, per head (£) [GDHI per head]                                         627.6812    621.639      1.010      0.313    -590.709    1846.071
Count of births of new enterprises (control rounded to base 5) [New enterprises]                      -4202.1830    1.8e+05     -0.023      0.981   -3.57e+05    3.48e+05
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                     9713.2997    3.1e+05      0.031      0.975   -5.98e+05    6.17e+05
Count of active enterprises (control rounded to base 5) [Active enterprises]                          -1.994e+04   4.35e+05     -0.046      0.963   -8.73e+05    8.33e+05
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                 4.264e+04   4.34e+04      0.982      0.326   -4.25e+04    1.28e+05
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                       82.2177    669.967      0.123      0.902   -1230.894    1395.329
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                -83.1145     88.685     -0.937      0.349    -256.934      90.705
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]       -53.9912    145.339     -0.371      0.710    -338.851     230.869
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                       14.7230    200.763      0.073      0.942    -378.765     408.211
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]    72.6774    186.605      0.389      0.697    -293.062     438.417
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     14.6675    113.685      0.129      0.897    -208.151     237.486
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                            -85.4667    114.927     -0.744      0.457    -310.719     139.785
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                -20.2549    190.145     -0.107      0.915    -392.931     352.422
Advertising and marketing                                                                             -3140.0986    959.449     -3.273      0.001   -5020.584   -1259.613
Aerospace manufacturing                                                                               -3966.0423   1275.290     -3.110      0.002   -6465.564   -1466.520
Agritech                                                                                              -4897.3380   1621.701     -3.020      0.003   -8075.814   -1718.862
Asset management and wholesale services                                                                 897.0563   1181.755      0.759      0.448   -1419.142    3213.254
Automotive manufacturing                                                                              -3452.3239   1077.082     -3.205      0.001   -5563.366   -1341.282
Batteries                                                                                             -4956.8873   1646.223     -3.011      0.003   -8183.424   -1730.350
Capital markets and retail investment                                                                  -355.4930    780.702     -0.455      0.649   -1885.640    1174.654
Defence Sector                                                                                        -4796.8451   1583.689     -3.029      0.002   -7900.819   -1692.871
Digital and Technology                                                                                 2.008e+04   9133.634      2.198      0.028    2175.378     3.8e+04
Film and TV                                                                                           -3200.9859    989.740     -3.234      0.001   -5140.841   -1261.131
Insurance and reinsurance markets                                                                     -2689.3239    833.583     -3.226      0.001   -4323.116   -1055.532
Legal services                                                                                        -1476.3662    620.056     -2.381      0.017   -2691.654    -261.078
Life Sciences                                                                                         -3789.8169   1210.582     -3.131      0.002   -6162.515   -1417.119
Management consultancy                                                                                  777.8451   1140.249      0.682      0.495   -1457.002    3012.692
Music, peforming, and visual arts                                                                     -3678.6338   1163.779     -3.161      0.002   -5959.599   -1397.669
Video games                                                                                           -4708.2113   1546.500     -3.044      0.002   -7739.296   -1677.127
==============================================================================
Omnibus:                    16262.678   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        470821625.887
Skew:                          32.708   Prob(JB):                         0.00
Kurtosis:                    1369.779   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [ ]:
m4_raw    = run_ols_raw   (y_emp, frontier_dummies, "M4: Employment Growth + Frontier FE")

============================================================
MODEL (RAW): M4: Employment Growth + Frontier FE
                              OLS Regression Results
==================================================================================
Dep. Variable:     Employment_growth_rate   R-squared:                       0.295
Model:                                OLS   Adj. R-squared:                  0.291
Method:                     Least Squares   F-statistic:                     21.08
Date:                    Sun, 15 Mar 2026   Prob (F-statistic):          1.11e-117
Time:                            15:45:57   Log-Likelihood:                -73159.
No. Observations:                    6035   AIC:                         1.464e+05
Df Residuals:                        6001   BIC:                         1.466e+05
Df Model:                              33
Covariance Type:                      HC3
=========================================================================================================================================================================
                                                                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                  1515.8223   6748.280      0.225      0.822   -1.17e+04    1.47e+04
Gross Value Added (GVA) per hour worked (£) [GVA per hour]                                               25.5059     16.922      1.507      0.132      -7.660      58.672
Gross median weekly pay (£) [Weekly pay]                                                                 -3.5654      3.160     -1.128      0.259      -9.759       2.628
Employment rate, aged 16 to 64 years (%) [Employment rate]                                               19.7825     62.721      0.315      0.752    -103.148     142.713
Modelled unemployment rate, aged 16 years and over (%) [Unemployment rate]                              150.2896   1219.818      0.123      0.902   -2240.509    2541.088
Gross disposable household income, per head (£) [GDHI per head]                                           0.0559      0.055      1.010      0.313      -0.053       0.164
Count of births of new enterprises (control rounded to base 5) [New enterprises]                         -0.1459      6.249     -0.023      0.981     -12.394      12.103
Count of deaths of enterprises (control rounded to base 5) [Deaths of enterprises]                        0.3287     10.488      0.031      0.975     -20.227      20.885
Count of active enterprises (control rounded to base 5) [Active enterprises]                             -0.0805      1.756     -0.046      0.963      -3.523       3.362
Count of high growth enterprises (control rounded to base 5) [High growth enterprises]                   43.6481     44.463      0.982      0.326     -43.497     130.793
Percentage of premises with gigabit-capable broadband (%) [Broadband availability]                        4.4889     36.579      0.123      0.902     -67.204      76.182
Percentage of 4G coverage by at least one mobile network operator (%) [4G area coverage]                -23.7107     25.300     -0.937      0.349     -73.298      25.876
Proportion of the population aged 16 to 64 with NVQ3+ qualification (%) [Level 3+ qualifications]        -6.1703     16.610     -0.371      0.710     -38.725      26.385
Percentage of adults that currently smoke cigarettes (%) [Smokers]                                        3.8311     52.241      0.073      0.942     -98.559     106.221
Mean satisfaction with your life nowadays scored 0 (not at all) - 10 (completely) [Life satisfaction]   295.3228    758.265      0.389      0.697   -1190.850    1781.495
Mean feeling things done in life are worthwhile scored 0 (not at all) - 10 (completely) [Worthwhile]     60.3736    467.943      0.129      0.897    -856.778     977.525
Mean happiness yesterday scored 0 (not at all) - 10 (completely) [Happiness]                           -331.4546    445.705     -0.744      0.457   -1205.021     542.112
Mean anxiety yesterday scored 0 (not at all) - 10 (completely) [Anxiety]                                -51.0659    479.386     -0.107      0.915    -990.645     888.513
Advertising and marketing                                                                             -3140.0986    959.449     -3.273      0.001   -5020.584   -1259.613
Aerospace manufacturing                                                                               -3966.0423   1275.290     -3.110      0.002   -6465.564   -1466.520
Agritech                                                                                              -4897.3380   1621.701     -3.020      0.003   -8075.814   -1718.862
Asset management and wholesale services                                                                 897.0563   1181.755      0.759      0.448   -1419.142    3213.254
Automotive manufacturing                                                                              -3452.3239   1077.082     -3.205      0.001   -5563.366   -1341.282
Batteries                                                                                             -4956.8873   1646.223     -3.011      0.003   -8183.424   -1730.350
Capital markets and retail investment                                                                  -355.4930    780.702     -0.455      0.649   -1885.640    1174.654
Defence Sector                                                                                        -4796.8451   1583.689     -3.029      0.002   -7900.819   -1692.871
Digital and Technology                                                                                 2.008e+04   9133.634      2.198      0.028    2175.378     3.8e+04
Film and TV                                                                                           -3200.9859    989.740     -3.234      0.001   -5140.841   -1261.131
Insurance and reinsurance markets                                                                     -2689.3239    833.583     -3.226      0.001   -4323.116   -1055.532
Legal services                                                                                        -1476.3662    620.056     -2.381      0.017   -2691.654    -261.078
Life Sciences                                                                                         -3789.8169   1210.582     -3.131      0.002   -6162.515   -1417.119
Management consultancy                                                                                  777.8451   1140.249      0.682      0.495   -1457.002    3012.692
Music, peforming, and visual arts                                                                     -3678.6338   1163.779     -3.161      0.002   -5959.599   -1397.669
Video games                                                                                           -4708.2113   1546.500     -3.044      0.002   -7739.296   -1677.127
==============================================================================
Omnibus:                    16262.678   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        470821625.887
Skew:                          32.708   Prob(JB):                         0.00
Kurtosis:                    1369.779   Cond. No.                     1.55e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.55e+07. This might indicate that there are
strong multicollinearity or other numerical problems.